### ISSUE TITLE
Prévoir l'élargissement des conditions d'accessibilité 

### ISSUE THREAD

**Issue by Jordan11** [CovidTrackerFr/vitemadose#106]
Sachant qu'à une date x le gouvernement va rendre disponible la vaccination, quand celle ci se rapproche, adapter les conditions d'accessibilité en amont pour permettre la prise de rdv en avance

**Comment by Maijin** [comment]
En fait cette issue est dupliqué avec 53 et aussi c'est qqchose qui doit se faire sur le front-end pour la timeline donc je ferme ici.

Duplicate of #53
