### ISSUE TITLE
Disponibilité VMD erronée (Doctolib)

### ISSUE THREAD

**Issue by Shasdo** [CovidTrackerFr/vitemadose#108]
Pour le département 43, et particulièrement le centre Yssingeaux, il indique une disponibilité mais une fois sur Doctolib, aucune date pour une première injection et date bien plus lointaine pour une éventuelle deuxième.

Problème depuis le début sur ce département/centre avec la date indiquée sur vitemadose qui se décale mais toujours sans rien derrière.

Bonne continuation.

![Screenshot_20210408-191346_Firefox](https://user-images.githubusercontent.com/4083901/114069141-f2c23280-989e-11eb-86e3-ca092e9445ce.jpg)

![Screenshot_20210408-191415_Firefox](https://user-images.githubusercontent.com/4083901/114069173-fb1a6d80-989e-11eb-91f6-80b2313642ea.jpg)

![Screenshot_20210408-191423_Firefox](https://user-images.githubusercontent.com/4083901/114069197-040b3f00-989f-11eb-9fe8-9c3e9bb62848.jpg)

**Comment by aureliancnx** [comment]
Je vois que le centre a bien été mis à jour tout seul. Il s'agit d'un problème d'actualisation des données

**Comment by Shasdo** [comment]
Le rendez vous détecté comme disponible est à présent pour le 15/04 contre le 13/04 hier.
Mais toujours rien pour une première injection une fois sur Doctolib. Le 21/04 est toujours proposé dans le cas d'une seconde.


![Screenshot_20210409-121456_Firefox](https://user-images.githubusercontent.com/4083901/114166148-aa9e2100-992d-11eb-8b32-68bb61ae758c.jpg)

**Comment by aureliancnx** [comment]
OK. Je viens de vérifier manuellement. En effet le scraper le détecte toujours. Après plusieurs vérifications en local, il y a bien plusieurs disponibilités sur cette organisation de centres.

En fait, le problème est que Doctolib a l'air de pas gérer les lieux de consultation correctement par défaut. On a 2 lieux de consultations sur la même URL, mais il est impossible pour nous de savoir le practice_id par défaut lorsque l'on va sur la page, si aucun n'est indiqué. Au lieu de prendre toutes les practice_id, j'ai pris seulement celles du premier lieu quand on arrive sur la page, ce qui permet de corriger le problème, et ça n'a pas l'air de casser la détection de disponibilité des autres centres.

En l'occurrence le centre de vaccination de Yssingeaux / Monistrol a l'air d'avoir un problème de gestion de calendriers en interne sur Doctolib, ce qui complique la détection correcte.

J'ai mis un petit fix sur ce problème là, il a l'air d'être très peu présent sur les autres centres.

Problème corrigé.
