### ISSUE TITLE
URL affiché sur VMD a nettoyer

### ISSUE THREAD

**Issue by Maijin** [CovidTrackerFr/vitemadose#117]
VMD affiche cette URL indiquant que des doses sont disponibles malheuresement, la presence de speciality_id restreint l'affichage a seulement une categorie de vaccin qui eux n'ont pas de rendez-vous disponibls - https://partners.doctolib.fr/centre-de-sante/metz/cvcptsm-centre-de-vaccination-cpts-metz?speciality_id=5494&enable_cookies_consent=1 

En revanche cette URL - https://partners.doctolib.fr/centre-de-sante/metz/cvcptsm-centre-de-vaccination-cpts-metz contient bien des rendez-vous associé a un autre type de vaccin.

L'issue consiste donc a nettoyer uniquement l'URL sans ses parametres sur le site VMD.

**Comment by aureliancnx** [comment]
OUI.

**Comment by aureliancnx** [comment]
Corrigé par https://github.com/CovidTrackerFr/vitemadose/commit/a0c80249c120055e35311a691e856a30b9afc217
