### ISSUE TITLE
Affichage de la Ville

### ISSUE THREAD

**Issue by Noezor** [CovidTrackerFr/vitemadose#120]
Quelqu'un a pointé sur Twitter que le formating de l'addresse n'était pas très naviguable sur la Front Page.

https://twitter.com/YH/status/1380814900281348097

J'ai vu que c'était car le nom était scrappé, mais pas particulièrement la ville. Mais mettre la ville en avant semble être en projet ici https://github.com/CovidTrackerFr/vitemadose/pull/114. 

Je suis chaud pour améliorer les scrappers pour aussi parser les villes / addresses cet après midi.

**Comment by iso8859** [comment]
J'ajoute que certains centre ont été déplacés et que l'adresse indiquée dans VMD est inexacte. Exemple CPTS de la Marque, Salle Mariane (Villeneuve d'Ascq 59) dans VMD qui est maintenant Centre de Vaccination COVID - Salle Concorde (toujours Villeneuve d'Ascq) dans Doctolib.

**Comment by aureliancnx** [comment]
> J'ajoute que certains centre ont été déplacés et que l'adresse indiquée dans VMD est inexacte. Exemple CPTS de la Marque, Salle Mariane (Villeneuve d'Ascq 59) dans VMD qui est maintenant Centre de Vaccination COVID - Salle Concorde (toujours Villeneuve d'Ascq) dans Doctolib.

Ça vient du CSV du gouvernement qui n’est pas à jour.

**Comment by tlevillayer** [comment]
J'ai ecris une fonction rapide qui trouve la ville à partir de l'adresse dans info_centres https://gist.github.com/tlevillayer/764cb7cec38090f4b7149c5609e4a57c .
A voir où il serait le mieux de le mettre

**Comment by Noezor** [comment]
https://github.com/grubounet/vitemadose/blob/60ffea3e6a232953e297f18be3eef0db182f8a4f/scraper/departements.py#L65-L71

T'as aussi cette regexp

**Comment by tlevillayer** [comment]
Ok merci, j'avais pas vu que c'était deja en prod :)

**Comment by Noezor** [comment]
Pour cette issue, le plus simple pour la résoudre serait de changer le [champ ici](https://github.com/CovidTrackerFr/vitemadose/blob/ef7ee479acda1c86204535eaccf7cedfe86ce9f4/scraper/scraper.py#L169) qui est récupéré par le front.

Je pense que c'est potentiellement une bonne première issue. @Maijin tu peux ajouter un tag ?

**Comment by Maijin** [comment]
C'est fix avec le nouveau front-end en fait
