### ISSUE TITLE
Aucun centre de vaccination trouvé par VMD pour le département du Jura (39)

### ISSUE THREAD

**Issue by baptistepl** [CovidTrackerFr/vitemadose#121]
VMD ne détecte plus les RDV dans le département du Jura 
![image](https://user-images.githubusercontent.com/32340024/114268165-089b3900-9a00-11eb-89ec-0a3d6b8fc7dc.png)

Pourtant, sur Doctolib, 3 centres proposent des RDV
![image](https://user-images.githubusercontent.com/32340024/114268197-2ff20600-9a00-11eb-96f4-2fe318caf4fe.png)
https://www.doctolib.fr/vaccination-covid-19/jura?ref_visit_motive_ids%5B%5D=6970&ref_visit_motive_ids%5B%5D=7005&ref_visit_motive_ids%5B%5D=7107

**Comment by Noezor** [comment]
Même raison que #122

**Comment by aureliancnx** [comment]
Fixé

**Comment by Noezor** [comment]
https://covidtracker.fr/vitemadose/#dep-39
Ça semble pas avoir été fix
