### ISSUE TITLE
Aucun centre de département actif pour le Gers (32)

### ISSUE THREAD

**Issue by Noezor** [CovidTrackerFr/vitemadose#122]
Le gers a eu plein de centres temporaires qui sont [encore indexés alors qu'ils n'existent plus en pratique](https://covidtracker.fr/vitemadose/#dep-32). À l'inverse, [les nouveaux centres temporaires ne le sont pas](https://www.doctolib.fr/centre-de-sante/mirande/centre-de-vaccination-covid-19-cd-32-gers?pid=practice-165028) et il semblerait y avoir beaucoup de disponibilité.

J'ai vu que c'était la même "enseigne" avec des sous-centres, comme pour #121 . Je ne sais pas si c'est qu'on ne sais pas parcer ce genre de pages, ou si c'est qu'elles n'ont pas été indexées. Je vais faire le tri pour le Gers.

**Comment by Noezor** [comment]
J'ai investigué et il semblerait que ce bug et #121 soient le même : le département a mis tous ses centres sur doctolib sur le même centre de vaccination, et on arrive pas encore à les parser. Comme ces 2 paquets de centres sont sur doctolib, la solution serait plutôt de voir si on peut pas les récupérer avec l'API de Doctolib, plutôt que créer 2 nouveaux cas de scrapping.

**Comment by aureliancnx** [comment]
Devrait être corrigé par https://github.com/CovidTrackerFr/vitemadose/commit/cca5f9a1ffde09a76dee41ae898a1aade106f986

**Comment by Noezor** [comment]
https://covidtracker.fr/vitemadose/#dep-39
Ça a pas été fix
