### ISSUE TITLE
Centre présent en double (Doctolib, Savoie)

### ISSUE THREAD

**Issue by rozierguillaume** [CovidTrackerFr/vitemadose#123]
Ce centre en Savoie (73) est présent en double.

Lien 1 : https://partners.doctolib.fr/centre-de-vaccinations-internationales/albertville/centre-de-vaccination-covid-maison-de-sante-d-albertville?speciality_id=5494&enable_cookies_consent=1

Lien 2 : https://partners.doctolib.fr/centre-de-vaccinations-internationales/albertville/centre-de-vaccination-covid-maison-de-sante-d-albertville?highlight%5bspeciality_ids%5d%5b%5d=5494

![image](https://user-images.githubusercontent.com/22763678/114271210-90893f00-9a10-11eb-8c7d-3c48ca18ea92.png)

**Comment by Maijin** [comment]
Devrait etre fix une fois que https://github.com/CovidTrackerFr/vitemadose/issues/117 est reglé

**Comment by Maijin** [comment]
En fait les URLs sont vraiment differentes:

https://partners.doctolib.fr/centre-de-sante/albertville/centre-de-vaccination-covid-maison-de-sante-d-albertville
vs 
https://partners.doctolib.fr/centre-de-vaccinations-internationales/albertville/centre-de-vaccination-covid-maison-de-sante-d-albertville

**Comment by aureliancnx** [comment]
Corrigé par https://github.com/CovidTrackerFr/vitemadose/commit/4d763206d1cfdc304078d69b7019447decbf7b59 & https://github.com/CovidTrackerFr/vitemadose/commit/de22edaa861ee8bfb23dcc6d4032681ac0c62c26
