### ISSUE TITLE
Manque de tests unitaires pour Ordoclic

### ISSUE THREAD

**Issue by aureliancnx** [CovidTrackerFr/vitemadose#125]
scraper/ordoclic.py                           108     89    18%   21-26, 30-33, 37-46, 50-58, 62-89, 93-116, 120-136

**Comment by Bouska** [comment]
Je prends !

**Comment by aureliancnx** [comment]
@Bouska T’as pu regarder un peu ?

**Comment by Bouska** [comment]
J'ai eu le temps de regarder ce week end, je vois comment il faut avancer, mais j'ai relativement peu de temps de disponible hors weekend. Donc il faudra soit attendre le weekend prochain soit mettre quelqu'un d'autre sur le coup en plus :smile:
