### ISSUE TITLE
Numero de Telephone incorrect

### ISSUE THREAD

**Issue by Maijin** [CovidTrackerFr/vitemadose#130]
Le numero doit etre normalisé: +33XXXXX

OK - https://github.com/CovidTrackerFr/vitemadose/blob/data-auto/data/output/83.json#L73
PAS OK - https://github.com/CovidTrackerFr/vitemadose/blob/data-auto/data/output/83.json#L133

Afin d'eviter:

"Salle Polyvalente de Riez"
"Robert Debre centre de vaccination"
![image](https://user-images.githubusercontent.com/1408600/114303475-9cd3d180-9ace-11eb-9114-9c9a9502d6dd.png)
![image](https://user-images.githubusercontent.com/1408600/114303488-aa895700-9ace-11eb-9289-67e584a6d359.png)

**Comment by Maijin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Numero de Telephone incorrect](https://trello.com/c/hAs7q25W/16-numero-de-telephone-incorrect)

**Comment by rozierguillaume** [comment]
Le premier bug (avec les points) semble récurrent, notamment sur les centres Doctolib 

![C020934B-6828-49C2-A305-EED6858F2B51](https://user-images.githubusercontent.com/22763678/114314974-3b772700-9afd-11eb-969f-ee4a910ab9a1.jpeg)

https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt83-var/age-plus75ans/

**Comment by Maijin** [comment]
Le numero doit etre normalisé: +33XXXXX

OK - https://github.com/CovidTrackerFr/vitemadose/blob/data-auto/data/output/83.json#L73
PAS OK - https://github.com/CovidTrackerFr/vitemadose/blob/data-auto/data/output/83.json#L133

**Comment by fcamblor** [comment]
J'ai tenté de normaliser les numéro de tel (détecter le +33 et le supprimer quand il apparaissait) mais je pense que j'ai été trop optimiste en me disant qu'il n'y aurait que 2 formats de numéros de tel :)

Je peux enlever ce que j'ai fait et afficher "tels quels" les numéros qu'on reçoit du back, ça évitera les bugs d'affichage dû à de mauvaises hypothèses de formatting.

Ça déporte cette logique d'homogénéisation coté back, ce qui n'est pas plus mal puisque ça bénéficiera à tout le monde.
