### ISSUE TITLE
URL affiché sur VMD a nettoyer v2 (enlever pid)

### ISSUE THREAD

**Issue by baptistepl** [CovidTrackerFr/vitemadose#132]
VMD détecte des RDV dans certains centres, mais le lien censé nous renvoyer vers la page du centre sur Doctolib ne fonctionne pas.
![2](https://user-images.githubusercontent.com/32340024/114304459-909e4300-9ad3-11eb-936a-0acb3ee5be6d.gif)
De plus, le centre ne propose aucun RDV quand on se met dessus, alors que VMD en détecte
![image](https://user-images.githubusercontent.com/32340024/114304470-9f84f580-9ad3-11eb-8651-58248ec474d7.png)

Je vais regarder si il y a d'autres problèmes de ce genre dans d'autres départements.

**Comment by Maijin** [comment]
Oui - il faut aussi qu'on enleve le pid des URLs renvoyés sur l'interface - https://partners.doctolib.fr/centre-de-sante/dole/ars-de-bourgogne-franche-comte?pid=practice-164482

**Comment by max5962** [comment]
Hello,

Je prend :)

**Comment by max5962** [comment]
Doublons #147 ?

Bon je viens de regarder et c'est plus compliqué que prévu.

En réalité, Vmd propose deux centres (même date même heure) alors qu'il y en a qu'un seul qui a de la dispo c'est celui de "Centre de vaccination des Rousses"

Le premier lien ne marche pas parce qu'il n'est pas sensé être disponible. Je regarde pourquoi il est détecté par VMD

**Comment by max5962** [comment]
Comme avec @Noezor , sa PR (https://github.com/CovidTrackerFr/vitemadose/pull/154) devrait résoudre ce ticket.

**Comment by Noezor** [comment]
Ça marche de mon côté. Le problème venait du fait que le centre affiché avec de la dispo n'était pas celui sur lequel on était redirigé.

Par exemple : 
https://partners.doctolib.fr/centre-de-sante/mirande/centre-de-vaccination-covid-19-cd-32-gers?pid=practice-165028
est un bon lien car il a un pid qui corespond au centre qu'on veut (qui a de la dispo)
Par contre, à cause de l'open data, des fois on redirigeait vers le mauvais site : 
https://partners.doctolib.fr/centre-de-sante/mirande/centre-de-vaccination-covid-19-cd-32-gers?pid=practice-165026

**Comment by Maijin** [comment]
On peut fermer pour le moment alors.
