### ISSUE TITLE
Centre avec 0 dose affiché

### ISSUE THREAD

**Issue by Maijin** [CovidTrackerFr/vitemadose#138]
![image](https://user-images.githubusercontent.com/1408600/114308296-98fe7a00-9ae3-11eb-8556-9199bd62ee9d.png)

Centre avec 0 dose affiché - Pharmacie du Mortier 01200

**Comment by tlevillayer** [comment]
Pour doctolib, l'erreur est due au fait qu'on affiche la date next_slot lorsqu'aucun créneau n'a été trouvé et la valeur prise "total" vaut 0
