### ISSUE TITLE
Pharmacie avec 0 dose dispo (Ordoclic)

### ISSUE THREAD

**Issue by rozierguillaume** [CovidTrackerFr/vitemadose#139]
Cette pharmacie est marquée comme ayant des RDV dispo (ce qui est le cas), mais le nombre de doses est erroné (0, au lieu de +).

Pharmacie : https://app.ordoclic.fr/app/pharmacie/pharmacie-du-mortier-valserhone

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/22763678/114308309-addb0d80-9ae3-11eb-8009-590f4880f30d.png">

**Comment by Maijin** [comment]
Duplicate of #138
