### ISSUE TITLE
Utiliser CenterInfo plutôt qu'un dict

### ISSUE THREAD

**Issue by Noezor** [CovidTrackerFr/vitemadose#141]
On a un joli objet [CenterInfo ici](uhttps://github.com/CovidTrackerFr/vitemadose/blob/9171f5608811c30b62cf3b78784ccbb33a9b00d5/scraper/pattern/center_info.py#L14) mais on le transforme en dictionnaire [ici](https://github.com/CovidTrackerFr/vitemadose/blob/a0fc80f2d287498c139874908a8c3f34cdce6ee6/scraper/scraper.py#L109) et cela nous réduit à manipuler des dictionnaires [plus tard](https://github.com/CovidTrackerFr/vitemadose/blob/a0fc80f2d287498c139874908a8c3f34cdce6ee6/scraper/scraper.py#L167-L197) ce qui nous fait perdre l'interet d'avoir créé un objet, et on perd tous les avantages de manipulation d'un objet typé. 

Ça serait très cool d'utiliser CenterInfo le plus possible.

**Comment by aureliancnx** [comment]
https://github.com/CovidTrackerFr/vitemadose/pull/159
