### ISSUE TITLE
Centre détecté comme dispo dans VMD mais n'existe pas sur Doctolib

### ISSUE THREAD

**Issue by baptistepl** [CovidTrackerFr/vitemadose#147]
https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt39-jura/age-plus75ans/
![image](https://user-images.githubusercontent.com/32340024/114317999-1f7a8200-9b0b-11eb-9b29-e0e29810019d.png)

**En cliquant sur "Changer de lieu" sur Doctolib, on remarque que ce centre n'est pas présent dans la liste car il n'est pas ouvert.**
https://partners.doctolib.fr/centre-de-sante/dole/ars-de-bourgogne-franche-comte?pid=practice-171878

**Comment by Maijin** [comment]
Merci @baptistepl, le bug est deja referencé dans l'issue #132.

Duplicate of #132
