### ISSUE TITLE
Add Multiprocessing (Pool) on MaPharma center scrape

### ISSUE THREAD

**Issue by Maijin** [CovidTrackerFr/vitemadose#152]
Add Multiprocessing (Pool) on MaPharma center scrape - https://github.com/CovidTrackerFr/vitemadose/actions/workflows/mapharma_center_scrap.yml

**Comment by gaelbenoit** [comment]
PR #158

**Comment by aureliancnx** [comment]
MaPharma va nous fournir de meilleures ressources que le scrap actuel.
