### ISSUE TITLE
Améliorations MaPharma.net

### ISSUE THREAD

**Issue by hurtrelj** [CovidTrackerFr/vitemadose#155]
Bonjour,

Je suis le développeur de mapharma.net, j'aimerais que l'on échange ensemble pour améliorer le système de récupération  des données, avec par exemple la fourniture de nouvelles pharmacies qui vont bientôt ouvrir.
Également des modifications sur le WebService utilisé sont prévues, et on pourrait donc échanger en avance de phase pour ne pas couper votre service.

Contactez moi par mail : jonathanhurtrel@groupeuniverspharmacie.com

Cordialement

**Comment by Maijin** [comment]
Bonjour et merci Jonathan, je viens de vous envoyer un e-mail - je ferme ici.
