### ISSUE TITLE
Lien direct vers la campagne MaPharma

### ISSUE THREAD

**Issue by hurtrelj** [CovidTrackerFr/vitemadose#156]
Le lien de la campagne de vaccination MaPharma.net peut être modifié pour présélectionner la campagne sur la page de prise de RDV en passant l'id de campagne (parametre c en GET), qui a permit la récupération des créneaux

Exemple : https://mapharma.net/68200?c=168

**Comment by Maijin** [comment]
CC @gaelbenoit

**Comment by gaelbenoit** [comment]
bonjour oui j'avais vu les paramètres c et l, ça ne m'a pas paru indispensable de préciser le c dans l'url car il est mis par défaut et peu de pharmacies ont des campagnes multiples. Je vais quand même regarder pour faire cette modification.
Sur ce sujet, un champ permettant d'identifier clairement la campagne, ou un intitulé commun nous serait très utile, car l'id de campagne et son intitulé me semble propre à chaque pharmacie, j'en ai même trouvé une avec 2 campagnes: vaccin vendredi & vaccin samedi :D

**Comment by Maijin** [comment]
Je ferme ici du coup
