### ISSUE TITLE
RDV non détectés (Keldoc, Toulouse)

### ISSUE THREAD

**Issue by rozierguillaume** [CovidTrackerFr/vitemadose#161]
Des centaines de rdv ne sont pas détectés sur ce centre « CVD31 - Grand Centre Hall 8 Ile Ramier » à Toulouse (31)

https://vaccination-covid.keldoc.com/redirect/?dom=cabinet-medical&inst=toulouse-31000&user=vaccinodrome-toulouse&motive=88503&category=3243&cabinet=18777&specialty=144

**Comment by aureliancnx** [comment]
Corrigé par https://github.com/CovidTrackerFr/vitemadose/pull/163 !

**Comment by tdevlaeminck** [comment]
Un utilisateur me remonte que ce centre n'est pas visible sur VMD : https://www.keldoc.com/cabinet-medical/toulouse-31000/vaccinodrome-toulouse/vaccinodrome-toulouse?motive=88503&category=3243&cabinet=18777&specialty=144&agenda=53155,53172,53160,53159,53171,53163,53168,53165,53157,53154,53174,53164,53173,53158,53161,53166,53167,53156,53162,53169,53170

Je vous confirme que je ne le vois pas sur VMD. Or il me semble que c'est le même centre que celui présenté dans cette issue.

**Comment by Maijin** [comment]
Probablement pas le meme probleme @tdevlaeminck je te conseille d'ouvrir de nouvelles issues a la place

**Comment by Maijin** [comment]
Ouvert ici https://github.com/CovidTrackerFr/vitemadose/issues/269
