### ISSUE TITLE
Doublons dans les centres répertoriés sous différents URLs

### ISSUE THREAD

**Issue by Noezor** [CovidTrackerFr/vitemadose#172]
/!\ Attention de ne pas être trop agressif dans le critère d'unicité. C'était la source de plusieurs problèmes #122 #121 #132 . Ne pas modifier la donnée !

#166 a fix ^ mais a introduit des doublons. Les enlever n'est pas facile : les doublons proviennent de l'open-data qui n'est pas à jour sur les URLs. On scrap un URL sur doctolib, et un autre sur l'opendata, et [comme l'unicité se fait à partir de l'URL](https://github.com/CovidTrackerFr/vitemadose/blob/main/scraper/scraper.py#L236-L243), ils ne sont pas détectés comme différents.

Comme fix potentiel, on pourrait arrêter de scrap l'opendata pour les centres doctolib, mais il fait être sûr qu'on n'enlève que des doublons, et pas des vrais centres.

![image](https://user-images.githubusercontent.com/8218350/114543709-d8e76d80-9c59-11eb-8983-87414e8d90d4.png)
^ les liens mais aussi les addresses sont différentes alors que cela correspond au même centre.

**Comment by rozierguillaume** [comment]
Cet exemple aussi, à voir si c'est le même cas ou pas

https://twitter.com/cyril_granite/status/1382010886668365825?s=21

**Comment by Noezor** [comment]
Yes même cas, franchement j'ai pas d'idée pour uniciser... L'exemple que j'ai montré il n'y a ni exactement le même nom, ni même numéro de téléphone. 

La seule solution c'est de virer datagouv pour doctolib.

**Comment by tlevillayer** [comment]
Mais avec le num id quand on regarde les données sur doctolib, c'est pas possible ?

**Comment by Noezor** [comment]
Nop, ils sont différents entre doctolib et l'open data !

**Comment by Noezor** [comment]
https://twitter.com/_amomentintime/status/1382041321528029190

Un autre

**Comment by Noezor** [comment]
#176 devrait fix ces doublons
