### ISSUE TITLE
Nom de centres identiques mais différents

### ISSUE THREAD

**Issue by baptistepl** [CovidTrackerFr/vitemadose#173]
Certains centres affichent un nom identique sur VMD et n'est donc pas très explicite. Si on regarde l'adresse, on peut savoir où c'est mais imaginons que l'utilisateur se focalise sur le nom du centre en gras, il va se demander quel centre ça peut être.

Par exemple, dans le département du Jura, la majorité des centres ont le même nom "ARS de Bourgogne-Franche-Comté - Jura". Ne serait-il pas plus judicieux d'ajouter le nom de la ville dans le nom du centre ? Ou de remplacer "ARS de Bourgogne-Franche-Comté - Jura" par "Centre de Vaccination - Ville -" ?

Ce genre de problème concerne donc actuellement les départements suivants - les noms entre guillemets représentent les noms de centres identiques pour les départements concernés - :
- Jura (39) : "ARS de Bourgogne-Franche-Comté - Jura"
- Deux-Sèvres (79) : "Centre de vaccination Covid-19 - SDIS 79"
- Tarn (81) : "Centres de Vaccination Covid-19 du Tarn"
- Var (83) : "Centre de vaccination Covid 19 du VAR - Vaccination Covid-19"
- Haute-Vienne (87) : "[Limousin] Vaccination COVID-19"
- Essonne (91) : "Centre de Vaccination COVID - Conseil Départemental de l'Essonne (CD91)"
- Val d'Oise (95) "Centre de vaccination territorial du Haut Val d'Oise" & "Centre de vaccination territorial Centre Val d'Oise"

**Comment by aureliancnx** [comment]
Doctolib qui fournit des noms de centres pas explicites... :)

**Comment by Noezor** [comment]
Baptiste on tombe exactement sur les mêmes problemes hehehe
C'est encore lié aux PIDs. Quand un centre a plusieurs sous-centres, ils ont tous le même nom. Je sais pas à quel endroit du code ça serait mieux de faire ce fix...

**Comment by aureliancnx** [comment]
Devrait être corrigé par la PR merged de @Noezor ?

**Comment by aureliancnx** [comment]
Corrigé par https://github.com/CovidTrackerFr/vitemadose/pull/177
