### ISSUE TITLE
[Maiia] Centre dispo dans VMD avec 0 dose => dans Maiia impossible de réserver

### ISSUE THREAD

**Issue by Toomaaa** [CovidTrackerFr/vitemadose#175]
Hello,

Centre dans le 69 : 
![image](https://user-images.githubusercontent.com/8841899/114588125-a142ea80-9c86-11eb-9025-e09f61f17d45.png)

Dispo avec 0 dose.
Dans Maiia :

![image](https://user-images.githubusercontent.com/8841899/114588177-b0c23380-9c86-11eb-9f43-ffaa3db95182.png)

A noter qu'il y a deux motifs, qui ont l'air identique. Et pour les deux motifs c'est la même chose :
![image](https://user-images.githubusercontent.com/8841899/114588258-c3d50380-9c86-11eb-8695-6e8e7b0d4674.png)

**Comment by Maijin** [comment]
Je pense c'est un dup avec #168 qui a une PR ouverte

**Comment by nhumblot** [comment]
#168 a été ouvert sur un centre Maiia aussi oui. J'essaye de regarder ce soir. :slightly_smiling_face:

**Comment by Maijin** [comment]
ok then Duplicate of #168
