### ISSUE TITLE
Centre dupliqués

### ISSUE THREAD

**Issue by Maijin** [CovidTrackerFr/vitemadose#178]
Centre dupliqués dans le JURA

https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt39-jura/age-plus75ans/

2 URLs:

- https://partners.doctolib.fr/centre-de-sante/dole/ars-de-bourgogne-franche-comte?pid=practice-164598
- https://partners.doctolib.fr/centre-de-sante/dole/ars-de-bourgogne-franche-comte?pid=practice-164598&%3fspeciality_id=5494

<img width="1269" alt="image" src="https://user-images.githubusercontent.com/1408600/114690202-c4b57600-9d16-11eb-8ea4-ff4098b3d783.png">

**Comment by Maijin** [comment]
<img width="826" alt="image" src="https://user-images.githubusercontent.com/1408600/114691084-997f5680-9d17-11eb-9907-2cb8add57258.png">

https://partners.doctolib.fr/hopital-public/chateau-salins/centre-de-vaccination-covid-19-hopital-de-chateau-salins?pid=practice-165120

https://partners.doctolib.fr/hopital-public/chateau-salins/centre-de-vaccination-covid-19-hopital-de-chateau-salins

**Comment by aureliancnx** [comment]
Réglé pour le speciality_id : https://github.com/CovidTrackerFr/vitemadose/commit/f725ca1bcb61bb504d507e7acc205ba05315da36
