### ISSUE TITLE
Doctolib - Ajouter un flag dans le JSON pour les centres avec rendez-vous telephonique uniquement

### ISSUE THREAD

**Issue by Maijin** [CovidTrackerFr/vitemadose#180]
Beaucoup de centres ne sont disponibles que par telephone. Ces centres sont noyés sur le frontend, pour ameliorer la visiblité je propose d'ajouter un flag `tel_only` dans le JSON qui les identifie:

`tel_only`: `True` ou `False`

Par exemple https://partners.doctolib.fr/centre-de-sante/vesoul/centre-de-vaccination-covid-19-de-vesoul?speciality_id=5494

<img width="352" alt="image" src="https://user-images.githubusercontent.com/1408600/114839924-97300180-9dd6-11eb-9101-cc0119de6b24.png">

**Comment by quinao** [comment]
Je commence à regarder.

**Comment by quinao** [comment]
On parle de quel fichier JSON : doctolib-centers.json ou info_centres.json ?

**Comment by Maijin** [comment]
Les 01.json, 02.json,...  - https://github.com/CovidTrackerFr/vitemadose/tree/data-auto/data/output

**Comment by aureliancnx** [comment]
Ajouté par https://github.com/CovidTrackerFr/vitemadose/commit/00ebcd876c1ca792c2b166c8a0c59bc73a1f50f1

Il suffit d'appeler la fonction pour Ordoclic etc.. pour les autres centres
