### ISSUE TITLE
Aucun RDV dans certains départements

### ISSUE THREAD

**Issue by baptistepl** [CovidTrackerFr/vitemadose#181]
Dans VMD, il n'y aucun RDV détecté pour certains départements alors qu'il y en a sur Doctolib
Ces départements sont :
- Ardennes (08)
- Indre (36)

**Comment by aureliancnx** [comment]
Les Ardennes semblent OK, l'Indre vient de la façon bizarre de doctolib de gérer le nom de ce département.

Corrigé par https://github.com/CovidTrackerFr/vitemadose/commit/caf86e46a4aaae3bd4a95e4fafc6af6d29e92cba

**Comment by aureliancnx** [comment]
Corrigé
