### ISSUE TITLE
Centre indisponibles mais rendez-vous disponibles

### ISSUE THREAD

**Issue by Maijin** [CovidTrackerFr/vitemadose#184]
E.g
<img width="844" alt="image" src="https://user-images.githubusercontent.com/1408600/114832745-1cafb380-9dcf-11eb-8685-f918dcf048a6.png">
https://partners.doctolib.fr/centre-de-sante/vesoul/ars-de-haute-saone?pid=practice-164265

<img width="956" alt="image" src="https://user-images.githubusercontent.com/1408600/114832768-220cfe00-9dcf-11eb-9418-ddc55878732d.png">

**Comment by aureliancnx** [comment]
Après vérification des informations du centre, il semblerait que le practice id n'est pas bon et que cela cause des problèmes de scrap, on gère déjà beaucoup d'erreurs avec le practice id mais il semblerait que les agendas n'arrivent pas à être reliés.

ça demande un fix
