### ISSUE TITLE
Ordoclic - Ajouter un flag dans le JSON pour les centres avec rendez-vous telephonique uniquement

### ISSUE THREAD

**Issue by Maijin** [CovidTrackerFr/vitemadose#197]
Exemple dans le 38 - https://app.ordoclic.fr/app/pharmacie/pharmacie-martin-pinel-pont-de-cheruy

`tel_only`: `True` ou `False`

<img width="837" alt="image" src="https://user-images.githubusercontent.com/1408600/115053970-fcbbe500-9edf-11eb-88a4-6123a08564a6.png">

<img width="391" alt="image" src="https://user-images.githubusercontent.com/1408600/115054029-0f361e80-9ee0-11eb-86fd-b8c8afcf7fb7.png">

**Comment by aureliancnx** [comment]
C'est le même cas pour certains centres sur d'autres plateformes (j'ai vu ça sur Keldoc, Maiia je ne suis pas sûr)

Il faudrait unifier ça, c'est juste de la donnée à filtrer sur chaque scraper

**Comment by aureliancnx** [comment]
Done https://github.com/CovidTrackerFr/vitemadose/commit/0778decfb57ca6765a7de48f603291affccb078a
