### ISSUE TITLE
Ordoclic : "N'a pas pu être ratachée à un département connu"

### ISSUE THREAD

**Issue by Noezor** [CovidTrackerFr/vitemadose#201]
`
2021-04-17 09:16:13,050 | [WARNING] le centre Pharmacie Tournamy () n'a pas pu être rattaché à un département connu
`

Cela cause le centre de ne pas être affiché corrèctement scrap. Pourtant, dans info-centres, cette pharma figure avec un centre, ce qui indique qu'on a bien réussi à la scrap à un moment.

**Comment by tlevillayer** [comment]
Cette pharmacie n'est pas plutot sur Ordoclic ?

**Comment by gaelbenoit** [comment]
Le code postal est mal saisi chez Ordoclic


![image](https://user-images.githubusercontent.com/11502741/115954336-b292bf00-a4f0-11eb-9eed-2ee5c91893f2.png)

Du coup elle apparaît bien dans info_centres mais dans le 06...

**Comment by Noezor** [comment]
Ok, je les appelle dans l'après midi :)

**Comment by Noezor** [comment]
Mhh ça serait quoi le code zip correct ? `06250` ? Je pense qu'on pourrait le normaliser :)

**Comment by gaelbenoit** [comment]
en fait c'est déjà réglé par la PR #210 qui normalise les CP à 4 caractères en ajoutant un 0 devant (format_cp)
j'ai vérifié dans le log des derniers pipelines pas d'erreur (enfin au moins pour celle-ci)

https://github.com/CovidTrackerFr/vitemadose/blob/c3e1f87fee19e3ecc38eedf305820ac8e1309141/utils/vmd_utils.py#L120-L138
