### ISSUE TITLE
[Maiia] Scrap les dates de test plutôt que de vaccin

### ISSUE THREAD

**Issue by Noezor** [CovidTrackerFr/vitemadose#212]
![image](https://user-images.githubusercontent.com/8218350/115144842-221b3100-a04f-11eb-9f59-af71cb7dadd7.png)
La [Pharmacie L'Aquarius](https://www.maiia.com/pharmacie/75019-paris/pharmacie-de-l-aquarius?centerid=602cf98a236ce7156a7603e5) n'a pas de vaccination disponnible. J'ai regardé sur le workflow gitlab, il semble qu'on trouve des dates qui correspondent aux dates de test.

**Comment by gaelbenoit** [comment]
Voilà c'est corrigé: le nouveau script fait bien la différence, cette pharmacie (qui a des rdv mais pas pour de la vaccination) ne remonte plus
![image](https://user-images.githubusercontent.com/11502741/115147245-6bbd4900-a05a-11eb-92b6-8c6aee924bd1.png)
