### ISSUE TITLE
[Miia] Doses disponibles à tord

### ISSUE THREAD

**Issue by max5962** [CovidTrackerFr/vitemadose#220]
Département du Nord : plus de 600 doses
![image](https://user-images.githubusercontent.com/34659571/115259824-8236d380-a132-11eb-9e38-5b182aa0b6d2.png)

alors qu'en cliquant sur le lien le lien : 
https://www.maiia.com/pharmacie/59770-marly/pharmacie-de-la-rhonelle?centerid=603e4fae8c512e753fc49ba1
![image](https://user-images.githubusercontent.com/34659571/115260014-a98da080-a132-11eb-8d0a-f2ac6d435184.png)

Nous avons que des tests COVID et non de la vaccination.

**Comment by gaelbenoit** [comment]
le champs 'injectionType' est égal à FIRST, ça ne devrait pas être le cas pour un dépistage, c'est une mauvaise saisie côté Maiia...

![image](https://user-images.githubusercontent.com/11502741/115288287-91794980-a151-11eb-9f1b-09ae8e38c8f3.png)

**Comment by max5962** [comment]
Pourquoi pas avoir une méthode de filtrage de dernier recours.
Genre "name= *antigénique*"
Il y a peut être d'autres pharmacies dans cette erreur de saisie ?
