### ISSUE TITLE
Doctolib - Whitelisting echec

### ISSUE THREAD

**Issue by renaudrouas** [CovidTrackerFr/vitemadose#227]
Bonjour,
Je suis désolé j'ouvre une issue même si il ne s'agit pas d'une erreur mais bien d'un problème de notre côté !
Nous essayons d’implémenter votre solution pour le compte de la Métropole Aix Marseille Provence afin de proposer votre service aux citoyens de la région sur le portail qui référence les services Métropolitains.
Bien entendu nous y faisons clairement référence à votre travail et à votre site.

Tout marche parfaitement sauf l'import des données Doctolib. Ils nous bloquent dès le second appel.
Je n'arrive pas à rentrer en contact avec eux pour avancer sur le projet.

Pouvez vous nous aider svp ?

A votre disposition pour en discuter :
renaud.rouas@inetum.world

**Comment by rozierguillaume** [comment]
Bonjour,

Merci pour votre message. Nous ne pouvons malheureusement pas vous aider sur ce point, nous sommes indépendants de Doctolib. Ce dépôt n’a pas été créé dans le but d’être implémenté plusieurs fois, cela pouvant surcharger les plateformes de réservation. La métropole Aix-Marseille peut en revanche référencer l’outil Vite Ma Dose, qui est accessible sur vitemadose.covidtracker.fr. 

Bonne journée 
Guillaume
