### ISSUE TITLE
Issue in the distances computation

### ISSUE THREAD

**Issue by pedugnat** [CovidTrackerFr/vitemadose#229]
It seems there is an issue in how distances between the localisation and the centers are computed. 

Here I tried with Valence (26000) and it proposed me a center in Le Cheylard, indicating 6.3km (cf. screenshot 1).
It turns out Valence-Le Cheylard is ~55km (cf. screenshot 2). I guess the issue may come from the fact that the center's address is not the right one, or from the way distances are computed. 

Config : laptop Chrome for MacOS Version 90.0.4430.72 (Build officiel) (x86_64)

![image](https://user-images.githubusercontent.com/34744445/115377138-a0064600-a1cf-11eb-8a10-f125936b7268.png)
![image](https://user-images.githubusercontent.com/34744445/115377212-b0b6bc00-a1cf-11eb-9e02-74052f9a99a3.png)

**Comment by Noezor** [comment]
C'est calculé du coté du front car on veut minimiser les données des users qui touchent le serveur, j'ai fait une issue de leur côté aussi

**Comment by fcamblor** [comment]
I just created a custom google map with coordinates : https://www.google.com/maps/d/edit?mid=1eW8DAiaYzexTlQWqA7GXnTEhkLLSIVg4&usp=sharing

- In Blue : how Google resolves Valence & Le Cheylard
- In Yellow : what are the coordinates for Valence city & Le Cheylard center

=> We have clear discrepancies between Google and [Maiia coordinates](https://www.maiia.com/centre-de-vaccination/07160-le-cheylard-/centre-de-vaccination-le-cheylard?centerid=6033e4c60e0f7505a337ae0a) for this center

Not sure who is right though..

**Comment by pedugnat** [comment]
For living in this area, Le Cheylard is indeed ~50km away from Valence, not 6km. It seems the problem indeed comes from the yellow dots, ie the data coming from Maia if I understood well.

**Comment by fcamblor** [comment]
Yep, that's it 👍

**Comment by Noezor** [comment]
A fermer car problème de data de chez Maiia

**Comment by Bouska** [comment]
S'il y a eu un problème à un moment avec les données, c'est corrigé maintenant, le centre est maintenant géolocalisé (vaguement) au bon endroit https://www.google.com/maps/place/44%C2%B055'17.0%22N+4%C2%B027'02.9%22E/@44.9214038,4.4486113,17z/data=!3m1!4b1!4m5!3m4!1s0x0:0x0!8m2!3d44.9214!4d4.4508

**Comment by pedugnat** [comment]
@Bouska Manifestement il semble que la distance affichée ne soit toujours pas la bonne... 

![image](https://user-images.githubusercontent.com/34744445/115964961-3071bd00-a527-11eb-9faa-6c6ee9059a43.png)

**Comment by Bouska** [comment]
Je viens de vérifier, il y a deux erreurs en fait : la première c'est que ce centre ne devrait a fortiori pas exister ; la deuxième c'est que la géolocalisation de ce "centre" par Maiia le place sur la commune de Soyons. La distance colle à la distance Valence-Soyons. Je vais aller voir comment corriger le premier problème (qui corrigera le second).

**Comment by Bouska** [comment]
Corrigé par #251
