### ISSUE TITLE
Keldoc - mauvais type de vaccin

### ISSUE THREAD

**Issue by Maijin** [CovidTrackerFr/vitemadose#230]
Depuis le tweet - https://twitter.com/EP37803629/status/1384827461070950402

https://vaccination-covid.keldoc.com/redirect/?dom=centre-municipal-de-sante&inst=lannion-22300&user=centre-de-vaccination-de-lannion

Le centre propose un motif "1ere injection suite a Astrazeneca" ce qui ne signifie pas necessairement "Astrazeneca".

Potentiellement il faudrai rajouter un denyfiltre pour ce cas specifique pour ne pas retourner un nom de vaccin incorrect.

![image](https://user-images.githubusercontent.com/1408600/115546166-fc876500-a2a4-11eb-945d-30f16655fdd7.png)

**Comment by rozierguillaume** [comment]
Voici le type de filtre qui pourrait être utilisé :

![FE277788-36DE-42B1-8E23-2B8ECEE167D0](https://user-images.githubusercontent.com/22763678/115740241-eb1a8780-a38e-11eb-8d17-76cb7792f832.jpeg)

**Comment by Noezor** [comment]
Je m'en occupe dans l'après midi :)

**Comment by Maijin** [comment]
Pas totalement fixé il y a encore des centres qui affichent encore astrazeneca par exemple https://vaccination-covid.keldoc.com/redirect/?dom=maison-de-sante&inst=lamballe-22400&user=lamballe

![image](https://user-images.githubusercontent.com/1408600/116736728-90b5a280-a9f0-11eb-8a69-03321a6628dc.png)
![image](https://user-images.githubusercontent.com/1408600/116736735-9317fc80-a9f0-11eb-9179-40d4f550e393.png)

**Comment by Bouska** [comment]
Le problème c'est que ce centre utilise le caractère moins (voire un demi cadratin je ne sais pas trop) pour "- de 55 ans" (cf. mon commentaire ici https://github.com/CovidTrackerFr/vitemadose/pull/260#discussion_r623333363)

**Comment by Noezor** [comment]
Waaaaaa, je croyais que t'étais fatigué et que tu avais tapé 3 fois le même caractère ... Vous êtes vraiment fort en qualité à la QA

**Comment by Bouska** [comment]
J'avais bien les yeux en face des trous :stuck_out_tongue_closed_eyes: et je parlais du bordel qu'est la [typographie des tirets](https://fr.wikipedia.org/wiki/Tiret#Codage_informatique). Logiquement, on devrait récupérer des "trait d'union-signe moins/tiret quart de cadratin" (ASCII 0x2D) [le fameux tiret du 6], des vrais "signe moins" (unicode U+2212) [le bon tiret d'un point de vue typographique] et potentiellement aussi des "tirets demi cadratin" (unicode U+2013) [je me demande si Word ne converti pas les '-' au milieu d'un phrase par ce caractère].

**Comment by Noezor** [comment]
https://twitter.com/PierrickBedouch/status/1388415388392828930 un autre report, ajouté aux test cases sur la PR

**Comment by Maijin** [comment]
J'ai vérifié tout bon
