### ISSUE TITLE
Médecin du 62 qui apparait dans les résultats du dep 80

### ISSUE THREAD

**Issue by tdevlaeminck** [CovidTrackerFr/vitemadose#238]
Lorsque l'on fait une recherche dans le département 80 (Somme) on a le Dr Jean Cattiau basé dans le 62 qui apparait dans les résultats.

![image](https://user-images.githubusercontent.com/82476476/115900996-ecb48000-a460-11eb-823f-bdb25ada9366.png)

**Comment by tlevillayer** [comment]
La donnée associée au code postal 62760 renvoie la ville THIEVRES avec un code insee 80756 dans le fichier codepostal_to_insee.json, ensuite utilisé pour déterminer le département.

"62760": {
        "insee": "80756",
        "nom": "THIEVRES"
    }

Reste à déterminer pourquoi cette association est déterminée de cette façon

**Comment by Bouska** [comment]
Les joies de la France. Le code postale `62720` est rattaché à 15 communes, dont Mondicourt ainsi que [Thièvres](https://fr.wikipedia.org/wiki/Thi%C3%A8vres_(Pas-de-Calais)), toutes dans le 62, mais aussi le [Thièvres](https://fr.wikipedia.org/wiki/Thi%C3%A8vres_(Somme)) qui est dans la Somme (selon les sources), parce que pour je ne sais quelle raison, quelqu'un a décidé de couper une commune en deux entre deux départements pour en faire deux communes du même nom.  Dans notre base CP-INSEE, le CP [`62720`](https://github.com/CovidTrackerFr/vitemadose/blob/76333b7e67380f985a625a250bd1d9c920cd3fa4/data/input/codepostal_to_insee.json#L15502) est rattaché au Thièvres, de la Somme, donc du coup tous les communes rattachés au CP `62760` seront rattaché à la Somme.

**Comment by tlevillayer** [comment]
Est-ce qu'on pourrait modifier le fichier CP-INSEE manuellement pour mettre un code insee dans le bon departement ? Ca sera bon pour 15 communes et faux pour le Thievres de la Somme, alors que maintenant c'est le contraire.

**Comment by gaelbenoit** [comment]
On peut aussi utiliser api-adresse.data.gouv.fr

![image](https://user-images.githubusercontent.com/11502741/115911581-8c2c3f80-a46e-11eb-9dff-d2a0459c57f6.png)

**Comment by Noezor** [comment]
Ok pour les 2 solutions. @tlevillayer tu fais un fix pour ce cas, et on essaye de bouger sur l'API du gouvernement pour un changement un peu plus solide ?

**Comment by tlevillayer** [comment]
Solution temporaire => PR #245
