### ISSUE TITLE
Mauvais centre indiqué dans VMD

### ISSUE THREAD

**Issue by baptistepl** [CovidTrackerFr/vitemadose#239]
Pour le centre indiqué ci-dessous, le centre n'est pas bon car il s'agit du centre Jura Parc - Hall Lacuzon - Entrée B
Rue du 19 Mars 1962, 39570 Lons-le-Saunier, le lien est correct par contre.
![image](https://user-images.githubusercontent.com/32340024/115916827-9d2c7f00-a475-11eb-8cef-914c65fe4da7.png)

**Comment by gaelbenoit** [comment]
en fait le lien de ce centre est https://partners.doctolib.fr/centre-de-sante/dole/ars-de-bourgogne-franche-comte ce qui amène à la page Doctolib de l'ARS qui contient 19 centres, dont celui d'Orgelet. Comme le pid n'est pas précisé dans le lien l'adresse affichée est la première des 19. Il faudrait donc que le lien soit avec le pid https://partners.doctolib.fr/centre-de-sante/dole/ars-de-bourgogne-franche-comte?pid=practice-165027

![image](https://user-images.githubusercontent.com/11502741/115951253-034dec00-a4e0-11eb-90a0-4984b9219e0e.png)

**Comment by gaelbenoit** [comment]
J'ai fait quelques vérifications, c'est une erreur d'enregistrement côté Doctolib. Le champ place_id n'est pas renseigné (alors qu'il l'est pour les autres centres de ce groupe)

![image](https://user-images.githubusercontent.com/11502741/115952109-9721b700-a4e4-11eb-88bc-6103b339c4a1.png)

Du coup même sur le site de Doctolib l'adresse bug, on peut sélectionner Orgelet à droite mais c'est Lons-le-Saunier qui est sélectionné à gauche (premier de la liste par défaut vu qu'il n'y a pas de place_id)

![image](https://user-images.githubusercontent.com/11502741/115952078-6fcaea00-a4e4-11eb-8b9c-eea36b771bf1.png)

**Comment by Noezor** [comment]
On passe par Guillaume pour contacter doctolib ?

**Comment by gaelbenoit** [comment]
je viens de leur envoyer un msg sur twitter, on va voir si leur CM fait suivre 😁

**Comment by tlevillayer** [comment]
En fait, on peut récupérer les infos du centre directement à l'adresse suviante : 
Si on regarde le json à https://www.doctolib.fr/booking/ars-de-bourgogne-franche-comte.json , la 14e valeur de data[places] comporte les infos du centre cherché
![image](https://user-images.githubusercontent.com/73873761/116007092-53c36780-a60e-11eb-8b5b-fbbf0712787c.png)

**Comment by grubounet** [comment]
@Maijin c'est corrigé, tu peux close ?
