### ISSUE TITLE
Date stats.json

### ISSUE THREAD

**Issue by dumoulinjb** [CovidTrackerFr/vitemadose#240]
Serait-il possible d'avoir la date des données qui permettent le calcul des statistiques du fichier stats.json ? Merci

**Comment by Bouska** [comment]
J'avais remonté cette demande à un moment donnée et on m'a dit que la date de commit devrait être suffisant pour avoir un timestamp de la stat, ce qui se tient.

**Comment by dumoulinjb** [comment]
Je ne connais pas la mécanique de publication, mais en tout cas rien ne donne cette date via l'url : https://vitemadose.gitlab.io/vitemadose/stats.json

**Comment by Maijin** [comment]
Fixed in https://github.com/CovidTrackerFr/vitemadose/pull/298

**Comment by dumoulinjb** [comment]
@Maijin pourquoi ce revert ?
