### ISSUE TITLE
Fréquence de mise à jour de stats_by_date.json

### ISSUE THREAD

**Issue by rozierguillaume** [CovidTrackerFr/vitemadose#244]
On aimerait bien mettre en lumière les stats sur le front, mais le fichier stats_by_date.json est mis à jour irrégulièrement. Est-ce possible de le mettre à jour à intervalle régulier ?

<img width="1170" alt="image" src="https://user-images.githubusercontent.com/22763678/115985303-8e47e880-a5ab-11eb-8dec-323299e170f7.png">

**Comment by aureliancnx** [comment]
Corrigé
