### ISSUE TITLE
Centre doctolib non détecté

### ISSUE THREAD

**Issue by gaelbenoit** [CovidTrackerFr/vitemadose#248]
Ce centre ne remonte pas dans le fichier doctolib-centers.json

https://www.doctolib.fr/centre-de-sante/paris/centre-de-vaccination-covid-ville-de-paris-mairie-du-15e-creneaux-dedies

![image](https://user-images.githubusercontent.com/11502741/115988217-e20cfe80-a5b8-11eb-9920-6cae5b2f6d98.png)

attention à ne pas confondre avec un autre centre Doctolib à la même adresse mais ce n'est pas le même (et celui-ci remonte bien mais n'a pas de dispo)
https://partners.doctolib.fr/centre-de-sante/paris/centre-de-vaccination-covid-paris-15e

**Comment by Bouska** [comment]
J'ai regardé ce problème dans le détail. Concrètement, que ce soit dans les [pages JSON](https://www.doctolib.fr/vaccination-covid-19/paris.json) ou le [site web](https://www.doctolib.fr/vaccination-covid-19/paris?page=1&ref_visit_motive_ids%5B%5D=6970&ref_visit_motive_ids%5B%5D=7005&ref_visit_motive_ids%5B%5D=7107&ref_visit_motive_ids%5B%5D=7945), ce centre n'apparaît pas, ce qui explique qu'on ne le récupère pas. Sur le pourquoi il n'apparaît pas, je pense que ça doit être un problème interne à Doctolib (les 2 centres au 31 rue Peclet ont le même practice_id, peut-être que ça explique cela)

**Comment by grubounet** [comment]
Le 1er lien n'est plus accessible ?

**Comment by Maijin** [comment]
La page n'existe plus et le second n'a pas de dose pour le moment

**Comment by Maijin** [comment]
Je ferme pour le moment
