### ISSUE TITLE
[Keldoc] Vaccins identifiés comme AZ alors que ARNm

### ISSUE THREAD

**Issue by Noezor** [CovidTrackerFr/vitemadose#250]
https://twitter.com/Poyonoz/status/1386235109402202113

https://vaccination-covid.keldoc.com/redirect/?dom=centre-municipal-de-sante&inst=st-brieuc-22000&user=robien-saint-brieuc&category=-1&cabinet=16618&specialty=144

Il y a marqué "suite à Astra-zeneca" dans motif de consultation, et on identifie le centre comme un centre qui donne du AZ alors que non...

**Comment by Bouska** [comment]
Duplicate de #230
