### ISSUE TITLE
le vaccinodrome de Vannes est absent dans le 56-Morbihan

### ISSUE THREAD

**Issue by BrunoSpy** [CovidTrackerFr/vitemadose#253]
Initialement posté dans covidtracker-tools par @fjoussellin
Bonjour,
Le vaccinodrome de Vannes ne semble pas répertorié par Vitemadose ...
Son adresse est : Centre de vaccination - Vannes Kercado 28 Rue Winston Churchill, 56000 Vannes (c'est le gymnase de Kercado).
On peut facilement le retrouver sur doctolib : https://www.doctolib.fr/hopital-public/vannes/centre-de-vaccination-covid-19-vannes-kercado
alors que sur Vitemadose, il semble répertorié à l'adresse : https://partners.doctolib.fr/hopital-public/vannes/ghba-centre-de-vaccination-covid-vannes

Merci pour cet excellent outil,
Bon courage à tous,
François

**Comment by Bouska** [comment]
J'ai vérifié rapidement, c'est le même problème que #248. Le centre n'est tout simplement pas listé dans https://www.doctolib.fr/vaccination-covid-19/morbihan.json (par contre, c'est https://www.doctolib.fr/hopital-public/vannes/centre-de-vaccination-covid-19-vannes-kercado qu'on récupère, et https://partners.doctolib.fr/hopital-public/vannes/ghba-centre-de-vaccination-covid-vannes qu'on ne récupère pas). [Par contre, il y a un autre centre avec le même PID qui remonte, donc ça n'a pas l'air d'être ça le point bloquant]

**Comment by grubounet** [comment]
Le centre n'est même pas accessible directement par la recherche doctolib en motif "Vaccination covid-19", donc je pense que le soucis est coté doctolib ... mauvaise catégorie de centre par exemple ?

**Comment by Maijin** [comment]
Fixé ici https://github.com/CovidTrackerFr/vitemadose/pull/262
