### ISSUE TITLE
Stats créneaux disponibles par type de vaccin

### ISSUE THREAD

**Issue by rozierguillaume** [CovidTrackerFr/vitemadose#266]
Obtenir le nombre de créneaux ouverts par type de vaccin(Pfizer, Moderna, ARNm, Astra, Janssen, multiple,  non connu). Pourquoi pas historisé, mais pas urgent.

**Comment by mccob** [comment]
Vu les nouvelles conditions d'éligibilité (18-54 ans avec comorbidité qui sont éligibles mais pas en AZ), est-ce qu'il faut pas revoir la priorité de cette fonctionnalité et la rendre disponible dès le début de la recherche ou l'affichage des résultats ?
https://twitter.com/MCCob/status/1388469389536673794

merci

**Comment by ValentinMouret** [comment]
De ce que je comprends pour l’instant, ça ne me semble pas faisable, du moins pas entièrement.

Plusieurs centres rapportent de multiples vaccins, e.g. : 

```('Pharmacie Des Allees',
  [<Vaccine.ASTRAZENECA: 'AstraZeneca'>,
   <Vaccine.PFIZER: 'Pfizer-BioNTech'>,
   <Vaccine.MODERNA: 'Moderna'>,
   <Vaccine.JANSSEN: 'Janssen'>],
  36)`
```

Cette pharmacie rapporte 36 rendez-vous répartis (comment ?) sur 4 types de vaccins différents.

Ce que je peux faire dans un premier temps c’est produire la liste pour les cas où il n’y a pas de doute (un seul type de vaccin).
