### ISSUE TITLE
Centre Vaccination Toulouse manquant

### ISSUE THREAD

**Issue by Maijin** [CovidTrackerFr/vitemadose#269]
https://www.keldoc.com/cabinet-medical/toulouse-31000/vaccinodrome-toulouse/vaccinodrome-toulouse?motive=88503&category=3243&cabinet=18777&specialty=144&agenda=53155,53172,53160,53159,53171,53163,53168,53165,53157,53154,53174,53164,53173,53158,53161,53166,53167,53156,53162,53169,53170

**Comment by gaelbenoit** [comment]
J'ai fait quelques tests, leur site ne réagi pas de la même façon si on arrive avec www.keldoc.com ou vaccination-covid.keldoc.com.
Il faut bien que les adresses soient au format vaccination-covid.keldoc.com pour déclencher le redirect qui nous donne l'url avec les bons paramètres (https://vaccination-covid.keldoc.com/redirect/?dom=cabinet-medical&inst=toulouse-31000&user=vaccinodrome-toulouse). Si le ndd est en www.keldoc.com on n'obtient pas ce redirect donc le scraper s'arrête là

Je fais un fix et je vais aussi voir si on peut faire corriger la liste du côté d'atlasanté
