### ISSUE TITLE
[Doctolib] Présence de centres qui ne vaccinent pas dans les json.

### ISSUE THREAD

**Issue by grubounet** [CovidTrackerFr/vitemadose#271]
Exemple : dans le 44, ce centre https://partners.doctolib.fr/pharmacie/saint-etienne-de-montluc/pharmacie-thiercelin-jean-thiercelin-unipharm

Ne propose pas la vaccination covid, d'ailleurs dans https://www.doctolib.fr/booking/258630.json aucun des motifs ne correspond à la vaccination.

**Comment by Maijin** [comment]
Autre exemple https://partners.doctolib.fr/pharmacie/andelnans/pharmacie-des-pres uniquement des tests antigéniques

![Uploading image.png…]()

**Comment by Noezor** [comment]
Mhhh ... il faudrait virer les centres sans vaccination dans les motifs. Mais vu qu'on a déjà bien galéré à rajouter les bons noms pour les centres, ça va être funky pour cette tâche !

**Comment by Benvii** [comment]
Hello,
J'ai investigué un peu, après avoir ajouté les données extraite de motifs de rdv (pour l'instant non extraite au niveau centres) à l'output `data/output/doctolib-centers.json` (généré par le `make doctoscrap`).

Si on a l'approche évoqué dans ce ticket, c'est à dire `filtrer tous les centres n'ayant pas un motif de vaccination` on va en virer beaucoup (643 centres) notamment des centres qui n'ont aucun motifs mais proposent potentiellement ce service (je pense aux centres en réservation par tel uniquement) : 
```
Total number of centers 2811
  Centers with vaccination motives :  2168
  Centers without vaccination motives :  643
  Centers without any motives :  138
  Centers with motives but none of them is a vaccination motive :  505
Taking a look a the center with motives but no vaccination ones, did we miss something ?
  We have  353  different motives for those centers
  Ignored motives written in : /tmp/ignored_motives.csv
```

Il paraît plus judicieux d'avoir l'approche suivante `filter les centres ayant des motifs mais aucun correspondant à la vaccination COVID19`.

Avec cette approche on élimine 505 centres, mais je trouvais que c'était encore beaucoup encore, j'ai donc parcouru tout les motifs des centres ignorés par le filtre [is_appointment_relevant](https://github.com/CovidTrackerFr/vitemadose/blob/main/scraper/doctolib/doctolib_filters.py#L5) et je me suis rendu compte que ce filtre ignore des motifs qui sont selon moi valides, notamment les motifs suivants : 
- 2de injection vaccin COVID-19 (Moderna)
- Vaccin COVID-19 - AstraZeneca (55 ans et plus) --> Celui ci ne fait pas débat je pense
- 3ème injection MODERNA
- Injection unique vaccin COVID-19 (Janssen) --> Celui ci ne fait pas débat je pense
- 2nde injection vaccin COVID-19 (AstraZeneca)
- 2de injection vaccin COVID-19 (Pfizer-BioNTech)

J'imagine que dans notre cas il serait judicieux de ne pas ignorer les centres proposants des 2nd vaccinations ? en soit on doit les considérer comme centre de vaccination où pas (vu que nos utilisateur cherchent une première injection) ?

Mon implémentation ne prend pas en compte cette mise à jour de filtre, j'ai ouvert le ticket suivant #310 .

Je vous pousse un PR ce soir, j'ai lancé un scraping pour vérifier que tout est bon.

**Comment by gaelbenoit** [comment]
Effectivement pour les 2 motives 
- Vaccin COVID-19 - AstraZeneca (55 ans et plus)
- Injection unique vaccin COVID-19 (Janssen)

il n'y a pas de débat il faut les intégrer.

Pour les motives qui ne sont pas des premières injections, pour l'instant on a fait le choix de ne pas les intégrer car les utilisateurs cherchent principalement des premières injections et cliquer sur un lien pour finalement s'apercevoir que c'est une seconde injection risque d'apporter de la confusion là où l'on essaie justement de proposer un outil simple et efficace.

Cependant, avec l'avancement de la campagne vaccinale, nous allons avoir de plus en plus de visiteurs cherchant une seonde injection, car même si beaucoup de centre imposent de réserver le rendez-vous de la 2ème injection en même temps que celui de la première, ce n'est pas le cas de tous les points de vaccination, les pharmacies par exemple. 

Il faut donc 2 évolutions: 
- Savoir identifier les rangs d'injection lors des scrapes
- Pouvoir proposer d'effectuer un filtre (ou avoir un affichage de cette donnée) au niveau du front

**Comment by francoisBouchet** [comment]
question : on pose ce filtre d'injection dès le formulaire en homepage ? 

parce que j'ai fait un test créa de mettre un select filtrant sur la page résultats pour voir ce que ça pourrait donner... c'est sympa mais mon petit doigt me dit que 30% max des gens vont l'utiliser sur la page résultat...

<img width="1440" alt="injection-filter" src="https://user-images.githubusercontent.com/36815410/116917546-133b9d80-ac4f-11eb-8aa1-1310ae82b8a7.png">

**Comment by Benvii** [comment]
@gaelbenoit motifs intégrés sur #317 
On passe peut-être sur un autre ticket pour la partie identifier les rangs des injections ? j'ai pas trop regardé les autres scrapers j'imagine qu'il y a une première étude de faisabilité à faire

@francoisBouchet haha génial ce filtre surtout la dernière option ;)
