### ISSUE TITLE
[Doctolib] Centres dupliqués dont un affiché sans dose et l'autre avec doses

### ISSUE THREAD

**Issue by Maijin** [CovidTrackerFr/vitemadose#286]
Centres dupliqués dont un affiché sans dose et l'autre avec doses dans le doubs par exemple -  https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt25-doubs

<img width="985" alt="image" src="https://user-images.githubusercontent.com/1408600/116777126-00697300-aa6d-11eb-92cf-42b46586da67.png">

-> https://partners.doctolib.fr/centre-de-sante/baume-les-dames/centre-de-vaccination-petr-doubs-central

<img width="1017" alt="image" src="https://user-images.githubusercontent.com/1408600/116777137-17a86080-aa6d-11eb-9eab-5b17a94a62db.png">

-> https://partners.doctolib.fr/centre-de-sante/baume-les-dames/centre-de-vaccination-petr-doubs-central?pid=practice-174787

**Comment by grubounet** [comment]
Bug inhérent à doctolib : 
![image](https://user-images.githubusercontent.com/31167642/116892278-f3e14800-ac2f-11eb-8aa6-47bf1bdd0bc6.png)

Même en sélectionnant le centre de Rougemont, on retombe sur Baume Les Dames.

Tentative d'explication : Les centre l'ile le doubs et rougemont semblent être éphémère donc ils ont du être configurés pour renvoyer sur l'autre centre ?
![image](https://user-images.githubusercontent.com/31167642/116892351-0b203580-ac30-11eb-91d7-aabe0e68ce28.png)
