### ISSUE TITLE
Have a unique / non null id for a Center

### ISSUE THREAD

**Issue by michgauz** [CovidTrackerFr/vitemadose#287]
We have implemented the notifications on native apps.
Today we are blocked.

- We have tried to rely on "gid" field but this id is not unique
Dr Ariel Amar appears 2 times with same "gid", 2 different locations
https://vitemadose.gitlab.io/vitemadose/75.json

- We have tried to rely on "internal_id" but sometimes it is null
Pharmacie De La Trinité
https://vitemadose.gitlab.io/vitemadose/75.json

In addition, it would be great to remove special characters from theses ids ("[") or for this new id if you rely on theses characters

Thanks ;)

**Comment by Noezor** [comment]
I believe @grubounet is working on this :)
