### ISSUE TITLE
Pharmacie Gilles Buxerolles qui ne remonte pas

### ISSUE THREAD

**Issue by tdevlaeminck** [CovidTrackerFr/vitemadose#293]
La pharmacie Gilles à Buxerolles (86180) propose des rendez-vous de vaccination Astrazeneca & Janssen.
Prochaines disponibilités le 6 mai. 
Lien Maiia : https://www.maiia.com/pharmacie/86180-buxerolles/pharmacie-gilles

Pourtant cette pharmacie n'apparait pas sur VMD.
Lien VMD : https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt86-vienne/commune86041-86180-buxerolles/en-triant-par-distance<

**Comment by gaelbenoit** [comment]
Cela vient d'une mauvaise saisie des raisons de consultation, seule la dernière a le flag injectionType: "FIRST" mais son planning n'a pas de dispo. Les autres plannings ont des dispos mais pas le bon flag

![image](https://user-images.githubusercontent.com/11502741/116806528-e6439980-ab2d-11eb-9175-3a9da95e7de5.png)

![image](https://user-images.githubusercontent.com/11502741/116806637-bc3ea700-ab2e-11eb-81de-057736aac016.png)

**Comment by gaelbenoit** [comment]
J'ai contacté la pharmacienne, elle va corriger l'enregistrement de ses campagnes. Je surveille et j'update l'issue

**Comment by gaelbenoit** [comment]
La correction a été faite côté Maiia, mais j'ai découvert un bug lors de la récupération des centres Maiia qui empêche la mise à jour (#312) 
J'ai une correction en attente (#313)

![image](https://user-images.githubusercontent.com/11502741/116852921-7bf62c00-abf5-11eb-9924-6cf198106f74.png)

**Comment by gaelbenoit** [comment]
Fixed
![image](https://user-images.githubusercontent.com/11502741/116863560-c8963300-ac06-11eb-9488-22f327e754cc.png)
