### ISSUE TITLE
Retirer une pharmacie des résultats

### ISSUE THREAD

**Issue by tdevlaeminck** [CovidTrackerFr/vitemadose#296]
La pharmacie du Marché, 3 avenue du Général Leclerc 78340 LES CLAYES-SOUS-BOIS souhaite ne plus apparaitre sur le site VMD. 

![image](https://user-images.githubusercontent.com/82476476/116795016-09d8f680-aad2-11eb-9039-af6ada7c654c.png)

**Comment by gaelbenoit** [comment]
Bizarre elle est pourtant listée sur sante.fr
![image](https://user-images.githubusercontent.com/11502741/116806760-69192400-ab2f-11eb-8f47-41693a4b545c.png)

Et sur Doctolib
![image](https://user-images.githubusercontent.com/11502741/116806772-7afac700-ab2f-11eb-9036-bc65d905801b.png)

**Comment by Noezor** [comment]
c'est bien son droit de ne plus être affichée si elle se fait trop spam :)

Je vais faire une PR blacklist

**Comment by Maijin** [comment]
verifié c'est plus là!
