### ISSUE TITLE
Doctolib - Centres dupliqués

### ISSUE THREAD

**Issue by Maijin** [CovidTrackerFr/vitemadose#305]
https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt25-doubs

![image](https://user-images.githubusercontent.com/1408600/116821809-a60b0800-ab7b-11eb-8540-4b38b5b78b5a.png)

**Comment by grubounet** [comment]
Il est en double dans les json de doctolib, je vais regarder si on peut faire qqch

**Comment by Aymerik** [comment]
Même souci ici à priori : 
![image](https://user-images.githubusercontent.com/15689805/117419983-706c7300-af1d-11eb-9eb8-b886a14cddee.png)
https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt54-meurthe_et_moselle

Il s'agit du même centre, mais qui est dupliqué (mal configuré ?) sur Doctolib donc pas sûr qu'on puisse y faire grand-chose : 
 [Centre 1](https://partners.doctolib.fr/centre-de-vaccinations-internationales/nancy/centre-de-vaccination-covid-19-nancy?pid=practice-165715) - [Centre 2](https://partners.doctolib.fr/centre-de-vaccinations-internationales/nancy/centre-de-vaccination-covid-19-nancy?pid=practice-178399)

**Comment by aureliancnx** [comment]
Il faut contacter le centre directement ou l'ajouter à une blocklist.
