### ISSUE TITLE
Keldoc - centres manquants

### ISSUE THREAD

**Issue by Miloud-H** [CovidTrackerFr/vitemadose#308]
Bonjour,

Il semblerait que le centre de vaccination AlpeExpo de Grenoble ne remonte pas, il était pourtant bien listé il y a quelques jours.

Le lien keldoc : https://www.keldoc.com/cabinet-medical/grenoble-38000/vaccinodrome-grenoble?cabinet=18795&specialty=144

**Comment by Maijin** [comment]
Oui la plateforme keldoc est pour le moment desactivé pour des contraintes de performances côté Keldoc, on fait notre possible pour le remettre dès que c'est possible!

**Comment by chabrulat** [comment]
Bonjour,

Il serait bien d'ajouter une note pour signaler le problème et d'ajouter un lien vers le site https://www.sante.fr/ en pointant sur le département correspondant, par exemple https://www.sante.fr/cf/centres-vaccination-covid/departement-89-yonne.html

Il serait bien aussi de modifier le titre de ce message en un titre plus général, ça éviterait les doublons.

Cordialement,

**Comment by Maijin** [comment]
@chabrulat 
Pour le titre du message c'est fait!

L'alerte / note - c'est en cours côté front-end.

La solution est étudiée. Cette implementation n'est pas idéal car elle melangerait les centres dits "sans methode de prise de rendez-vous connu" et les centres Keldoc non fonctionnels ce qui n'est pas ideal car la plupart des utilisateurs ne verifient pas la liste des centres dits "Indisponibles".

**Comment by chabrulat** [comment]
Merci,

**Comment by Maijin** [comment]
Nous avons deja tout les centres affichés par Santé.fr dans notre base de donnée (et beaucoup plus), mais l'affichage de ces centres dans la liste des centres indisponibles risque de noyer l'utilisateur plus que d'être utile.

**Comment by chabrulat** [comment]
L'idée n'est pas d'ajouter des centres dans votre liste mais de mettre un lien vers https://www.sante.fr/ pour que les personnes qui veulent vérifier la disponibilité dans les centres gérés par KelDoc puissent le faire.

**Comment by Maijin** [comment]
Nous avons deja l'integralité des centres santé.fr renvoyer sur santé.fr n'a pas d'interet particulier. Ce qui est proposé est d'integrer qqchose de ce style pour keldoc, temporairement. Le mieux etant evidemment de fixer le rapport du nombre de dose.

<img width="970" alt="image" src="https://user-images.githubusercontent.com/1408600/116867575-c1beee80-ac0d-11eb-94af-260e4a181ed9.png">
