### ISSUE TITLE
[Doctolib] Ajouter des motifs de vaccination

### ISSUE THREAD

**Issue by Benvii** [CovidTrackerFr/vitemadose#310]
Hello,
Après une analyse exhaustive des centres dont les motifs sont considérés comme non vaccinant COVID19 dans le cadre d'une investigation pour le #271 .

J'ai repassé en revu 350 motifs ici : https://docs.google.com/spreadsheets/d/1Z7deht-Bi8i3o7iDbpruSB2HJSXy49S8OnHtMnoeq20/edit#gid=1504249045&fvid=1168460918 

Je n'ai pas l'historique du projet, je pense qu'il a été décidé d'ignorer les modifs de 2nd / 3èmes injections.
En revanche je note les motifs suivants : 
- Vaccin COVID-19 - AstraZeneca (55 ans et plus)
- Injection unique vaccin COVID-19 (Janssen)

Que ne passent pas le filtre [is_appointment_relevant](https://github.com/CovidTrackerFr/vitemadose/blob/main/scraper/doctolib/doctolib_filters.py#L5).

Pouvez-vous me confirmer qu'on peux les ajouter ? je peux faire la PR dans ce cas.

**Comment by Maijin** [comment]
Oui go!

**Comment by Noezor** [comment]
Trop cool la liste ! Ça fait 1 semaine que c'était dans ma todo et uqe je faisais que le procrastiner.
