### ISSUE TITLE
[KelDoc] Problème de remontée KelDoc

### ISSUE THREAD

**Issue by chabrulat** [CovidTrackerFr/vitemadose#314]
Bonjour,

Les centres utilisant la plateforme KelDoc ne sont plus remontés dans ViteMaDose (précédemment signalé ici : https://github.com/rozierguillaume/covidtracker-tools/issues/270).

Cordialement,

**Comment by Maijin** [comment]
Merci pour le retour @chabrulat 

Oui la plateforme keldoc est pour le moment desactivé pour des contraintes de performances côté Keldoc, on fait notre possible pour le remettre dès que c'est possible!

Duplicate of #308
