### ISSUE TITLE
Doublon de centre observé dans le 35

### ISSUE THREAD

**Issue by lc-dx** [CovidTrackerFr/vitemadose#324]
Bonjour les gars, j'ai repéré ce doublon sur un centre en Ille-et-Vilaine (sur iOS et sur desktop également) 
Vu que c'est un gros centre du coin ça fausse pas mal les stats du département en plus je pense.
Bon courage pour démêler tout ça 
![IMG_A00F60A08426-1](https://user-images.githubusercontent.com/82411720/117027111-ac74bd80-acfc-11eb-8bb2-d207b5f505a8.jpeg)
PS : j'espère que j'ai mis ça au bon endroit :-P

**Comment by grubounet** [comment]
Hello hello, tu es au bon endroit !

Voici l'origine du soucis : 
![image](https://user-images.githubusercontent.com/31167642/117033135-63c00300-ad02-11eb-8aed-de3df55909c8.png)

Le centre est configuré comme si il existait 2 centres, un pour pfizer/moderna et un pour astrazeneca (2 practice id). Ca fout un bordel pas possible, il faut contacter le centre pour leur expliquer que leur doctolib est mal configuré

**Comment by chabrulat** [comment]
Bonjour,

Dans le même genre mais sous un autre angle, le centre d'Auxerre apparaît sous deux noms :

![Capture](https://user-images.githubusercontent.com/77581665/117299441-da7f0c80-ae78-11eb-8029-3e97e584a10e.PNG)

Cordialement,

**Comment by grubounet** [comment]
@chabrulat bonjour, le soucis vient de doctolib !
Le centre existe sous deux noms et deux liens, à la même adresse :/
https://www.doctolib.fr/centre-de-vaccinations-internationales/auxerre/centre-vaccinal-de-l-auxerrois
https://www.doctolib.fr/hopital-public/auxerre/centre-hospitalier-d-auxerre

**Comment by lc-dx** [comment]
Bonjour @grubounet,

Je reviens sur le bug avant de les contacter avec deux trois infos fraiches :

- le centre a ouvert le 1er mai pour faire de l'AZ exceptionnellement : https://www.bretagne.ars.sante.fr/rennes-le-centre-de-vaccination-robert-poirier-sera-ouvert-ce-samedi-1er-mai
- quand on va sur Doctolib il n'y plus qu'un centre 
![Capture d’écran 2021-05-06 à 18 14 23](https://user-images.githubusercontent.com/82411720/117332026-a404ba00-ae97-11eb-8c10-0358428bceb0.png)

La balle semble être dans notre camp. J'imagine que l'AZ ce week-end a généré un deuxième centre et maintenant qu'il l'ont fermer le scraper alimente les deux en Pf et Moderna ?

Je vous laisse regarder ça,  j'en suis étant totalement incapable :-P

A plus,

**Comment by lc-dx** [comment]
@grubounet le doublon a bien disparu. L'affaire peut être close.
