### ISSUE TITLE
Type de Vaccin manquant

### ISSUE THREAD

**Issue by Maijin** [CovidTrackerFr/vitemadose#328]
https://vaccination-covid.keldoc.com/redirect/?dom=cabinet-medical&inst=st-brice-sous-foret-95350&user=vaccination-plaine-vallee-saint-brice-sous-foret&category=-1&cabinet=16609&specialty=496

![image](https://user-images.githubusercontent.com/1408600/117050016-29139600-ad15-11eb-86c8-c3c5ff384a83.png)

VMD N'affiche rien alors que les 3 types de Vaccins sont disponibles:

<img width="998" alt="image" src="https://user-images.githubusercontent.com/1408600/117050037-303aa400-ad15-11eb-8c29-8f7407aeb86b.png">

**Comment by gaelbenoit** [comment]
![image](https://user-images.githubusercontent.com/11502741/117059663-56197600-ad20-11eb-9924-98349ff64209.png)
