### ISSUE TITLE
Centre Doctolib non présent dans le 10

### ISSUE THREAD

**Issue by rozierguillaume** [CovidTrackerFr/vitemadose#330]
Message reçu : "Bonjour! 
Tout d’abord merci pour ce que vous faites. 
Juste une petite remarque, sur VMD pas de dispo au vaccinodrome de troyes rue des gayettes depuis plusieurs jours, or sur doctolib il y en a. 
J’ignore s’il s’agit d’un bub mais à lechelle du departement de l’aube cela peut etre genant, ce centre vaccine 80% des aubois. 
Bien à vous"

**Comment by rozierguillaume** [comment]
![image](https://user-images.githubusercontent.com/22763678/117063505-389adb00-ad25-11eb-9d51-9752674b4ded.jpeg)

**Comment by Maijin** [comment]
Il y en a pour la 2nd injection, pas pour la 1ere injection cf.

<img width="399" alt="image" src="https://user-images.githubusercontent.com/1408600/117063850-b1019c00-ad25-11eb-800a-de2add9b21d2.png">

**Comment by rozierguillaume** [comment]
Merci !
