### ISSUE TITLE
Médecin généralisation qui ne remonte pas - 83170 Brignoles

### ISSUE THREAD

**Issue by tdevlaeminck** [CovidTrackerFr/vitemadose#333]
Bonjour, 

Un généraliste nous signale qu'il a des rendez-vous dispo sur Doctolib mais qu'il n'est pas référencé sur VMD. 
Lien doctolib : https://www.doctolib.fr/medecin-generaliste/brignoles/antoine-alexis

Thanks,

**Comment by Maijin** [comment]
<img width="374" alt="image" src="https://user-images.githubusercontent.com/1408600/117107531-04a1d300-ad82-11eb-9d06-b667f1f6bf5f.png">

Ce generaliste n'a pas de 1ere dose disponible
