### ISSUE TITLE
[Doctolib] Janssen ne remonte pas

### ISSUE THREAD

**Issue by gaelbenoit** [CovidTrackerFr/vitemadose#334]
https://partners.doctolib.fr/centre-de-sante/paris/centre-medical-europe

![image](https://user-images.githubusercontent.com/11502741/117105438-4e88ba00-ad7e-11eb-855e-123a55a938a6.png)

**Comment by gaelbenoit** [comment]
![image](https://user-images.githubusercontent.com/11502741/117106807-cce65b80-ad80-11eb-82e6-fc39b8cb549c.png)

![image](https://user-images.githubusercontent.com/11502741/117106706-9d375380-ad80-11eb-806b-9c189286f8f5.png)

**Comment by Maijin** [comment]
Mon fix passe pas donc ça doit être autre chose. A creuser.

**Comment by Noezor** [comment]
![image](https://user-images.githubusercontent.com/8218350/117200979-6860e600-adec-11eb-9bcb-fd415310a5a7.png)
`first_shot_motive` à `false`. Il faudrait virer ce check pour du Janseen

**Comment by Maijin** [comment]
bien vu @Noezor tu veux te lancer?
