### ISSUE TITLE
Remove tracking parameters

### ISSUE THREAD

**Issue by DavidLibeau** [CovidTrackerFr/vitemadose#34]
The Doctolib urls contains a `speciality_id` attribute. 

https://github.com/CovidTrackerFr/vitemadose/blob/238de43cef7f5f9326df20b9cf55636fa8970a49/scraper/doctolib.py#L59

It should be clarified why this attribute is present and removed if it is useless or for tracking purposes.

**Comment by Bouska** [comment]
Ce n'est pas un tracker. Le `speciality_id 5494` correspond à (cf. les données du JSON https://partners.doctolib.fr/booking/centre-de-vaccination-tarbes-ayguerote.json) "Vaccination COVID-19". Dans ce cas particulier qu'est un centre de vaccination COVID-19, c'est la seule procédure qu'ils font donc je suppose que le frontend de Doctolib ne propose pas de choix s'il n'y a qu'un seul choix possible. Mais pour les lieux de vaccinations qui ne sont pas exclusivement centre de vaccination COVID-19, c'est utile en revanche.

**Comment by florimondmanca** [comment]
@DavidLibeau Hello,

En effet le `speciality_id` est une donnée qu'on a visiblement besoin de garder, ça n'est visiblement pas lié à du tracking. Dans tous les cas les utilisateurs de VideMaDose sont protégés, car c'est notre scraper (via GitHub Actions) qui fait tous ces appels (le frontend ne fait que "consommer" les résultats du traitement).

✌️

**Comment by DavidLibeau** [comment]
J'ai pas tout compris mais si vous êtes sûr que c'est pas un tracker alors c'est parfait.
