### ISSUE TITLE
Lien erronée fourni par Doctolib et donc erronée dans VMD pour le centre d'Orgelet (39270)

### ISSUE THREAD

**Issue by baptistepl** [CovidTrackerFr/vitemadose#342]
Pour le centre de vaccination d'Orgelet (39270), le lien redirigé par Doctolib est erronée et donc de ce fait il est erronée dans VMD. Il renvoie vers un autre centre - celui de Lons-Le-Saunier (39000) - . Serait-il possible de le corriger manuellement dans VMD ?
Voici le lien correct si ça peut vous aider : https://partners.doctolib.fr/centre-de-sante/dole/ars-de-bourgogne-franche-comte?speciality_id=5494&pid=practice-165027

**Comment by gaelbenoit** [comment]
c'est toujours le même problème que #239, il faudrait regarder du côté de la récupératin des centres pourquoi le practice n'est pas remonté pour ce centre

**Comment by tlevillayer** [comment]
Etrange en effet que le nom remonte mais pas le pid

**Comment by Noezor** [comment]
On pourrait les rajouter à la main avec #435

**Comment by grubounet** [comment]
@baptistepl en fait, il n'y a pas d'erreur, ou plus d'erreur en tout cas !

![image](https://user-images.githubusercontent.com/31167642/118829823-be3e8f00-b8be-11eb-9697-2830de72bf99.png)

Il y a bien un bug coté doctolib puisque dans le rectangle violet le nom du centre est pas le bon, mais à droite on voit bien que le centre est bien celui d'orgelet :)

**Comment by grubounet** [comment]
@Maijin tu peux close ?
