### ISSUE TITLE
Remonter le code postal dans le endpoint info_centres

### ISSUE THREAD

**Issue by poudro** [CovidTrackerFr/vitemadose#344]
Le endpoint `https://vitemadose.gitlab.io/vitemadose/info_centres.json` contient toutes les infos de centres remontes mais l'adresse n'est disponible que en version "formattee".

Serait-il possible de remonter les differentes parties de l'adresse en version "splitee" aussi (en particulier le code postal) ? 

Merci

**Comment by grubounet** [comment]
Bonjour, 
Je pense que cela va dépendre des plateformes, pour certaines on récupère l'adresse complete en un seul champ de mémoire !

**Comment by poudro** [comment]
Hello @grubounet !

Merci pour la reponse.

Pour le moment j'utilise `api-adresse.data.gouv.fr` pour les parser de mon cote, mais je me disais que ca pourrait etre interessant de le faire directement une fois pour toute au niveau de la source.

Si ca vous interesse je peux regarder un peu au niveau du code pour voir si je peux me debrouiller moi-meme pour l'integrer.

**Comment by Noezor** [comment]
C'est fait ! Merci @mathilde-leval pour la PR :1st_place_medal:
