### ISSUE TITLE
[KelDoc] Centre de Sens (89)

### ISSUE THREAD

**Issue by chabrulat** [CovidTrackerFr/vitemadose#345]
Bonjour,

Le lien proposé sur ViteMaDose (https://vaccination-covid.keldoc.com/redirect/?dom=infectiologue&inst=sens-89100&user=vaccination-covid-19-2&agenda=51183&motive=81385&category=-1&cabinet=16565) ne propose pas de première injection.

Il y a des premières doses disponibles en passant par ce lien : https://www.keldoc.com/centre-hospitalier/sens-89100/centre-hospitalier-de-sens?category=-1&cabinet=16565&specialty=153

Cordialement,

**Comment by Noezor** [comment]
Fixé une fois que #435 est bon

**Comment by gaelbenoit** [comment]
Pour info, pour Keldoc quand on a un souci avec une url on peut leur demander de faire corriger ça au niveau de l'ARS qui l'a saisi. En l'occurence pour le centre de Sens j'ai vérifié l'url est maintenant correcte dans le csv data gouv

**Comment by chabrulat** [comment]
Merci, le centre apparaît bien dans les lieux de vaccination avec disponibilités.

Bonne journée,
