### ISSUE TITLE
Pouvoir filtrer par type de vaccin avant/après recherche 

### ISSUE THREAD

**Issue by pantshee** [CovidTrackerFr/vitemadose#346]
Bonjour,
Certaines personnes souhaitent éviter certains vaccins (par peur ou par contre indication médicale).
Il serait utile de pouvoir ajouter avant ou après la recherche par ville, des cases à cocher (ou autre) avec les différents vaccins, afin d'affiner la recherche de doses.

Pour certains centres qui proposent plusieurs types de vaccins la complexité est un peu plus grande j'imagine, mais ce serait pertinent d'ajouter ce filtre au moins pour exclure de la recherche les centres de vaccination qui proposent 1 seul vaccin qu'on ne recherche pas

**Comment by Maijin** [comment]
Hello @pantshee et merci pour la suggestion,

L'ajout de cette fonctionnalité est travaillé du côté frontend et est en cours d'implementation - voir ici https://github.com/CovidTrackerFr/vitemadose-front/issues/147.

Je ferme cette issue du côté backend.
