### ISSUE TITLE
 [Doctolib] Partners URL vers Normal URL

### ISSUE THREAD

**Issue by Maijin** [CovidTrackerFr/vitemadose#348]
Nous avons une demande urgente de changer les URLs de Doctolib dites "partners" par exemple https://partners.doctolib.fr/centre-de-sante/vesoul/centre-de-vaccination-covid-19-de-vesoul?speciality_id=5494&enable_cookies_consent=1

Vers les URL de ce type - "https://www.doctolib.fr/" par exemple pour ce centre^^^:

https://doctolib.fr/centre-de-sante/vesoul/centre-de-vaccination-covid-19-de-vesoul?speciality_id=5494&enable_cookies_consent=1

Pour résumer Doctolib nous demande de remplacer https://partners. par https://.

**Comment by tlevillayer** [comment]
Si personne dessus, je prends

**Comment by Maijin** [comment]
Voir follow-up issue #372
