### ISSUE TITLE
Créneaux Doctolib de Troyes ne remontent pas

### ISSUE THREAD

**Issue by fcamblor** [CovidTrackerFr/vitemadose#355]
Le centre "Centre de vaccination de la Métropole Troyenne (CUBE parc des expos), 20 rue des Gayettes" (10000 - Troyes) a des créneaux Pfizer sur Doctolib : https://partners.doctolib.fr/centre-de-sante/troyes/centre-de-vaccination-covid-troyes-champagne-metropole-ex-lidl 

Mais ils ne remontent pas sur VMD
<img width="1304" alt="Vaccination_COVID-19_à_Troyes_10000" src="https://user-images.githubusercontent.com/603815/117469649-43888200-af56-11eb-87ee-9401f91da6c1.png">

**Comment by varsq** [comment]
Dans le JSON https://partners.doctolib.fr/booking/centre-de-vaccination-covid-troyes-champagne-metropole-ex-lidl.json

Il y a 3 `places`, le script va récupérer que la première et donc ne pas trouver les disponibilités.
`practice_id = rdata.get("places")[0].get("practice_ids", None)`

En testant rapidement de récupérer le practice_id de chaque place, je récupère bien une disponibilité.

`2021-05-09 13:42:50,947 | [INFO] first availability : 2021-05-13T12:18:00.000+02:00`

Je connais pas très bien le projet, donc est-ce qu'il y a une raison de récuperer seulement la première `place` ?

**Comment by KanorUbu** [comment]
Il y a un doublon avec https://github.com/CovidTrackerFr/vitemadose/issues/388
Et @varsq je suis arrivé aussi à la même hypothèse

**Comment by KanorUbu** [comment]
Bonjour 
Je pense qu'on peut fermer cette issue ça semble fonctionner maintenant 
et clôturer aussi https://github.com/CovidTrackerFr/vitemadose/issues/388
