### ISSUE TITLE
[proposition d'évolution] ajuster la granularité de certaines statistiques

### ISSUE THREAD

**Issue by max5962** [CovidTrackerFr/vitemadose#365]
Bonjour,
En parcours la page statistiques, d'ailleurs faute de frappe :
![Screenshot_20210508-203141](https://user-images.githubusercontent.com/34659571/117549759-773dd780-b03c-11eb-97ee-9746b79ee22f.png)

Je me dit que le "prochaines heures ou prochains jours" peut être plus granulaire. C'est pas beaucoup plus lourds a calculer, beaucoup plus lourds a stocker et permettrait de voir pas mal de chose.

Genre une dropdown au niveau du front (ticket à ouvrir côté front si c'est accepté), avec ces valeurs :
- 24 prochaines heures
- 2 prochains jours
-7 prochains jours
-30 prochains jours.

Cette granularité permettrait de suivre la "perte de dose" puisque le nombre de créneaux restant à 24h doivent rester le plus faible.

Qu'en pensez-vous ?

**Comment by max5962** [comment]
Arf semble doublons à https://github.com/CovidTrackerFr/vitemadose/issues/292

Vous confirmez ?

**Comment by Noezor** [comment]
#292 est surtout pour[ ChronoDose](https://www.lci.fr/sante/chronodose-le-nouvel-outil-de-guillaume-rozier-fondateur-de-covid-tracker-et-vite-ma-dose-pour-trouver-des-creneaux-de-vaccination-le-lendemain-2185470.html) sur lequel on est en train de travailler. Je pense que ça mérite de garder l'issue ouverte pour centraliser les discussions.

**Comment by grubounet** [comment]
Du coup vu qu'on a ajouté les 1_days, 2_days, 7_days, 28_days et 49_days c'est bon non ? Je peux close @Noezor ?

**Comment by grubounet** [comment]
@max5962 tu peux créer un ticket côté front ? Vu qu'on fournit dorénavant tout ce qu'il faut :)

**Comment by max5962** [comment]
yes of course :)

**Comment by fcamblor** [comment]
Il me semble que l'idée était que tous les `appointment_schedules` vont dégager (très) prochainement

C'était utile pour les chronodoses, mais vu qu'elles ont disparues, l'idée était plutôt de supprimer cette section du JSON (pour l'alléger, en prévision des statistiques par jour des créneaux préconisés dans #519)

@max5962 avec #519, on devrait pouvoir "recalculer" cette stat car on aura des données encore plus granulaires, par centre.

**Comment by grubounet** [comment]
Hello, perso je suis pour laisser les appointment schedules, en virant "chronodose" et en modifiant éventuellement les jours
