### ISSUE TITLE
Split le scrapper par plateforme

### ISSUE THREAD

**Issue by Noezor** [CovidTrackerFr/vitemadose#368]
On a encore beaucoup (10+ par jours) de fails du scrapper car une plateforme est lente et fait tout timeout. En pratique, l'update de tous les résultats devrait être indépendant du fait qu'une des plateformes fail.

Voilà ce que je propose :
Avoir chacun des providers scrappés individuellement et générer 1 fichier (temporaire) par provider, dans un job par provider
Merger tout ces fichiers intermédiaires en 1 et les publier.

Utiliser plusieurs fichiers plutôt qu'un évite de se pauser trop de soucis sur la concurrence.

**Comment by aureliancnx** [comment]
Il faudrait que l'on puisse avoir plusieurs règles dans le makefile pour scrape chaque plateforme.

le fichier serait sauvegardé dans le dossier data/output avec un pattern.

Le publisher mergerait tous les centres dans les fichiers des plateformes et générerait les fichiers des départements et pousserait ça sur gitlab (ce publisher serait très rapide à l'exécution)

**Comment by Olivier4477** [comment]
J'en ai déjà parlé sur Mattermost mais autant faire un commentaire également ici:

Ce soir j'ai constaté une chose; 

Par moment, des plateformes partent en timeout est le cycle de scrapper en cours atteignent le timeout, qui est à 7 minutes.
Par contre les cycles des scrappers sont réglé à 5 minutes. 
Donc par moment, et je l'ai vue (désolé j'aurai du faire un screen), le scrap A  reçoit des timeout de plateforme, le scrap B se lance, alors que le A est en cours d'exécution à 5 minutes.

Donc part moment, vous avez 2 scrapper qui tourne et qui interroge les plateformes, pendant 2 minutes. Donc pendant 2 minutes, vous avez potentiellement des requêtes en double et qui n'aide pas les plateformes.
De +, le scrap A va attérir en timeout et vous jetez les résultats de son scrapping.

Je suggère, après je ne connais pas le code des scrappers, de démarer le scrap quand celui d'avant  soit terminé / soit arrivé en timeout -> Donc je propose de diminuer le temps de timeout( de 7m à 6 m voir 5m30 ou 5m).

Sauf erreur le temps moyen est entre 2m50 et 3m10.

Je n'ai pas voulu le modifier sur .gitlab-ci car je pense que d'autres ont + d'expérience que moi sur le projet pour valider ou non mon hypothèse.

**Comment by Olivier4477** [comment]
voici une capture: 

![vmd](https://user-images.githubusercontent.com/68284897/117940418-56f66d00-b309-11eb-9284-67f454003a34.JPG)

**Comment by aureliancnx** [comment]
> J'en ai déjà parlé sur Mattermost mais autant faire un commentaire également ici:
> 
> Ce soir j'ai constaté une chose;
> 
> Par moment, des plateformes partent en timeout est le cycle de scrapper en cours atteignent le timeout, qui est à 7 minutes.
> Par contre les cycles des scrappers sont réglé à 5 minutes.
> Donc par moment, et je l'ai vue (désolé j'aurai du faire un screen), le scrap A reçoit des timeout de plateforme, le scrap B se lance, alors que le A est en cours d'exécution à 5 minutes.
> 
> Donc part moment, vous avez 2 scrapper qui tourne et qui interroge les plateformes, pendant 2 minutes. Donc pendant 2 minutes, vous avez potentiellement des requêtes en double et qui n'aide pas les plateformes.
> De +, le scrap A va attérir en timeout et vous jetez les résultats de son scrapping.
> 
> Je suggère, après je ne connais pas le code des scrappers, de démarer le scrap quand celui d'avant soit terminé / soit arrivé en timeout -> Donc je propose de diminuer le temps de timeout( de 7m à 6 m voir 5m30 ou 5m).
> 
> Sauf erreur le temps moyen est entre 2m50 et 3m10.
> 
> Je n'ai pas voulu le modifier sur .gitlab-ci car je pense que d'autres ont + d'expérience que moi sur le projet pour valider ou non mon hypothèse.

Ce n'est pas fondamentalement le plus gros du problème. Ce n'est que 2 minutes d'écart (et encore, il faut une trentaine de secondes pour lancer un autre scrap, donc on va dire 1 min 30). Le problème du timeout arrive rarement et n'est là que pour une plateforme pour le moment, qui ne subit pas cela toute la journée, mais sur des très courtes périodes -> de plus on a rajouté un killswitch.

Il vaut mieux pouvoir lancer un second scraper en parallèle plutôt que de bloquer la queue

Pour revenir à l'issue de @Noezor, tout est prêt de mon côté pour pouvoir passer à un split de scraper par plateforme, mais il semblerait que l'on ne soit pas tous d'accord sur cette implémentation. Cependant, je préfère pouvoir run 4 scrapers (un pour la plateforme A, B, C, D) en parallèle plutôt qu'à la chaîne, ça permettrait de moduler le temps entre chaque scrape (par exemple, sur certaines plateformes, on fait peu de requêtes au final et on pourrait lancer le scraper plus souvent que d'autres plateformes, ce qui permettrait de merge petit à petit toutes les données et d'avoir des données encore + fraîches avec les Chronodoses. Ceci dit, il faut que l'on continue à optimiser là où on peut les requêtes, pour rendre encore plus rapide le scraper (l'ajout de fonctionnalités niveau back étant + secondaire je pense pour le moment) et le temps entre chaque exécution.

**Comment by grubounet** [comment]
@Noezor la nouvelle config avec le enable/disable pour chaque plateforme en cas de soucis et le circuit breaker me semblent avoir remplacé l'idée de base non ? 

Je peux close ?

**Comment by Noezor** [comment]
Yes, en pratique on pourrait encore optimiser la parallelisation un peu, mais ce split de jobs n'est plus aussi utile qu'avant, et ne justifie plus du tout l'effort.
