### ISSUE TITLE
Pas d'infos centres sur les collectivités d'outremer

### ISSUE THREAD

**Issue by fcamblor** [CovidTrackerFr/vitemadose#384]
Hello les amis ! ✋ 

On vient de s'apercevoir qu'on avait un petit trou dans la raquette : il existe 4 communes en France pour lesquelles on ne dispose d'aucune statistique de centres .... car elles n'appartiennent à aucun département, puisque faisant partie de **collectivités** d'outremer (j'ai appris un truc :-) )

![image](https://user-images.githubusercontent.com/603815/117668204-01ee1600-b1a6-11eb-8fb5-0cfc4307e26d.png)

Je sais pas si vous avez moyen de scrapper des infos de centres pour ces 4 communes et les mettre dans un fichier json séparé (par exemple un `om.json` .. om pas comme Olympique de Marseille mais comme OutreMer) mais si vous y arrivez ce serait top :-)

**Comment by fcamblor** [comment]
Je link https://github.com/CovidTrackerFr/vitemadose-front/issues/182 dans laquelle on parle de ce problème coté front :-)

**Comment by Bouska** [comment]
En partie lié à #307

**Comment by Maijin** [comment]
Je ferme l'autre:

"Par exemple https://www.doctolib.fr/centre-de-vaccinations-internationales/saint-pierre-et-miquelon/centre-de-vaccination-covid-19-st-pierre-miquelon (telephone seulement)"

**Comment by fcamblor** [comment]
@Maijin du coup ça a été MEP sur le back ?

Car je vois bien un https://vitemadose.gitlab.io/vitemadose/om.json mais il est vide actuellement :')
(et est-ce qu'il ne faudrait pas que cela apparaisse dans https://vitemadose.gitlab.io/vitemadose/departements.json)

**Comment by fcamblor** [comment]
Pour info, j'ai une PR coté front qui rajoute le support pour les 4 communes.

Par contre : 
- j'ai dû hardcoder le département `om` (car il n'existe pas dans le `departements.json`)
- il n'y a aucun centre dans le `om.json`, ce qui me semble bizarre (non ?)
