### ISSUE TITLE
Centre de Bitche qui affiche 0 créneau

### ISSUE THREAD

**Issue by tdevlaeminck** [CovidTrackerFr/vitemadose#387]
Bonjour, 

Le centre de vaccination Covid-19 du CH de Sarreguemines à Bitche affiche 0 créneau alors qu'il y en a dès le 20 mai sur Doctolib. 

Vue VMD : 
![image](https://user-images.githubusercontent.com/82476476/117698912-864f9180-b1c4-11eb-8e79-ab6196ae749d.png)

Vue Doctolib :
![image](https://user-images.githubusercontent.com/82476476/117698950-8f406300-b1c4-11eb-9914-fa2a1929f027.png)

Thanks :)

**Comment by aureliancnx** [comment]
Problème de configuration provenant du centre en question. On ne peut pas y faire grand chose à ce niveau là...

**Comment by grubounet** [comment]
Le centre a carrément disparu de VMD ?

**Comment by grubounet** [comment]
Le centre a disparu, il faudra l'ajouter à la main.

@tdevlaeminck tu peux modifier l'issue ?

**Comment by tdevlaeminck** [comment]
Je vois à nouveau le centre. 
Et VMD affiche bien 0 créneau comme sur Doctolib donc le comportement semble normal. 

![image](https://user-images.githubusercontent.com/82476476/119441617-b6e80d00-bd26-11eb-92c9-0b0a86ff7fb5.png)

Je clos l'issue. 
J'en ouvrirai une nouvelle si un nouveau problème se présente pour ce centre.
