### ISSUE TITLE
Centre de Troyes qui affiche 0 créneau

### ISSUE THREAD

**Issue by tdevlaeminck** [CovidTrackerFr/vitemadose#388]
Bonjour, 

Le centre de vaccination COVID – **Troyes Champagne Métropole (10000 Troyes)** affiche 0 créneau alors qu'il y a des dispos dès le 12 mai sur Doctolib. 

![image](https://user-images.githubusercontent.com/82476476/117700361-31ad1600-b1c6-11eb-904b-6b6c7467146f.png)

Merci 🙂

**Comment by KanorUbu** [comment]
Bonjour 
Après avoir exploré un peu le code il semble que si on remplace l'url 
https://www.doctolib.fr/centre-de-sante/troyes/centre-de-vaccination-covid-troyes-champagne-metropole-ex-lidl
par 
https://www.doctolib.fr/centre-de-sante/troyes/centre-de-vaccination-covid-troyes-champagne-metropole-ex-lidl?pid=pratice-175998
dans https://raw.githubusercontent.com/CovidTrackerFr/vitemadose/data-auto/data/output/doctolib-centers.json
ça semble fonctionner 
Après je ne sais pas comment est géré la mise à jour du fichier json ?

**Comment by Noezor** [comment]
Sera fix avec #435 ?

**Comment by grubounet** [comment]
Je suis pas pour l'ajout à la main, je pense qu'il faut revoir la logique du scraper concernant la gestion des PID pour ce type de cas, vu qu'il est bien présent dans le vaccination-covid-19/dep.json sur l'api docto

**Comment by chabrulat** [comment]
Le centre de Troyes est maintenant OK :

![Capture](https://user-images.githubusercontent.com/77581665/118811830-c04c2200-b8ad-11eb-909a-827aa54c2648.PNG)

Bon après-midi,

**Comment by grubounet** [comment]
@Maijin tu peux close ?
