### ISSUE TITLE
Liens Doctolib : re-migrer vers Doctolib.fr

### ISSUE THREAD

**Issue by rozierguillaume** [CovidTrackerFr/vitemadose#390]
Désolé @aureliancnx pour le travail inutile… il va falloir re-migrer l’ensemble des liens partners.Doctolib.fr vers des liens Doctolib.fr, sans restriction (pour tout, y compris les centres) :(

**Comment by tlevillayer** [comment]
Ok, je refais ça.

**Comment by aureliancnx** [comment]
> Désolé @aureliancnx pour le travail inutile… il va falloir re-migrer l’ensemble des liens partners.Doctolib.fr vers des liens Doctolib.fr, sans restriction (pour tout, y compris les centres) :(

Pas de souci, on se rattrapera à la Garden Party
