### ISSUE TITLE
Pourquoi toutes les dates des prochains rdv ne sont pas indiqués

### ISSUE THREAD

**Issue by DavidLibeau** [CovidTrackerFr/vitemadose#392]
Bonjour,
#291 a ajouté un décompte des rendez-vous disponibles à J1, J7, J28 et J49, mais n'a pas inclus les informations sur la date des rendez-vous disponibles.
Y-a-t-il une raison pour ne pas avoir inclus dans les données les dates des rendez-vous ?
Merci

**Comment by Noezor** [comment]
Mhhh je ne suis pas celui qui ai fait #291 mais je pense que la raison la plus simple est que ça fait énormément de data dans ton json plutôt qu'avoir une donnée agrégée. On a aussi aucune utilité produit à faire ça : on regarde soit la date la plus récente, soit les dispos chronodoses.

**Comment by DavidLibeau** [comment]
Merci de la réponse rapide.
C'est dommage car cela signifie que vous faites une sélection des données à ouvrir… et j'avais compris que vous souhaitiez faire de l'open data. En choisissant quelles données vous ouvrez et lesquelles vous n'ouvrez pas selon uniquement des cas d'utilisation ou selon un produit préexistant, vous ne répondez pas complètement aux enjeux d'open data. On retrouve cette problématique partout et on tend à toujours répondre : ouvrez tout ce que vous pouvez.
De mon côté, je veux avoir accès à ces données pour une réutilisation, et je ne peux donc pas. Pensez-vous qu'il serait possible d'inclure ces données ?

**Comment by rozierguillaume** [comment]
Ces données ne sont pas collectées et donc ne peuvent, à fortiori, pas être publiées. 
N'hésitez pas à implémenter une solution, puis à soumettre une PR.

**Comment by DavidLibeau** [comment]
> Ces données ne sont pas collectées et donc ne peuvent, à fortiori, pas être publiées.

Donc, le comptage à J1, J7, J28 et J49 est une donnée brute ? J'avais compris que c'est vous qui faisiez le comptage selon les rendez-vous disponibles. Si tel est le cas, et c'est comme ça que je lis le code https://github.com/CovidTrackerFr/vitemadose/pull/291/files#diff-ead15f8d228d82221e5bfa1fd4221c2a20eea14c74a3cb09f9071a395ce52256R240 (même si je ne code pas en Python), vous avez bien les données et vous faites un `len` sans publier l'intégralité des données.

**Comment by DavidLibeau** [comment]
@fcamblor Oui, je suis totalement d'accord avec ces arguments qui concernent le premier point.

Donc, on est d'accord que la seconde solution serait le mieux ?

**Comment by aureliancnx** [comment]
Bonjour,

ViteMaDose ne récolte que la date du premier rendez-vous disponible et une mesure statistique des créneaux disponibles sur un intervalle de 1, 7, 28 et 49 jours. Nous n'avons pas pour objectif pour le moment de remplacer les plateformes de réservation en ligne, en fournissant un calendrier aussi détaillé qu'eux, car le but est de donner les premières disponibilités pour les personnes qui pourraient avoir des difficultés à trouver un créneau de vaccination.

Nous n'avons pas d'API à proprement parler comme vous le mentionnez, il s'agit de fichiers JSON statiques, générés lors d'un scrape. Pour le moment, il n'est pas pensable de gérer toute cette masse de données de rendez-vous en un ou plusieurs fichiers JSON statiques, et cela demanderait de nombreux changements back-end et l'ajout d'une API, une idée que nous avons écarté pour le moment, car servir des fichiers JSON statiques qui changent régulièrement permet de supporter des pics de charges conséquents sur notre plateforme, sans posséder une infrastructure de plusieurs dizaines de serveurs.

Si vous souhaitez développer l'idée, rien ne vous empêche de fork le projet et de mettre cela en oeuvre.

Cordialement,

**Comment by gaelbenoit** [comment]
En faite vous voulez avoir accès à une donnée que nous ne produisons pas. 

Vous faite votre propre interprétation du terme open data: nous entendons par là que nous mettons à disposition publique les données que nous produisons, vous vous souhaitez avoir accès aux données que nous consultons. Bonne nouvelle, elles sont accessibles pour vous comme pour nous sur les plateformes de réservation. 

Nous n'avons pas besoin de connaitre l'intégralité des heures de rendez-vous, juste le premier et leur nombre. Les API des plateformes sont ainsi faites qu'il n'est pas possible d'obtenir cette donnée sans lire l'intégralité des agendas.

En résumé vous avez votre réponse: nous mettons à disposition l'intégralité des données que nous produisons, rien de moins, rien de plus

**Comment by DavidLibeau** [comment]
@aureliancnx C'est une API statique et non dynamique, mais c'est bien une API, à savoir une interface conçu pour être utilisé par un logiciel (ici le front de ViteMaDose).

@gaelbenoit Super, merci pour cette réponse complète. Je déplore que votre objectif ne soit pas l'ouverture de toutes les données disponibles, de l'open data par défaut (dans l'esprit des réserves de l'article L. 311-6 du CRPA).

Ce qui m'empêche de fork ou de faire mon propre scrap c'est bien la `DOCTOLIB_API_KEY` qui vous a été donné en exclusivité.
