### ISSUE TITLE
Redirection de l'ancienne adresse Vitemadose vers la nouvelle

### ISSUE THREAD

**Issue by reminesta** [CovidTrackerFr/vitemadose#401]
L'ancienne adresse https://covidtracker.fr/vitemadose/ redirige vers https://vitemadose.covidtracker.fr/ en redirection 302 (redirection temporaire) au lieu de redirection 301 (redirection définitive).

<img width="347" alt="3" src="https://user-images.githubusercontent.com/84020427/117812745-7b4b3e80-b262-11eb-9622-8ef3d22d8d8f.PNG">
Il est recommandé en SEO d'utiliser des redirections 301 pour les changements d'adresse, afin que Google mette correctement à jour son index, cf les résultats Google qui remontent toujours l'ancienne URL :
<img width="472" alt="1" src="https://user-images.githubusercontent.com/84020427/117812928-b9486280-b262-11eb-848a-6d1e353dcb38.PNG">

**Comment by Maijin** [comment]
Plus une info pour le front (https://github.com/CovidTrackerFr/vitemadose-front) ping @fcamblor

**Comment by reminesta** [comment]
> Plus une info pour le front (https://github.com/CovidTrackerFr/vitemadose-front) ping @fcamblor

En effet, au temps pour moi. Je recrée l'issue là bas. :)
