### ISSUE TITLE
Résultats Chronodose "très faux" en Isère

### ISSUE THREAD

**Issue by Noezor** [CovidTrackerFr/vitemadose#407]
https://github.com/CovidTrackerFr/vitemadose-front/issues/191

**Comment by iGitScor** [comment]
Même constat pour Doctolib + Montpellier

**Comment by aureliancnx** [comment]
Je constate que sur Keldoc, l'implémentation a l'air d'être faite assez différemment.

J'ai l'impression que les centres gèrent un peu les doses allouées comme ils le souhaitent pour les "chronodoses", il y a une "catégorie de motif" dédiée à  "Personne +18 ans sans critère - RDV < 24H", sans aucun rendez-vous. Cependant, il y a bien des créneaux disponibles pour le prochain jour dans les autres motifs.

Exemple avec Alpexpo : https://vaccination-covid.keldoc.com/redirect/?dom=cabinet-medical&inst=grenoble-38000&user=vaccinodrome-grenoble&category=-1&cabinet=18795&specialty=144

Soit les centres n'ont pas encore configuré la fonctionnalité, soit Keldoc n'a pas mis en prod l'implémentation complète des chronodoses, soit les centres gèrent comme ils le souhaitent les créneaux pour les chronodoses (et décident donc d'en mettre ou non ?)

On ressort bien les créneaux à J+1, mais l'arrivée de cette "catégorie de motif" change tout. Il faudrait voir avec notre contact chez Keldoc

**Comment by ffourcot** [comment]
Je crois avoir surtout observé que Keldoc utilise une définition stricte des 24h.

Un créneau disponible dans 26h (J+1 à midi alors qu'il est 10h du matin) ne sera pas mis à disposition des  "Personne +18 ans sans critère - RDV < 24H". Un créneau disponible le même jour à 8h du matin, si (22h seulement avant le rendez-vous)

Du coup vitemadose remonte beaucoup de créneaux "chronodose" qui ne sont pas éligibles avec les règles de Keldoc.

**Comment by darrepac** [comment]
Moi ce que je vois c’est que Chronodose affiche tous les creneaux dispos le
lendemain quelque soit le motif alors que la plupart sont réservés pour
certains motifs…

Le jeu. 13 mai 2021 à 14:21, Florent Fourcot ***@***.***> a
écrit :

**Comment by gromain** [comment]
Je confirme les problèmes avec Keldoc. Ils existent aussi parfois avec Doctolib (quand il existe sur Doctolib une catégorie plus de 18 ans moins de 24h).

**Comment by darrepac** [comment]
Y a aussi le cas sur Doctolib : affiche dose dispo et quand on va sur doctolib, voilà la choix qu'on a:
![image](https://user-images.githubusercontent.com/7128994/118155435-8a73ed00-b418-11eb-927a-a84a783d163b.png)

**Comment by gromain** [comment]
J'ai envie de mentir, mais ça manque de clarification. Peut être que dans l'appli et sur le site un message pourrait expliquer la situation (sans faire de recommandations sur mentir ou pas, je pense que de toute façon, si tu as fait ta résa moins de 24h avant, ça va être compliqué pour le centre de refuser la vaccination) et expliquer la disparité qui existe entre ce qui est affiché dans vitemadose et dans doctolib/keldoc.

**Comment by Noezor** [comment]
Outre le cas : les doses ne sont plus dispo au moment de votre consultation du site, je crois que vous remontez 2 gros problèmes.
+ Le fait qu'on soit trop large sur la définition pour Keldoc et Maiia, qui utilise 24h strict glissante.
+ On a pris en compte juste les directions gouvernementales, qui étaient que toutes les doses à 24h étaient disponibles pour tout le monde. En pratique, il semblerait que les centres n'aient soit pas tous fait les changement sur les plateformes, soit ne respectent pas la règle... Comme c'est très dur de savoir dans quel cas chaque centre tombe (si il n'y a que un motif "vaccination Pfizer" sans précision 24h, est ce que c'est disponible ou pas ? Inversement, si il n'y est pas, est ce que c'est vraiment impossible de book sur un autre motif ou juste un oubli ?), je pense qu'on ne va pas pouvoir changer cette situation. La recommandation officieuse de Guillaume sur Twitter était de s'arranger avec les motifs tant que vous respectez bien la règle des 24h.

**Comment by gromain** [comment]
ça me paraît normal. C'est pour ça que je disais que peut être juste un warning dans la FAQ sur le pourquoi du comment c'est pas pareil ça pourrait être pas mal. Pas forcément besoin de plus à ce stade, tant qu'on a pas plus d'infos sur le fonctionnement précis.

**Comment by darrepac** [comment]
> Outre le cas : les doses ne sont plus dispo au moment de votre consultation du site, je crois que vous remontez 2 gros problèmes.
> 
> * Le fait qu'on soit trop large sur la définition pour Keldoc et Maiia, qui utilise 24h strict glissante.
> * On a pris en compte juste les directions gouvernementales, qui étaient que toutes les doses à 24h étaient disponibles pour tout le monde. En pratique, il semblerait que les centres n'aient soit pas tous fait les changement sur les plateformes, soit ne respectent pas la règle... Comme c'est très dur de savoir dans quel cas chaque centre tombe (si il n'y a que un motif "vaccination Pfizer" sans précision 24h, est ce que c'est disponible ou pas ? Inversement, si il n'y est pas, est ce que c'est vraiment impossible de book sur un autre motif ou juste un oubli ?), je pense qu'on ne va pas pouvoir changer cette situation. La recommandation officieuse de Guillaume sur Twitter était de s'arranger avec les motifs tant que vous respectez bien la règle des 24h.

Ca fait sens. Néanmoins je n'ai pas trouvé le tweet en question de Guillaume...un lien?

**Comment by Noezor** [comment]
https://twitter.com/GuillaumeRozier/status/1391809675478421505

Après encore une fois, c'est juste l'opinion de Guillaume, pas une directive officielle. Mais bon, en voyant que les centres/ARS ne suivent pas les directives du gouvernement... c'est quoi officiel ?

**Comment by francoisBouchet** [comment]
alors typiquement, ce qui m'est arrivé (avec Keldoc) sur Grenoble mercredi :

- mercredi matin, 7-8h, au réveil, je retente un coup sur mes bookmarks. des chronodoses chez VMD, pourtant aucun créneau "18ans+ <24h" disponible sur les différents centres Keldoc en Isère...
- mais, dans un des centres (Hôpital de Grenoble/La Tronche) : "18ans+ <24h" n'est même pas affiché dans les motifs de vaccination possibles, en revanche : **des créneaux toutes les demie-heures TOUTE LA JOURNEE** (et même jusqu'à la fin de la semaine), avec le motif "18+ vulnérable sans ordonnance"... (motif encore différent de "18+ avec commorbidités"...)
- ça m'a posé des petits problèmes de conscience, mais je me suis tout de même lancé - avec succès dans la résa d'un créneau. la règle officielle étant "tous les créneaux du jour-même + lendemain". 3h plus tard j'étais vacciné.

Je pense que les centres créent des catégories, les remplissent de créneaux, mais après n'ont pas le temps de suivre la chose et de transvaser des doses/créneaux d'une catégorie vers l'autre.. ça doit soit être une tannée, ou alors ils y pensent pas parce que l'outil reconduit les créneaux les jours suivants automatiquement mais dans la même catégorie (j'imagine), ... bref les "créneaux pour tous", c'est pas encore entré dans le process de tous les centres...

**Comment by Noezor** [comment]
Ouais ... je pense vraiment que c'est un problème de leur côté +. C'est une "bonne" décision de pas prendre compte de ces notifs, quitte à ce que les gens choisissent le mauvais motif.

**Comment by grubounet** [comment]
Du coup le soucis est réglé en passant Keldoc sur 24h glissantes ? Après c'est un choix volontaire de prendre en compte TOUS les créneaux, puisque c'est la consigne du gouvernement

**Comment by grubounet** [comment]
J'ai regardé un peu, depuis le passage sur 24h glissantes les résultats sont cohérents. @Maijin @Noezor @aureliancnx tu peux close ?

**Comment by Noezor** [comment]
On a encore le problème des motifs, mais c'est vrai que normalement les pushes des 24h glissantes ont dû résoudre ce problème.

**Comment by Maijin** [comment]
Reouvre une autre issue s'il faut
