### ISSUE TITLE
Add Gitlab action to push data to Data.gouv

### ISSUE THREAD

**Issue by Maijin** [CovidTrackerFr/vitemadose#408]
Add Gitlab action to push data to Data.gouv (https://www.data.gouv.fr/fr/organizations/covidtracker/) automatically the recent data.

**Comment by grubounet** [comment]
@Maijin on a déjà ce dataset automatique avec les centres de vaccination : https://www.data.gouv.fr/en/datasets/vite-ma-dose-de-vaccin/
Tu voyais quoi de plus toi ?

**Comment by Maijin** [comment]
L'idee ici c'etait de pousser nos datas vers data.gouv automatiquement

**Comment by grubounet** [comment]
Mais quelle type de data par exemple ?Les dispos de chaque centre ? Les stats ?La liste des centres ?Je m'en occuperai avec plaisir !!Le 22 juil. 2021 10:50, Maijin ***@***.***> a écrit :
L'idee ici c'etait de pousser nos datas vers data.gouv automatiquement
