### ISSUE TITLE
Ajouter des tests sur toutes les plateformes

### ISSUE THREAD

**Issue by Olivier4477** [CovidTrackerFr/vitemadose#418]
Pour les notifications mobile, l'internal_id et le practice_id dois toujours rester les mêmes.
Ajouter des tests unitaire pour vérifier que ces valeurs ne soit pas modifié

(au pire je m'en occupe) ;)

**Comment by tlevillayer** [comment]
La notion de practice_id est relative à Doctolib uniquement ou aussi à d'autres plateformes ?

**Comment by michgauz** [comment]
Hey!
on n'utilise pas le practice_id sur Android, je ne vois pas de raison qu'iOS l'utilise également

**Comment by victor-sarda** [comment]
On ne l'utilise pas sur iOS non plus 👍

**Comment by aureliancnx** [comment]
Les tests unitaires ne sont pas une garantie que les internal_id ne peuvent pas changer du côté des plateformes, mais seulement sur notre intégration.

**Comment by Maijin** [comment]
Je ferme pour le moment ici, @Olivier4477  si tu as des questions n'hesites pas a rejoindre le mattermost 😃
