### ISSUE TITLE
Centre grisé alors qu'il y a des dispos - 24200 Sarlat-la-Canéda

### ISSUE THREAD

**Issue by tdevlaeminck** [CovidTrackerFr/vitemadose#424]
Bonjour, 

Le centre de vaccination Centre culturel Paul Eluard, Rue Gaubert, 24200 Sarlat-la-Canéda est grisé sur VMD (et apparait 2 fois) : 

![image](https://user-images.githubusercontent.com/82476476/118014590-ab263f00-b353-11eb-9763-f5157b8efda2.png)

Or il y a des dispos dès le 24 mai sur Doctolib : 

![image](https://user-images.githubusercontent.com/82476476/118014669-bf6a3c00-b353-11eb-922a-17c0fa8f1324.png)

Thanks

**Comment by Noezor** [comment]
Lié à #433

**Comment by grubounet** [comment]
Quand on regarde https://www.doctolib.fr/booking/vaccination-ch-jean-leclaire-sarlat, on remarque que le centre semble posseder deux places practice-163750 et practice-164700
Dans agendas, pour l'entrée 4 on a practice_id: 163750 mais pas de visit_motive_ids_by_practice_id

FIX proposé : pour chaque centre, on récupère l'ensemble des practice-id dans places, mais on ne génère l'URL que si le practice-id en question est contenu dans le visit_motive_ids_by_practice_id d'au moins un agenda. @Noezor qu'en penses tu ?

**Comment by Noezor** [comment]
ça a été fix, regarde #433

**Comment by Noezor** [comment]
Ah bah non c'était pas fix, @grubounet si tu veux faire une PR ok, mais fais attention aux régressions :D

**Comment by grubounet** [comment]
C'est fix par #543, je close !
