### ISSUE TITLE
Centres identiques dans le département du Jura (39)

### ISSUE THREAD

**Issue by baptistepl** [CovidTrackerFr/vitemadose#426]
Sur VMD, pour le département du Jura, tous les centres ont le même nom
https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt39-jura/recherche-standard
![image](https://user-images.githubusercontent.com/32340024/118025452-2db4fb80-b360-11eb-8ace-0d7f92d0a5c0.png)

**Comment by Noezor** [comment]
Sera fix avec #433

**Comment by DjMomo** [comment]
Je suppose que c'est identique pour celui là... 

<img width="851" alt="Capture d’écran 2021-05-13 à 11 49 58" src="https://user-images.githubusercontent.com/4518584/118109482-90021080-b3e1-11eb-802f-778862502be7.png">

https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt81-tarn/recherche-standard

**Comment by Noezor** [comment]
Fix avec #433
