### ISSUE TITLE
Lien non fonctionnel pour douai

### ISSUE THREAD

**Issue by max5962** [CovidTrackerFr/vitemadose#429]
Hello,

Chronodose dispo au centre de Douai :
![Screenshot_20210512-225103](https://user-images.githubusercontent.com/34659571/118042734-bb024b00-b374-11eb-9338-2564ff6dc8ab.png)

Mais le lien :
https://www.doctolib.fr/centre-de-sante/douai/cpts-grand-douai-salle-gayant-expo/booking/motive-categories?pid=practice-178830&placeId=practice-178830&specialityId=5494

Demande une catégorie différentes de "18 ans et + sans comorbidité"

![Screenshot_20210512-225427](https://user-images.githubusercontent.com/34659571/118042969-0ddc0280-b375-11eb-8777-38902787c02b.png)

**Comment by aureliancnx** [comment]
L'intégration de Doctolib ne propose pas tout le temps un motif pour les doses J+0 à J+1 disponibles pour les +18 ans. Leur intégration est différente et nous nous ne basons pas sur un motif particulier.

**Comment by max5962** [comment]
Hello,

Dans ce cas devrions-nous pas "ne pas les proposer" ? 
Car ce sont finalement pas des chronodose ?

**Comment by Noezor** [comment]
Je crois qu'on avait fait le parti pris de quand même les proposer en chronodoses. Les règles gouvernementales doivent normalement être suivies par tous les centres, et c'est en général car un administratif ne l'a pas mis à jour. 
En pratique, je crois que les utilisateurs "mentent" sur le motif dans ce cas là pour avoir un rdv.

**Comment by Noezor** [comment]
@max5962 je ferme car ce n'est pas un problème qu'on peut résoudre avec du code. Cependant, tu peux appeler le centre et essayer d'avoir le numéro de qqn qui s'en occupe pour faire ajouter ce motif de notification.

**Comment by max5962** [comment]
@Noezor pas de soucis :)
