### ISSUE TITLE
Ordoclic : Pharmacie avec `NextSlot` non null mais `appointment_count = 0`

### ISSUE THREAD

**Issue by dumoulinjb** [CovidTrackerFr/vitemadose#430]
Le centre suivant, extrait de Ordoclic, à une date de prochain rdv en juillet, mais le nombre de créneau est indiqué à 0.

Merci

`{
"departement": "95",
"nom": "Pharmacie De La Mairie",
"url": "https://app.ordoclic.fr/app/pharmacie/pharmacie-de-la-mairie-andilly",
"location": {
"longitude": 2.2988758,
"latitude": 49.0048594,
"city": "andilly"
},
"metadata": {
"address": "9 place louis jean finot, 95580 andilly",
"phone_number": "+33139592168",
"business_hours": null
},
"prochain_rdv": "2021-07-03T11:30:00+00:00",
"plateforme": "Ordoclic",
"type": "drugstore",
"appointment_count": 0,
"internal_id": "ordoclicace3c632",
"vaccine_type": [
"AstraZeneca"
],
"appointment_by_phone_only": false,
"erreur": null,
"last_scan_with_availabilities": "2021-05-12T23:18:29.681896+02:00",
"appointment_schedules": [
{
"name": "chronodose",
"from": "2021-05-12T00:00:00+02:00",
"to": "2021-05-13T23:59:59+02:00",
"total": 0
},
{
"name": "1_days",
"from": "2021-05-12T00:00:00+02:00",
"to": "2021-05-12T23:59:59+02:00",
"total": 0
},
{
"name": "2_days",
"from": "2021-05-12T00:00:00+02:00",
"to": "2021-05-13T23:59:59+02:00",
"total": 0
},
{
"name": "7_days",
"from": "2021-05-12T00:00:00+02:00",
"to": "2021-05-18T23:59:59+02:00",
"total": 0
},
{
"name": "28_days",
"from": "2021-05-12T00:00:00+02:00",
"to": "2021-06-08T23:59:59+02:00",
"total": 0
},
{
"name": "49_days",
"from": "2021-05-12T00:00:00+02:00",
"to": "2021-06-29T23:59:59+02:00",
"total": 0
}
],
"gid": "ace3c632"
}`

**Comment by dumoulinjb** [comment]
Est-ce du au fait que le RDV est à plus de 50 jours ?

**Comment by aureliancnx** [comment]
> Est-ce du au fait que le RDV est à plus de 50 jours ?

Oui. Le rendez-vous n'est pas censé apparaître.
