### ISSUE TITLE
Keldoc :  Centre avec `NextSlot` non null mais `appointment_count = 0`

### ISSUE THREAD

**Issue by dumoulinjb** [CovidTrackerFr/vitemadose#431]
Le centre suivant, extrait de Keldoc, à une date de prochain rdv en juin, mais le nombre de créneau est indiqué à 0.

Merci

`{
"departement": "95",
"nom": "Centre de vaccination territorial Centre Val d'Oise",
"url": "https://vaccination-covid.keldoc.com/cabinet-medical/montmorency-95160/vaccination-plaine-vallee-montmorency-salle-des-fetes?category=-1&cabinet=16607&specialty=496",
"location": {
"longitude": 2.32059,
"latitude": 48.9893,
"city": "Montmorency"
},
"metadata": {
"address": "3 Avenue Foch, 95160 Montmorency",
"phone_number": "+33130103980",
"business_hours": {
"lundi": "14h-17h",
"mardi": "14h-17h",
"mercredi": "fermé",
"jeudi": "fermé",
"vendredi": "fermé",
"samedi": "14h-17h",
"dimanche": "fermé"
}
},
"prochain_rdv": "2021-06-08T14:35:00.000000+0200",
"plateforme": "Keldoc",
"type": "vaccination-center",
"appointment_count": 0,
"internal_id": "keldoc824",
"vaccine_type": [
"Pfizer-BioNTech"
],
"appointment_by_phone_only": false,
"erreur": null,
"last_scan_with_availabilities": "2021-05-12T23:28:29.428742+02:00",
"appointment_schedules": [
{
"name": "chronodose",
"from": "2021-05-12T00:00:00+02:00",
"to": "2021-05-13T23:59:59+02:00",
"total": 0
},
{
"name": "1_days",
"from": "2021-05-12T00:00:00+02:00",
"to": "2021-05-12T23:59:59+02:00",
"total": 0
},
{
"name": "2_days",
"from": "2021-05-12T00:00:00+02:00",
"to": "2021-05-13T23:59:59+02:00",
"total": 0
},
{
"name": "7_days",
"from": "2021-05-12T00:00:00+02:00",
"to": "2021-05-18T23:59:59+02:00",
"total": 0
},
{
"name": "28_days",
"from": "2021-05-12T00:00:00+02:00",
"to": "2021-06-08T23:59:59+02:00",
"total": 0
},
{
"name": "49_days",
"from": "2021-05-12T00:00:00+02:00",
"to": "2021-06-29T23:59:59+02:00",
"total": 0
}
],
"gid": "824"
}`

**Comment by aureliancnx** [comment]
Je récupère 20 créneaux.

**Comment by grubounet** [comment]
Ca a l'air fix, @dumoulinjb je close et je te laisse rouvrir une issue si tu ré aperçois des soucis !!
