### ISSUE TITLE
Scrap d'un nouveau site - avecmondoc.com

### ISSUE THREAD

**Issue by Bouska** [CovidTrackerFr/vitemadose#432]
@tdevlaeminck a remonté sur Mattermost la plateforme [avecmondoc.com](https://avecmondoc.com/) qui souhaiterait apparaître sur VMD.

### Analyse préliminaire de l'API
AvecMonDoc dispose d'une API assez simple d'utilisation a priori.

#### Liste des praticiens
GET endpoint : `https://api.avecmondoc.com/api/Doctors/search?params={"city":null,"dateBefore":null,"specialityId":190}&options={"limit":100,"page":1}`
Récupère la totalité (?) des pharmacies de façon paginé (total 231) [en pratique on peut passer `limit` à 500 et tout récupérer sur une page]. `specialityId` à `190` c'est pour les pharmacies, `1` c'est pour la médecine générale ; apparemment, on peut aussi utiliser `professionId` à 14 pour avoir tous les médecins (total 187).

On ne récupère pas beaucoup d'information sur cet endpoint. Grosso modo, il va juste permettre de récupérer le `slug` et l'`id`pour chaque practitien.

#### Information praticien
GET endpoint: `https://api.avecmondoc.com/api/Doctors/slug/pharmacie-du-chateau-581` (où `pharmacie-du-chateau-581` est le `slug` récupéré à l'endpoint précédent)
GET endpoint: `https://api.avecmondoc.com/api/Organizations/getByDoctor/581` (où `581` est l'`id` récupéré dans le premier endpoint)
A priori, comme ça, il n'y a rien qui nous intéresse dans le premier endpoint qui ne soit pas dans le deuxième. L'`id` est particulièrement important, ici `543`.

#### Liste motives
GET endpoint:  `https://api.avecmondoc.com/api/Organizations/getConsultationReasons?params={"organizationId":543,"doctorId":581}` (où `543` et `581` sont les `id` récupérés précédemment)

Là, on peut récupérer les `reasons`, avec en particulier celles qui nous intéressent `Première injection vaccinale COVID-19` (id `580` [attention, les `id` ne sont pas communs à tous les praticiens !]) et `Seconde injection vaccinale COVID-19` (id `581`) [je suppose que c'est de l'AstraZeneca, je ne sais pas comment ils gèrent si c'est autre chose que ça)]

#### Listes slots
POST endpoint: `https://api.avecmondoc.com/api/BusinessHours/availabilitiesPerDay ; payload `{"consultationReasonId":580,"disabledPeriods":[],"doctorId":581,"fullDisplay":false,"organizationId":543,"periodEnd":"2021-05-15T22:00:00.000Z","periodStart":"2021-05-09T22:00:00.000Z","specialityId":190,"type":null}` 

Le payload est assez clair, on a a récupéré toutes les informations dans les endpoints précédents. Dans le JSON récupéré, soit on a pas de créneaux disponible est le prochain créenau dispo sera donné par `nextAvailableBusinessHours`, soit on a aura une liste de jour avec des `slots` par journée.

cc @gaelbenoit & @Noezor

**Comment by gaelbenoit** [comment]
J'ai fait la base du scrape, il reste encore un peu de boulot et d'implémenter les tests unitaires

![image](https://user-images.githubusercontent.com/11502741/118370616-ab6b4800-b5a8-11eb-958c-600339acf272.png)
