### ISSUE TITLE
Mapharma : problème de scrap

### ISSUE THREAD

**Issue by rozierguillaume** [CovidTrackerFr/vitemadose#434]
Visisblement on a un souci avec cette pharmacie ![image](https://user-images.githubusercontent.com/22763678/118084282-bc596500-b3c0-11eb-8c6b-490748eb6c42.png)![image](https://user-images.githubusercontent.com/22763678/118084289-bebbbf00-b3c0-11eb-8bb0-87491fff18fc.png)

**Comment by grubounet** [comment]
@mathilde-leval a fix avec la #444 je crois !

@Noezor tu peux close ?
