### ISSUE TITLE
Ajouter manuellement des centres

### ISSUE THREAD

**Issue by Noezor** [CovidTrackerFr/vitemadose#435]
On peut déjà [bloquer des centres à la main](https://github.com/CovidTrackerFr/vitemadose/pull/303). Il serait cool de pouvoir ajouter à la main des URLs pour quand le scrapper de centre ne passe pas.

**Ce que je propose :** 
On a déjà une liste "manuelle" avec les centres, le `.csv` du gouvernement. Son iterateur est [ici](https://github.com/CovidTrackerFr/vitemadose/blob/c8a39e7fc4115f8aacc52eb1e9de97613ff0cb53/scraper/opendata/opendata.py#L13-L47). Il serait bien de copier le même gerne de json mais avec nos datas, en faire un itérateur à part, et l'ajouter [ici](https://github.com/CovidTrackerFr/vitemadose/blob/c8a39e7fc4115f8aacc52eb1e9de97613ff0cb53/scraper/scraper.py#L191-L197). -> EDIT : Un json serait mieux qu'un csv. Après discussions avec Maijin, un google sheets -> json -> scrapper serait le mieux en terme d'UX.

C'est une issue avec un peu de code à écrire, mais je pense qu'elle est assez bien guidée et a une grosse plus-value pour la plateforme.

**Comment by Olivier4477** [comment]
Je m'y met (damien57 sur mattermost)

**Comment by Noezor** [comment]
On a l'intégration mais pas encore les centres, je réouvre

**Comment by ValentinMouret** [comment]
Je vais créer le spreadsheet ce soir.
