### ISSUE TITLE
Adresses erronées pour "Centre de Vaccination Covid 19 - Ville de Paris"

### ISSUE THREAD

**Issue by humpfhumpf** [CovidTrackerFr/vitemadose#436]
Le "Centre de Vaccination Covid 19 - Ville de Paris" est lié à 8 sites (pid) qui ont des adresses différentes.
Or, actuellement, tous ces sites sont affichés à la même adresse, ce qui n'était pas le cas, il y a 2 jours sur VMD.

Les liens d'accès sont toujours bons:
* https://www.doctolib.fr/centre-de-sante/paris/centre-de-vaccination-covid-19-ville-de-paris?pid=practice-176642
* https://www.doctolib.fr/centre-de-sante/paris/centre-de-vaccination-covid-19-ville-de-paris?pid=practice-164812
* etc...

![image](https://user-images.githubusercontent.com/43614174/118112269-0fddaa00-b3e5-11eb-9cbf-2a0f3473d7c8.png)

**Comment by Noezor** [comment]
#433 devrait fix ça, ça a été cassé il y a 2 jours
