### ISSUE TITLE
Disparition de VMD de deux tiers des centres en Mayenne

### ISSUE THREAD

**Issue by inderweltsein** [CovidTrackerFr/vitemadose#440]
En Mayenne, le centre de vaccination le plus important du département a totalement disparu de VMD depuis quelques jours (il me semble que ça coincide avec leurs regroupements des centres par "onglets" sur la page doctolib... ce qui expliquerait que d'autres plus petits ait disparu, mais pourtant certains des centres regroupés sont toujours présents.

Les centres disparus
Laval:
https://www.doctolib.fr/maison-de-sante/mayenne/pole-de-sante-de-mayenne-centre-de-vaccination?pid=practice-164879
Ernée:
https://www.doctolib.fr/maison-de-sante/mayenne/pole-de-sante-de-mayenne-centre-de-vaccination?pid=practice-164906
Craon:
https://www.doctolib.fr/maison-de-sante/mayenne/pole-de-sante-de-mayenne-centre-de-vaccination?pid=practice-164901
Meslay-du-Maine:
https://www.doctolib.fr/maison-de-sante/mayenne/pole-de-sante-de-mayenne-centre-de-vaccination?pid=practice-164911

Ces centres sont pourtant bien listés dans
main/data/output/doctolib-centers.json

Edit: Bon ça n'est pas exactement deux tiers des centres en fait, puisque deux ou trois autres centres ne sont pas regroupés.

**Comment by inderweltsein** [comment]
Je vais essayer de déterminer pourquoi les centres ne sont pas parsés ce week-end.
Mais en tout cas ça rend VMD assez inutile dans la région de Laval puisque ça incite à partir à plus de 50km (ce qui la plupart du temps n'est surement pas une solution légitime)

**Comment by Noezor** [comment]
C'était lié à #433 ! Ça a été fix. Merci beaucoup pour ton rapport
