### ISSUE TITLE
Respecter les 24h glissantes sur Maiia et Keldoc pour les chronodoses

### ISSUE THREAD

**Issue by Noezor** [CovidTrackerFr/vitemadose#443]
On déclare des rdvs un peu trop larges en Maiia et Keldoc. On a pris en compte le même critère que sur doctolib alors qu'en pratique ils opèrent sur 24h glissantes. Cela semble créer pas mal de frustrations pour ces 2 providers (cf. #407) .

Il faudrait changer la définition de ce qu'on met dans chronodose en fonction de 24h glissantes et pas juste aujourd'hui et demain.

**Comment by grubounet** [comment]
J'ai fait les corrections demandées, dès que tu peux merge @Noezor tu pourras close ici aussi :)

**Comment by aureliancnx** [comment]
Merci
