### ISSUE TITLE
Médecin qui ne remonte pas - 21121 Fontaine-lès-Dijon

### ISSUE THREAD

**Issue by tdevlaeminck** [CovidTrackerFr/vitemadose#453]
Bonjour, 

Docteur Anne-Sophie Poulain, généraliste à Fontaines les Dijon (21121) a des rendez-vous Astrazeneca pour le 28 mai. 
![image](https://user-images.githubusercontent.com/82476476/118233385-20982980-b492-11eb-87cf-459545c6fa24.png)
Url : https://www.doctolib.fr/medecin-generaliste/marseille/anne-sophie-poulain

Or elle n'apparait pas sur VMD.

Thanks

**Comment by grubounet** [comment]
Elle n'apparait pas sur https://doctolib.fr/vaccination-covid-19/fontaine-les-dijon
... surement un soucis du coté de docto ?
On la mettra à la main dans la nouvelle liste des centres manquants

**Comment by grubounet** [comment]
@tdevlaeminck peux tu prévenir la médecin (j'imagine qu'elle t'a contacté ?) de voir avec doctolib en expliquant que c'est parcequ'elle n'apparait pas en tant que centre de vaccination sur doctolib (on ne la trouve pas sur https://www.doctolib.fr/vaccination-covid-19/marseille), probablement lié à une erreur dans la config des 2e doses ?

**Comment by tdevlaeminck** [comment]
Merci pour le retour 🙂, 
Je préviens la médecin aujourd'hui.

**Comment by tdevlaeminck** [comment]
Médecin prévenue.
