### ISSUE TITLE
Décompte nombre créneaux et lieux de vaccination différents entre applis et site VMD

### ISSUE THREAD

**Issue by DjMomo** [CovidTrackerFr/vitemadose#454]
Bonjour,

Il y a un affichage totalement différent entre le site et les applis sur le nombre de centres de vaccination et de créneaux affichés pour une commune donnée (sans filtre appliqué je précise).
Exemple pour 87270 - Bonnac-la-Côte :
Sur le site : 4271 créneaux et 31 lieux de vaccination avec des disponibilités :

![IMG_20210514_090027](https://user-images.githubusercontent.com/4518584/118234784-1ecf6580-b494-11eb-99f6-0913d08cd144.jpg)

Alors que sur l'application (idem Android ou iPhone) seulement 2 lieux pour 129 créneaux :

![IMG_20210514_090022](https://user-images.githubusercontent.com/4518584/118234837-327acc00-b494-11eb-8840-02fc6e496858.jpg)

**Comment by Bouska** [comment]
Ca c'est un problème avec le front et les app, les données du back utilisés par les deux sont les mêmes, c'est une question d'affichage (ou de renouvellement des données) . Poste le bug plutôt sur https://github.com/CovidTrackerFr/vitemadose-front
