### ISSUE TITLE
HIA Sainte Anne grisé - 83200 Toulon

### ISSUE THREAD

**Issue by tdevlaeminck** [CovidTrackerFr/vitemadose#455]
Bonjour, 

L'HIA Sainte Anne à Toulon a des rendez-vous dispo dès demain, 
Pourtant il est grisé sur VMD. 

Doctolib : https://www.doctolib.fr/centre-de-sante/toulon/centre-de-vaccination-covid-19-hopital-d-instruction-des-armees-chia-sainte-anne?pid=practice-179632

![image](https://user-images.githubusercontent.com/82476476/118238506-e2eacf00-b498-11eb-94d8-bff71b5d9168.png)

![image](https://user-images.githubusercontent.com/82476476/118238530-eaaa7380-b498-11eb-9592-6687b4d128a4.png)

Thanks

**Comment by grubounet** [comment]
Soucis au niveau de doctolib.filters.appointment_category dans config.json, il manque des motifs que le centre utilise

Je vais essayer de regarder ça

![image](https://user-images.githubusercontent.com/31167642/118257336-cf4a6300-b4ae-11eb-8630-e18d1b0ba981.png)

**Comment by grubounet** [comment]
Corrigé dans la #459, est ce que qqn peut merge et close ? (cc @Maijin @Noezor @aureliancnx)
