### ISSUE TITLE
Manque un motif sur centre

### ISSUE THREAD

**Issue by Noezor** [CovidTrackerFr/vitemadose#477]
Le centre ci-dessous fait du Pfizer + AZ
https://www.doctolib.fr/maison-de-sante/beauvallon/centre-de-vaccination-covid-19-pays-mornantais?pid=practice-180904

![image](https://user-images.githubusercontent.com/8218350/118375702-acf63980-b5c3-11eb-8a94-8a44cf930f09.png)
https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt26-drome/commune26042-26800-beauvallon/recherche-standard/en-triant-par-distance

**Comment by aureliancnx** [comment]
Il me semble que l'on remonte les noms des vaccins en fonction des motives qui ont un rendez-vous disponible au minimum actuellement. Je vois que ce centre n'a que des doses AZ disponibles, et donc on remonte que du AZ.

Si le centre a des rendez-vous Pfizer disponibles, le filtre devrait le trouver

**Comment by Jordan11** [comment]
Le centre a de nouveau du Pfizer de dispo et elles apparaissent normalement. On peut fermer l'issue 
![image](https://user-images.githubusercontent.com/10164916/118652705-25891000-b7e7-11eb-91ef-3a51b46e48aa.png)
