### ISSUE TITLE
Ignorer les espaces pour la complétion de lieu

### ISSUE THREAD

**Issue by tmmorin** [CovidTrackerFr/vitemadose#484]
Les claviers prédictifs des smartphones ont pour effet souvent (toujours?) ajouter un espace après les mot qu'ils devinent.

Quand on saisit un lieu familier proche de chez soit, il est souvent prédit par le clavier prédictif, et quand ce dernier ajoute un espace après le lieu, la complétion intégrée dans Vitemadose (qui ajoute le code postal) ne fonctionne plus.

Ce problème existe à la fois avec l'app et avec le site web.

Peut-être serait il possible de stripper les espaces en début et fin de chaîne avant de passer le nom de lieu au moteur de complétion ?

**Comment by Noezor** [comment]
Hello ! Tu peux poster sur les repos du front ? C'est eux qui ont toute cette logique

https://github.com/CovidTrackerFr/vitemadose-front/
https://github.com/CovidTrackerFr/vitemadose-android
