### ISSUE TITLE
Duplication de centre de vaccination chronodose

### ISSUE THREAD

**Issue by sernitj** [CovidTrackerFr/vitemadose#490]
Bonjour,

J’ai 2 propositions identiques de centre de vaccination en mode chronodose avec le code postal 83000. La seule différence est que l’un propose 21 créneaux et l’autre 18.
Ci dessous un screen:
![852DD78C-062B-4103-B9B3-F609481BF81D](https://user-images.githubusercontent.com/1143767/118533471-6847db00-b748-11eb-819f-ccffcbeda46c.png)

Merci

**Comment by Noezor** [comment]
@grubounet , encore un problème de PID ?

**Comment by grubounet** [comment]
@Noezor assigne moi, je PR mercredi un fix définitif qui est en cours
