### ISSUE TITLE
Centre de vaccination qui apparait 4 fois - 94130 Nogent sur Marne

### ISSUE THREAD

**Issue by tdevlaeminck** [CovidTrackerFr/vitemadose#495]
Bonjour, 

Le centre de vaccination de Nogent sur Marne apparait 4 fois dans les résultats.
Qu'il y a des doses dispos ou non. 

![image](https://user-images.githubusercontent.com/82476476/118649790-32583480-b7e4-11eb-970e-518fbbb28468.png)

![image](https://user-images.githubusercontent.com/82476476/118649659-0b016780-b7e4-11eb-9dea-4da836fcb63a.png)

Thanks

**Comment by grubounet** [comment]
Je m'en charge demain, c'est un bug connu sur plusieurs centres ! @Maijin tu peux m'assigner ?

**Comment by Noezor** [comment]
@grubounet ttttttttttt, fais attention à pas virer les centres qui ont plusieurs PIDs :cold_sweat:

**Comment by tlevillayer** [comment]
Ce problème a été corrigé ou pas encore ? De ce que j'ai vu, les pid sont différents, mais les adresses renseignées sont les mêmes. Peut-être mettre un filtre sur l'unicité de l'adresse pour les centres doctolib ?

**Comment by grubounet** [comment]
Je suis dessus, ca deveait sortir ce soir !!Le 30 mai 2021 21:55, Timothée LEVILLAYER ***@***.***> a écrit :

Ce problème a été corrigé ou pas encore ? De ce que j'ai vu, les pid sont différents, mais les adresses renseignées sont les mêmes. Peut-être mettre un filtre sur l'unicité de l'adresse pour les centres doctolib ?

**Comment by grubounet** [comment]
Fixed by #543 and #547
