### ISSUE TITLE
Issue permanente pour les URLs manuels

### ISSUE THREAD

**Issue by ValentinMouret** [CovidTrackerFr/vitemadose#499]
Si vous avez une proposition d’URL à ajouter à la [liste](https://docs.google.com/spreadsheets/d/e/2PACX-1vQ5Wajauc3wbJbZHogzttxTdOKuvAboKlR5dJ_bYaCX7sa9bxVNaDqeOcDOfvT0O7Yh2IPUDpNLumGC/pubhtml) d’URL scrapés «manuellement», faites le ici

Merci !

**Comment by Maijin** [comment]
Je viens de rajouter un template specifique pour GitHub issue ;)
