### ISSUE TITLE
[Doctolib] Dispo des pharmacies, généralistes et centres de santé

### ISSUE THREAD

**Issue by Toomaaa** [CovidTrackerFr/vitemadose#50]
Quid des pharmacies, généralistes, centre de santé, sur Doctolib ?
Rien qu'une recherche sur Doctolib vers Lille me sort de nombreuses disponibilités, mais tout le temps dans des pharmacies, généralistes ou centres de santé

exemple : https://www.doctolib.fr/vaccination-covid-19/59000-lille?ref_visit_motive_ids[]=6970&ref_visit_motive_ids[]=7005&ref_visit_motive_ids[]=7107

**Comment by aureliancnx** [comment]
Ajouté
