### ISSUE TITLE
Centre de Contes (06390) qui n'apparait pas

### ISSUE THREAD

**Issue by tdevlaeminck** [CovidTrackerFr/vitemadose#504]
**Checklist**

* [x] J'ai réessayé a 15min d'intervalle
* [x] Mon issue contient l'URL du centre manquant
* [x] Mon issue contient l'URL vers le département / code postal Vite Ma Dose

URL complète à insérer ici : https://www.doctolib.fr/centre-de-sante/contes/centre-de-vaccination-de-contes

**Notes**

Le centre ne propose que des rendez-vous par téléphone. 
Non visible sur cette page : https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt06-alpes_maritimes/commune06048-06390-contes/recherche-standard/en-triant-par-distance

**Comment by grubounet** [comment]
@tdevlaeminck le centre ne propose même plus la prise de rdv par tel, donc on ne peut plus faire grand chose
![image](https://user-images.githubusercontent.com/31167642/121497083-5bcb4100-c9db-11eb-9656-b5ff92d6ff23.png)

Je close et on rouvrira si ça change !
