### ISSUE TITLE
Pharmacie en 'Résa tel' tout en étant sur Doctolib

### ISSUE THREAD

**Issue by tdevlaeminck** [CovidTrackerFr/vitemadose#505]
Bonjour, 

**Lieu de vaccination :** Pharmacie Captain Pharma - 242 Avenue Georges Clemenceau, 92000 Nanterre
Sur la [page de résultat](https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt92-hauts_de_seine/commune92050-92000-nanterre/recherche-standard/en-triant-par-distance) VMD nous affichons la mention "Réservation tel uniquement'. 

![image](https://user-images.githubusercontent.com/82476476/118817604-af061400-b8b3-11eb-829c-c92d1a38c01f.png)

Or la pharmacie est présente sur Doctolib : https://www.doctolib.fr/pharmacie/nanterre/pharmacie-sante-service-dr-olivier-berthelemy

![image](https://user-images.githubusercontent.com/82476476/118817579-a6add900-b8b3-11eb-9c5c-086bb057462c.png)

Il me semble que le comportement normal devrait indiquer la mention 0 créneau en grisé sur la page VMD. 
Or la pharmacie nous indique recevoir des centaines d'appels par jour. 

Merci 🙂

**Comment by grubounet** [comment]
Je vais essayer de regarder ce qui génère ce comportement côté front, y a un indicateur qu'on doit pas leur envoyer correctement

**Comment by grubounet** [comment]
@tdevlaeminck t'as mis le doigt sur un DOUBLE problème.

La pharmacie n'existe pas dans nos fichiers Doctolib, mais elle existe sur ... Ordoclic

![image](https://user-images.githubusercontent.com/31167642/118832118-a2d48380-b8c0-11eb-9898-0b2edce1224a.png)

Où elle est bien uniquement réservable par tel. J'ai appelé la pharma, il faut mettre leur Ordoclic dans la blocklist car visiblement ils ne savent même pas pourquoi ils sont sur ordoclic, et je leur ai dit de vérifier leur config Doctolib pour être certains qu'ils étaient bien inscrits en tant que centre de vaccination. Sinon on les ajoutera dans la liste manuelle une fois celle ci en place !

**Comment by grubounet** [comment]
@Bouska oui, et j'ai l'origine du soucis

**Comment by Noezor** [comment]
FIxé avec #513
