### ISSUE TITLE
Blacklister les CIAMT sur Chronodose

### ISSUE THREAD

**Issue by PLhery** [CovidTrackerFr/vitemadose#506]
Suite à une requete du Directeur Général du CIAMT
https://twitter.com/docvinhngo/status/1394990040783245317?s=21

exemple: https://patient.avecmondoc.com/fiche/structure/ciamt-italie-609

Si je ne me trompe pas, ces centres ne sont pas autorisés à administrer des vaccins ARN, malgré la mention de pfizer dans la page de reservation.

De plus, les créneaux s'affichent, mais aucun professionel de santé ne semble disponible pour l'administrer donc il semble impossible de réserver ; peut être qu'un fix du scrapper avecmondoc est préferable.

**Comment by grubounet** [comment]
@gaelbenoit tu peux regarder ? Je crois que dans l'API tu as trouvé un champ pour les professionnels non réservables

**Comment by tdevlaeminck** [comment]
Nous allons mettre en pause le scraper AMD. 
Cf : https://github.com/CovidTrackerFr/vitemadose/pull/507
