### ISSUE TITLE
Centre qui remonte les secondes doses ?

### ISSUE THREAD

**Issue by Noezor** [CovidTrackerFr/vitemadose#512]
![image](https://user-images.githubusercontent.com/8218350/118882148-265b9800-b8f4-11eb-953f-a7bc63916dff.png)
Mais que des 2ndes doses (bcp) sur doctolib 
![image](https://user-images.githubusercontent.com/8218350/118882594-a41fa380-b8f4-11eb-8a65-606340b8b7da.png)

https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt54-meurthe_et_moselle/commune54029-54560-audun_le_roman/recherche-standard/en-triant-par-date

Je me suis dit qu'ils avaient peut être inversé le first_dose_motive, mais cela ne semble pas être le cas.

**Comment by Benvii** [comment]
Hello,
Je me suis planché sur le problème en début de semaine (coup de bol le bug était encore visible).
Le **problème n'est pas lié aux secondes doses** mais au fait que le scraper n'utilise pas les mêmes requêtes d'availabilities que le front web de doctolib, en sommes nous avons en effet étrangement accès a des créneaux qui depuis le front de docolib ne sont pas accessible !

## Delta dans les requêtes availabilities

La requête en question : 

- Via le front doctolib :  https://www.doctolib.fr/availabilities.json?start_date=2021-05-25&visit_motive_ids=2527291-2867873-2868395&agenda_ids=478668&insurance_sector=public&practice_ids=188282&destroy_temporary=true&limit=4
- Celle généré par notre scraper  :  https://partners.doctolib.fr/availabilities.json?start_date=2021-05-24&visit_motive_ids=2868395&agenda_ids=478668&insurance_sector=public&practice_ids=188282&destroy_temporary=true&limit=7

 J'ai comparé les réponse joué un peu avec les query param, étrangement je constate que quand on envoie un seul `visit_motiv_ids` **on obtiens des créneau qui ne remontent pas lorsque ce même motifs est accompagné des autres IDs !**, c'est clairement illogique.

La conséquence on liste des créneau non réservable via le front du doctolib qu'on devrait donc considérer comme inexistants.

## Analyse front doctolib

Je me suis donc plus sérieusement penché sur la manière dont le front du doctolib en fonction de json booking du centre génère les requêtes d'availabilities lorsque qu'on sélectionne un motif. Mon intuition est que le front doctolib regoupe les IDs de motifs par nom, les 3 motifs en question ont exactement le même nom et en effet ça n'aurai aucun sens d'afficher 2 fois le même motif dans le `<select>` puisqu'il serait impossible de différencier les 3.

Pour confirmer cette hypothèse j'ai monté un petit man in the middle et customizé les `visit_motives` du centre (en écrasant le json de booking avant qu'il arrive au front), j'ai effectué les tests suivants : 

- changer le nom d'un des motifs (non dispo dans ce practice_id) : son ID n'est plus concaténé dans la requête d'availability, en phase avec l'hypothèse, aucun impact sur le `<select>`.

- changer le nom du motif `2868395` (seul présent sur ce practice_id) : j'ai uniquement son ID dans la requête d'availability, en phase avec l'hypothèse il est le seul à avoir ce nom, le nom dans le `<select>` à changé

- ajouter 2 visite_motive nouveaux avec un même nom bidon dont l'un d'entre eux dispo sur ce practice_id : je retrouve bien les 2 ids de mes motifs bidon dans la requête, en phase avec l'hypothèse et également mon nouveau motif dans le `<select>`.



Mes tests confirment un peu en reverse engineering que le JS du front de doctolib regroupe les modifs de vaccination par nom, et lorsqu'un motif dispo sur un practice_id envoie la requête d'availability avec l'ensemble des ids des motifs associés à ce nom (y comprend les ids non dispo sur le practice_id en question).


## Adaptation du scraper

Finalement un nom de motifs correspond pour nous dans l'implémentation actuelle du scraper à un  numéro de dose (1ère, 2ème ..) et un vaccin, modélisé par le type `Vaccine`. Nous ne regardons que les 1ère doses, je propose donc dans l'implémentation que j'ai push regrouper les ids des motifs par `Vaccine` et d'envoyer les requêtes d'availability par `Vaccine` avec l'ensemble des ids des motifs. Idéalement il vaudrait mieux se baser sur les noms mais le refacto risque d'être plus lourd.

## Quid de la prise de ces RDV qu'on arrivait à remonter ?

Ce qui m'intrigue c'est de savoir si on peut réellement prendre les RDV qu'on arrivait à voir (à date je n'en vois plus 😥), si vous identifiez un autre centre dans ce cas je suis preneur. Étant donné que je sais comment modifier la config du centre pour faire générer au front de doctolib la requête avec 1 seul motif que je pourrais tenter d'en réserver voir ce que ça donne 🤔... _ça restera peut-être un mystère_

**Comment by Benvii** [comment]
PR : https://github.com/CovidTrackerFr/vitemadose/pull/529

**Comment by DavidLibeau** [comment]
> J'ai comparé les réponse joué un peu avec les query param, étrangement je constate que quand on envoie un seul visit_motiv_ids on obtiens des créneau qui ne remontent pas lorsque ce même motifs est accompagné des autres IDs !, c'est clairement illogique.

Je sais pas si c'est normal et voulu, mais les dates sont différentes dans les deux url précédentes.

**Comment by Benvii** [comment]
@DavidLibeau merci, erreur de ma part ça a bien été testé avec les mêmes dates également j'ai joué sur tous les paramètres
