### ISSUE TITLE
Filtrage par type de vaccin

### ISSUE THREAD

**Issue by ClementGREGOIRE** [CovidTrackerFr/vitemadose#514]
Sur l'appli android (j'ai repéré ce problème uniquement à cet endroit), on peut filtrer par type de vaccin (astra moderna ect..). Mais si un centre propose 2 vaccins différents et que l'on ne sélectionne pas les deux vaccins dans le filtre ce centre disparrait de la liste des centres disponible. 

Soit vous prenez déjà en compte ce problème et dans ce cas ce qu'il manquerait c'est de dire pour quel type de vaccin est diponible de rdv, soit il y a une idée d'ammélioration pour la prochaine MAJ.

Bon courage pour la suite du développement

**Comment by Maijin** [comment]
Potentiellement a remonter du côté Appli android https://github.com/CovidTrackerFr/vitemadose-android :)

**Comment by grubounet** [comment]
Hello, il nous est impossible de remonter (en tout cas pas pour toutes les plateformes) quel est le vaccin associé à chaque type de rdv, c'est pour cela que nous ne donnons pas cette information
