### ISSUE TITLE
Centre manquant : Pôle Santé Travail 59280 Armentières

### ISSUE THREAD

**Issue by tdevlaeminck** [CovidTrackerFr/vitemadose#528]
**Checklist**

* [x] J'ai réessayé a 15min d'intervalle
* [x] Mon issue contient l'URL du centre manquant
* [x] Mon issue contient l'URL vers le département / code postal Vite Ma Dose

URL complète à insérer ici 
Doctolib : https://www.doctolib.fr/centre-de-sante/nord/pst?pid=practice-177831
VMD : https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt59-nord/commune59017-59280-armentieres/recherche-standard/en-triant-par-distance

**Notes : Au moment je rédige cette issue, il n'y a des dispos mi-juin que pour des secondes injections Astrazeneca et Moderna**

**Comment by grubounet** [comment]
Centres non référencés comme centres de vaccination sur doctolib (https://www.doctolib.fr/vaccination-covid-19/armentieres)
Il faut les prévenir et leur dire de contacter Doctolib, sinon on les ajouteras à l'itérateur manuel de @ValentinMouret lorsqu'il sera prêt !

**Comment by tdevlaeminck** [comment]
Merci!
Information remontée au centre.
