### ISSUE TITLE
Filtres de vaccination

### ISSUE THREAD

**Issue by aureliancnx** [CovidTrackerFr/vitemadose#53]
Certaines personnes recherchent plus spécifiquement des créneaux de vaccination en fonction de leur situation (+ de 70 ans, professionnel de santé, personnes avec des comorbidités...)

Un système de filtre devra faire changer le format des fichiers et donc des dates. Chaque plateforme (Keldoc, Doctolib, ...) a sa façon de filtrer les "raisons" du rendez-vous (appelé 'motives').

Actuellement, on fetch uniquement une date au format YYYY-MM-DD HH:MM'T'Z
Cependant, les noms des différents "motives" sont spécifiques à la plateforme et peuvent changer d'un centre de vaccination à un autre.

Par exemple, on retrouve des motives comme : "1ère inj +70 ans", "première injection prof. santé"...

J'ai pensé à renvoyer des informations unifiées : par exemple, "1ère inj +70 ans" pourrait être détecté comme étant dans la catégorie "received_dose: 1", "person_type: 70YO" (exemple tout bête avec un nom pas très travaillé pour l'exemple).
Le problème étant qu'en rajoutant des filtres, on va se heurter à plusieurs questions dont : 

- si on doit filtrer le fait que la personne doit recevoir sa première ou seconde injection, on doit filtrer également AstraZeneca/Pfizer/etc.. ? car certains vaccins pourront nécessiter qu'une dose (exemple J&J) ou peut-être plus ?
- si on doit faire un filtre précis jusqu'au type de vaccin, la prise en main de l'outil ne va-t-elle pas perdre de sa valeur ? (à savoir : trouver une dose en "un clic" [ou presque], vous avez saisi l'idée)
- comment gérer le format? des types et des sous_types? exemple de retour de données (bien sûr, dans le cadre d'une mise en prod, on serait peut-être sur des clés -> valeurs comprises entre le scraper et le front), dans cet exemple la hiérarchie n'est qu'un prototype :

- pfizer/..
    - +70 ans
        - 1ère injection : 2042-01-01 08:00.0000+0200...
        - 2nde injection :  2042-03-01 08:00.0000+0200...
    - professionnel de santé
        - 1ère injection : 2025-01-01 08:00.0000+0200...
        - 2nde injection :  2025-01-28 08:00.0000+0200...
    - comorbidités +50
        - 1ère injection : None
    .....

Ou alors avec des filtres plutôt par liste, sans hiérarchie ? exemple: <code>"2042-01-01 08:00.0000": "["pfizer", "+70", "1st_vaccination"]</code> ?

- il ne faut pas oublier que la 2nde dose est gérée automatiquement par les centres de vaccination dans certains cas (prise de RDV automatique, ou par appel du centre...)
- certains centres de vaccination ont très peu de "motives", qui rassemblent plusieurs cas de figure en un seul : par exemple, "Première injection du vaccin COVID-19" (accessible aux personnes d'un certain âge, aux personnes avec des comorbidités, aux professionnels de santé...)

Le système de filtre ouvre des questions sur la façon de faire, il y en a beaucoup, et ça va demander d'attribuer pas mal de "motives" à des filtres différents. Un petit exemple : 

<img src="https://i.imgur.com/aeROuDs.png" />

Quand par rapport à d'autres, on en a très peu, ou des doublons (mais les doublons se gèrent plutôt facilement) : 

<img src="https://i.imgur.com/E5ZQXQD.png" />

En résume, les centres de vaccination ne semblent pas proposer pas dans leur API des clés de critères précis pour chaque motive et le motive n'est toujours pas le même dans un centre à l'autre (alors qu'ils sont sur la même plateforme..) : par exemple "1ère inj - Vaccination +70 ans - AstraZeneca", "+70 ans - astra - première injection"...

Avez-vous des idées de fonctionnement des filtres pour pouvoir trouver le meilleur compromis ?

**Comment by Zar-rok** [comment]
> si on doit filtrer le fait que la personne doit recevoir sa première ou seconde injection, on doit filtrer également AstraZeneca/Pfizer/etc.. ? car certains vaccins pourront nécessiter qu'une dose (exemple J&J) ou peut-être plus ?

Je pense que ça peut être intéressant d’extrait les _motives_ avec la plus fine granularité possible. Les catégories que je vois, à partir des exemples, sont

- `Dose` (e.g. première, seconde, etc.)
- `Personne` (e.g. +70 ans, pompier+ambulancier, professionnel de santé, etc.)
- `Vaccin` (e.g. Pfizer-Biontech, Moderna, AstraZeneca, etc.)

La plus important des exigences me semble être que l’extraction des valeurs des _motives_ et la logique de filtrage des créneaux permettent de s’adapter à de nouvelles valeurs ou de nouvelles catégories.

> si on doit faire un filtre précis jusqu'au type de vaccin, la prise en main de l'outil ne va-t-elle pas perdre de sa valeur ? (à savoir : trouver une dose en "un clic" [ou presque], vous avez saisi l'idée)

Une fois la sélection par département effectué, une sélection basée sur les _motives_ peut-être proposé pour les entrées affichées. De sorte à ne pas demander d’entrée de jeu de filtrer et sur le département et sur les _motives_. Je pense que cela permettrait de proposer cette fonctionnalité sans pour autant impacter l’ergonomie actuelle.

> il ne faut pas oublier que la 2nde dose est gérée automatiquement par les centres de vaccination dans certains cas (prise de RDV automatique, ou par appel du centre...)

Lors d’un filtrage portant sur une seconde dose, un message d’indication pourrait être affiché pour indiquer à l’utilisateur de consulter le centre de vaccination de sa première injection avant de choisir un créneau. À voir si c’est le rôle de ce logiciel de faire ce type d’indication.

> comment gérer le format? des types et des sous_types?

Si le filtrage est effectué d’abord sur les départements puis sur les _motives_, alors une structure avec comme clef le créneau et comme valeur la liste des _motives_ associés me semble être une approche plus simple à gérer dans l’optique de pouvoir s’adapter à de nouvelles valeurs ou de nouvelles catégories. Cela tant que le nombre de créneau pour un département reste raisonnable.

> En résume, les centres de vaccination ne semblent pas proposer pas dans leur API des clés de critères précis pour chaque motive et le motive n'est toujours pas le même dans un centre à l'autre

Afin de pouvoir chercher comment extraire les _motives_ de manière fiable, je voudrais savoir s’il y a déjà un jeu de données contenant des _motives_ provenant de différent site ?

**Comment by Maijin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Scrape type de Dose (1ere, 2eme)](https://trello.com/c/ReIEMoX5/12-scrape-type-de-dose-1ere-2eme)

**Comment by Maijin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Scrape type de Vaccin](https://trello.com/c/IL4lJzjl/11-scrape-type-de-vaccin)

**Comment by Maijin** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Scrape type de Personnes à vacciner](https://trello.com/c/vi6HvYUY/13-scrape-type-de-personnes-%C3%A0-vacciner)
