### ISSUE TITLE
Retour vers le passé

### ISSUE THREAD

**Issue by rozierguillaume** [CovidTrackerFr/vitemadose#531]
VMD affiche des créneaux qui sont passés 

![Uploading 7379F834-D85C-4EA7-88CC-1C832673E08A.jpeg…]()

**Comment by rozierguillaume** [comment]
![1A1AA7D3-3A44-4A0D-909B-CD92D09B7802](https://user-images.githubusercontent.com/22763678/120153520-1b0b4500-c1ef-11eb-922f-f7742e0bc17f.jpeg)

**Comment by aureliancnx** [comment]
Devrait être corrigé par la #532 et #536
