### ISSUE TITLE
Intégration d'une nouvelle plateforme : Annura

### ISSUE THREAD

**Issue by tdevlaeminck** [CovidTrackerFr/vitemadose#534]
Bonjour, 

La plateforme [Annura](https://www.annura.com) nous contacte afin d'apparaitre sur Vite Ma Dose, 
Après rapide échange, ils peuvent mettre à disposition une API REST. 

**Avez-vous la possibilité de voir la pertinence de cette plateforme ?** 

Si pertinent, il faudrait leur indiquer les éléments dont nous avons besoin ainsi que la cinématique de récupération. 

Merci, 
Bonne journée

**Comment by max5962** [comment]
Pour tous ceux que j'ai pu tester dans l'onglet annuaire ( déjà il y a maxi 10 personnes par régions ) aucun proposait de la vaccination.
ça ressemble plus à de la publicité qu'à un réel intérêt pour la plateforme ( mon avis )
