### ISSUE TITLE
Doctolib : Centres non trouvés 

### ISSUE THREAD

**Issue by rozierguillaume** [CovidTrackerFr/vitemadose#54]
Sur Doctolib, certains centres ne sont pas recensés par le ministère de la santé et ne sont donc pas présents dans le fichier utilisé pour chercher les RDV. 

Est-il possible de faire une requête Doctolib pour trouver tous les centres faisant de la vaccination Covid plutôt que d’utiliser le fichier du ministère de la santé ?

Exemples :
75 :
- Mairie du 18ème
(https://www.doctolib.fr/centre-de-vaccinations-internationales/paris/ars-idf-centre-covisan-cpts-paris-18?highlight%5Bspeciality_ids%5D%5B%5D=5494)
- Le centre COVISAN de la Mairie du 5ème est disponible sur Doctolib
(https://www.doctolib.fr/centre-de-sante/paris/centre-covid19-paris-5?highlight%5Bspeciality_ids%5D%5B%5D=5494)

92 :
- CMS de Bagneux
(https://www.doctolib.fr/centre-de-sante/bagneux/centre-vaccination-covid-19-du-cms-de-bagneux?highlight%5Bspeciality_ids%5D%5B%5D=5494)

**Comment by Toomaaa** [comment]
Hello,
Même sujet que https://github.com/CovidTrackerFr/vitemadose/issues/50 du coup non ?

**Comment by aureliancnx** [comment]
De mon côté toutes les URL que tu as donné n'ont plus de créneaux, est-ce que tu aurais d'autres liens non pris en compte pour que je puisse creuser un peu ?

**Comment by Toomaaa** [comment]
> De mon côté toutes les URL que tu as donné n'ont plus de créneaux, est-ce que tu aurais d'autres liens non pris en compte pour que je puisse creuser un peu ?

@aureliancnx c'est le sujet sur lequel est Sacha, pour récupérer les centres qui sont pas dans le csv de data.gouv
Il y a plein de médecins, pharmaciens, centres de santé, qui sont sur Doctolib mais pas dans le csv du gouvernement.
Fais une recherche par exemple sur Doctolib, département du Nord, tu vas trouver pas mal de dispos sur des médecins ou pharmaciens.

Sacha (@grubounet je crois) est en train de scraper les pages Doctolib département par département pour se faire une base de centres

**Comment by aureliancnx** [comment]
On peut fermer cette issue ? 

Tu en as ouverte une vis-à-vis de ça : https://github.com/CovidTrackerFr/vitemadose/issues/50
