### ISSUE TITLE
Integration Bimedoc

### ISSUE THREAD

**Issue by xemxav** [CovidTrackerFr/vitemadose#542]
Bonjour,

Je suis dev back chez Bimedoc https://www.bimedoc.com/, nous souhaiterions pouvoir intégrer toutes nos pharmacies qui proposent la vaccination dans leur prise de rdv en ligne.

Comment pouvons nous rejoindre le Mattermost pour en discuter ? 

Bien à vous,

**Comment by aureliancnx** [comment]
Bonjour,

Merci de nous proposer d'ajouter votre plateforme à VMD. Vous pouvez nous rejoindre sur Mattermost à l'adresse suivante : https://mattermost.covidtracker.fr/covidtracker/channels/town-square

Cordialement,

**Comment by xemxav** [comment]
> Bonjour,
> 
> Merci de nous proposer d'ajouter votre plateforme à VMD. Vous pouvez nous rejoindre sur Mattermost à l'adresse suivante : https://mattermost.covidtracker.fr/covidtracker/channels/town-square
> 
> Cordialement,

Merci !

**Comment by grubounet** [comment]
Bonjour @xemxav , je vous ai envoyé un message sur le Mattermost, j'ai regardé un peu et il me manque quelques informations pour procéder à votre intégration sur ViteMaDose
