### ISSUE TITLE
Modification numéro téléphone - 95602 Eaubonne

### ISSUE THREAD

**Issue by tdevlaeminck** [CovidTrackerFr/vitemadose#545]
Bonjour,

Un centre de vaccination nous signale un numéro erroné. 
**Centre de vaccination CH Simone Veil Grand public à Eaubonne 95602**
Le bon numéro est le :  01.34.06.67.38

https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt95-val_d_oise/commune95203-95600-eaubonne/recherche-standard/en-triant-par-distance

Je constate que le numéro a été corrigé sur sante.fr (https://www.sante.fr/cf/centres-vaccination-covid/departement-95-val-d'oise.html). Les informations sont-elles censées être mise à jour automatiquement suite aux MAJ sante.fr ? 

Merci

**Comment by grubounet** [comment]
@tdevlaeminck le centre n'apparait plus sur VMD.
En effet, il contient dans le titre "Centre de vaccination COVID-19 - CH Simone Veil (**réservé aux professionnels de santé**)" même si il dispose de motifs "grand public"
Il faudrait peut être réfléchir à une autre manière de traiter les centres ou leur demander de renommmer le centre (d'autant plus qu'ils ont un motif réservé et un grand public) ?

**Comment by grubounet** [comment]
@tdevlaeminck J'ai trouvé le lien doctolib suivant - https://www.doctolib.fr/vaccination-covid-19/eaubonne/ch-simone-veil-vaccination-covid

Peux tu demander au centre de corriger son numéro sur le doctolib suivant ? De mon côté je vais essyaer de comprendre pourquoi il ne sort pas lors du scrape

**Comment by grubounet** [comment]
@tdevlaeminck Il faut demander au centre de modifier le numéro sur https://www.doctolib.fr/vaccination-covid-19/eaubonne/ch-simone-veil-vaccination-covid

J'ai essayé de les joindre pour leur demander de faire la modification mais ils sont difficiles à joindre, tu as peut être un autre moyen de les contacter ?

**Comment by grubounet** [comment]
Je viens de voir avec le responsable du centre, il souhaite laisser le numéro actuel pour éviter un débordement de la ligne dédiée du centre. 

Je close
