### ISSUE TITLE
Liens vers Doctolib sont casses

### ISSUE THREAD

**Issue by popsy-dev** [CovidTrackerFr/vitemadose#55]
Hello a toute l'equipe :)

Quand je clique sur des liens doctolib, le lien est casse.

<img width="1155" alt="Captura de Tela 2021-04-05 às 10 58 04 AM" src="https://user-images.githubusercontent.com/36266136/113546816-cdfb6000-95fd-11eb-8602-95bf09762b3a.png">

Quelques exemples:

1/ https://www.doctolib.fr/centre-de-sante/saint-denis/centre-de-vaccination-covid-19-stade-de-France

Le lien est casse. On finit sur: https://www.doctolib.fr/#

2/

<img width="406" alt="Captura de Tela 2021-04-05 às 10 59 53 AM" src="https://user-images.githubusercontent.com/36266136/113546946-0e5ade00-95fe-11eb-8854-41bac161ca9d.png">

Il n'y a pas de lien pour ce centre

3/ https://partners.doctolib.fr/hopital-public/paris/centres-de-vaccination-covid-19-ap-hp-hors-professionnels-de-sante?speciality_id=5494&enable_cookies_consent=1

Page n'existe plus

4/

<img width="365" alt="Captura de Tela 2021-04-05 às 11 02 05 AM" src="https://user-images.githubusercontent.com/36266136/113547128-5da10e80-95fe-11eb-913f-c502da9b3fb1.png">

On finit sur ce lien

https://covidtracker.fr/vitemadose/rdvvaccinationcovid.lmr@aphp.fr

Pour certains centres qui sont pas sur des plateformes, on retombe sur la page d'accueil de vite ma dose. Peut etre que l'on a pas interet a les montrer.

5/ 
Pour les centres reserves aux professionels de sante, on se retrouve bloque. On ne peut pas prendre rendez vous et si on est professionel de sante on ne peut pas l'indiquer pour prendre rendez vous j'ai l'impression.

<img width="1329" alt="Captura de Tela 2021-04-05 às 11 04 28 AM" src="https://user-images.githubusercontent.com/36266136/113547316-b2448980-95fe-11eb-8a91-dc31868e2696.png">

Merci!

Jean-Marie

**Comment by loicsimon** [comment]
Bonjour,

L'URL Doctolib provenant du dataset data.gouv.fr contient une majuscule à "France" : https://www.doctolib.fr/centre-de-sante/saint-denis/centre-de-vaccination-covid-19-stade-de-France

Or, l'URL correcte ne contient pas cette majuscule : https://www.doctolib.fr/centre-de-sante/saint-denis/centre-de-vaccination-covid-19-stade-de-france

Lorsque l'URL https://www.doctolib.fr est transformée en https://partners.doctolib.fr, la méthode `.lower()` est appliquée : https://github.com/CovidTrackerFr/vitemadose/blob/2f3b6a29e1c1bb0bba598f9dc7a6f148caa98e67/scraper/doctolib.py#L99

Est-ce que toutes les URL Doctolib doivent être normalisées en minuscule?

Espérant que ça vous aide un peu. Merci pour votre super initiative !

Loïc
