### ISSUE TITLE
Cache data.gouv.fr

### ISSUE THREAD

**Issue by aureliancnx** [CovidTrackerFr/vitemadose#557]
Suite à de nombreux problèmes avec les données de data.gouv.fr, il faudrait que l'on puisse mettre en cache les datasets que l'on télécharge. En cas de problème pour accéder au dataset, on pourrait fallback avec le dernier qu'on a pu récupérer en cache

**Comment by grubounet** [comment]
Inutile suite à suppression de l'utilisation du fichier
