### ISSUE TITLE
Centre qui affiche 0 créneaux - CPTS Sud Lochois

### ISSUE THREAD

**Issue by tdevlaeminck** [CovidTrackerFr/vitemadose#558]
Bonjour, 

Sur VMD nous affichons 0 créneaux pour le CPTS Sud Lochois

![image](https://user-images.githubusercontent.com/82476476/122371586-46689080-cf60-11eb-8f04-f6987a6a9068.png)

Cependant il y a bien des créneaux proposés sur Doctolib pour les prochains jours. 

Je constate que sur Doctolib il faut choisir une "Catégorie de motif" avant de choisir un "motif de consultation". J'ai l'impression que le problème peut venir de là. 

![image](https://user-images.githubusercontent.com/82476476/122371347-17eab580-cf60-11eb-820d-b058f507ad80.png)

Lien VMD : https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt37-indre_et_loire/commune37132-37600-loches/recherche-standard/en-triant-par-distance
Lien Doctolib : https://www.doctolib.fr/vaccination-covid-19/loches/centre-de-vaccination-covid-cpts-sud-lochois

Merci par avance,
Thomas

**Comment by grubounet** [comment]
C'est corrigé :)
