### ISSUE TITLE
Suppression d'un centre - Combs-la-ville

### ISSUE THREAD

**Issue by tdevlaeminck** [CovidTrackerFr/vitemadose#559]
Bonjour, 

La pharmacie de Combs à Combs-la-Ville souhaite ne plus apparaitre sur Vite Ma Dose,

![image](https://user-images.githubusercontent.com/82476476/122373545-dbb85480-cf61-11eb-97f3-51402d1a6f78.png)

Pouvez-vous la retirer please ? 
Merci

**Comment by grubounet** [comment]
C'est fait, j'attends le prochain scrape et je close.
