### ISSUE TITLE
Intégration plateforme Valwin

### ISSUE THREAD

**Issue by tdevlaeminck** [CovidTrackerFr/vitemadose#582]
Bonjour, 

La société Valwin propose un module de prise de rendez-vous pour les pharmacies, 
Voici un exemple : https://pharmacie-du-rond-point-orleans.epharmacie.pro/animation-details/be6c293a-e0a6-49ea-bdb4-31a779bde277/1/60

Les rendez-vous peuvent être récupérés via les endpoints suivants : 
<html><body>
<div><br></div><div><b><a href="https://pharma-api.epharmacie.pro/global/api/meetings/v2/pharmacies-with-vaccines" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://pharma-api.epharmacie.pro/global/api/meetings/v2/pharmacies-with-vaccines&amp;source=gmail&amp;ust=1625121673588000&amp;usg=AFQjCNErJWbTgUpvKgTPlIJ9R5k5x4_UPw">https://pharma-api.epharmacie.<wbr>pro/global/api/meetings/v2/<wbr>pharmacies-with-vaccines</a></b></div><div>Cet
 endpoint permet de récupérer la liste des pharmacies en mesure de 
proposer la vaccination. Pour chaque pharmacie, nous obtenons un objet 
JSON au format suivant :</div><div><br></div><div>{<br>    "id": "giro26-rondpoint",<br>    "name": "Pharmacie du Rond-Point",<br>    "address": {<br>      "city": "Orléans",<br>      "zipCode": "45100",<br>      "service": null,<br>      "street2": null,<br>      "mention": null,<br>      "street": "16 Avenue de la Bolière"<br>    },<br>    "websiteUrl": "<a href="https://pharmacie-du-rond-point-orleans.giropharm.fr" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://pharmacie-du-rond-point-orleans.giropharm.fr&amp;source=gmail&amp;ust=1625121673588000&amp;usg=AFQjCNH2fLvdmdvNTf3FVRkOgcke2-ywoA">https://pharmacie-du-rond-<wbr>point-orleans.giropharm.fr</a>",<br>    "hasAvailableSlot": true,<br>    "nextAvailableSlot": "2021-06-16T15:20:00",<br>    "linkToAllSlots": "<a href="https://pharma-api.epharmacie.pro/global/api/meetings/v2/giro26-rondpoint/slots" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://pharma-api.epharmacie.pro/global/api/meetings/v2/giro26-rondpoint/slots&amp;source=gmail&amp;ust=1625121673588000&amp;usg=AFQjCNEiU1PbXhLm4BDgV0ky3wjHp38UCQ">https://pharma-api.<wbr>epharmacie.pro/global/api/<wbr>meetings/v2/giro26-rondpoint/<wbr>slots</a>",<br>    "geoTag": {<br>      "latitude": 47.84133,<br>      "longitude": 1.9326591<br>    }<br>  }</div><div><br></div><div>Les champs ont les significations suivantes :</div><div><ul><li>id: ID interne du site chez nous</li><li>name : Nom public de la pharmacie</li><li>address: Adresse postale de la pharmacie</li><li>websiteUrl : site à destination des patients, sur lesquels ils peuvent prendre RDV</li><li>hasAvailableSlot : Si vrai, un ou plusieurs créneaux de vaccination sont disponibles</li><li>nextAvailableSlot : Date du prochain RDV disponible, indépendamment du type de vaccin</li><li>linkToAllSlots : Point d’API dédié permettant de récupérer tous les créneaux de vaccination pour cette pharmacie</li><li>geoTag : Coordonnées GPS de la pharmacie</li></ul><div><br></div><div>En interrogeant linkToAllSlots vous pouvez récupérer tous les créneaux disponibles dans la pharmacie. Par exemple <br></div><div><b><a href="https://pharma-api.epharmacie.pro/global/api/meetings/v2/ph25-parolini/slots" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://pharma-api.epharmacie.pro/global/api/meetings/v2/ph25-parolini/slots&amp;source=gmail&amp;ust=1625121673588000&amp;usg=AFQjCNHZ3aOVvzjvGW2khpf5lLBd73xXPQ">https://pharma-api.epharmacie.<wbr>pro/global/api/meetings/v2/<wbr>ph25-parolini/slots</a></b></div><div><b><br></b></div><div>retourne un payload au format suivant :</div><div>{<br>  "links": {<br>    "next": null,<br>    "total": 1,<br>    "prev": null,<br>    "pageSize": 60,<br>    "currentPage": 1,<br>    "nbPages": 1<br>  },<br>  "result": [<br>    {<br>      "start": "2021-06-25T14:30:00",<br>      "end": "2021-06-25T19:00:00",<br>      "timeDivisionId": "c0e27f66-cc0b-337d-8bea-<wbr>3cbb17403ba0",<br>      "meetingConfigurationId": "bdd1c13b-2774-46c8-bbeb-<wbr>a7a5957d3715",<br>      "title": "vaccination covid",<br>      "types": [<br>        {<br>          "id": "a77026ad-050d-4885-97db-<wbr>1939ff32cce7",<br>          "isSocialSecurityRefund": true,<br>          "label": "Vaccin COVID-19 - Moderna",<br>          "image": "<a href="https://d20fhuz7ayclct.cloudfront.net/meetingTypesV2/Vaccination.jpg" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://d20fhuz7ayclct.cloudfront.net/meetingTypesV2/Vaccination.jpg&amp;source=gmail&amp;ust=1625121673588000&amp;usg=AFQjCNFR-J_klAh2Ko-PRZb26pZ6sKsIcA">https://d20fhuz7ayclct.<wbr>cloudfront.net/meetingTypesV2/<wbr>Vaccination.jpg</a>"<br>        }<br>      ],<br>      "websiteUrl": "<a href="https://pharmacie-francoise-parolini.com" target="_blank" data-saferedirecturl="https://www.google.com/url?q=https://pharmacie-francoise-parolini.com&amp;source=gmail&amp;ust=1625121673588000&amp;usg=AFQjCNH59alSDUqD03xS1RkQQvZotDlfeA">https://pharmacie-francoise-<wbr>parolini.com</a>",<br>      "pharmacyName": "Pharmacie Parolini"<br>    }<br>  ]<br>}</div><div><br></div><div>L’objet links permet de naviguer dans l’éventuelle pagination.</div><div>Le tableau result expose les créneaux, avec en particulier : <br></div><div><ul><li>start : date du RDV</li><li>types[0].id : type du RDV</li><li>types[0].label : Nom du RDV</li><li>websiteUrl et pharmacyName permette de retrouver des informations de base sur la pharmacie.<br></li></ul><div>Les quatre types de RDV possibles sont :</div></div><div><span>

Type | Nom | Vaccin
-- | -- | --
be6c293a-e0a6-49ea-bdb4-31a779bde277 | Vaccin COVID-19 | AstraZeneca
c5d223c2-9e26-413a-bcc9-886c1bdbb19f | Vaccin COVID-19 - AstraZeneca | AstraZeneca
765bf5cc-cfeb-4c0f-8962-a4f813c66453 | Vaccin COVID-19 - Janssen | Janssen
a77026ad-050d-4885-97db-1939ff32cce7 | Vaccin COVID-19 - Moderna | Moderna
480d389d-f02d-4cfc-b242-9a108ef134d7 | Vaccin COVID-19 - Pfizer | Pfizer

</span></div><div><br></div><div>Il y a deux types pour AstraZeneca pour des raisons de rétrocompatibilité de notre côté.</div></div>
</body>
</html>

Le vaccin Pfizer est listé dans le cas où il serait autorisé un jour en pharmacie. 

**Avez-vous besoin d'autres informations pour intégrer cette plateforme ?**

**Comment by grubounet** [comment]
Je m'en occupe !

**Comment by grubounet** [comment]
Je te dis ca dans la journée pour ce qui pourrait manquer

**Comment by aureliancnx** [comment]
Hello,

Il semblerait qu'on ait déjà une issue ouverte pour l'ajout de la même plateforme : https://github.com/CovidTrackerFr/vitemadose/issues/471
