### ISSUE TITLE
Filtres de recherche

### ISSUE THREAD

**Issue by JulesMichael** [CovidTrackerFr/vitemadose#594]
Pendant mon utilisation du site, je me suis dit qu'il serait intéressant de pouvoir spécifier si on est intéressé par un vaccin en particulier.
En réfléchissant un peu plus je me suis dit qu'un système de filtres pourrais être une plus value même si il y en a déjà deux (au plus proche, au plus vite)

Exemple de filtres supplémentaires: 
- Un rayon particulier dans lequel trouver des centres
- Choix d'un ou plusieurs vaccins (AstraZeneca, Janssen, Moderna, etc...)
- Des créneaux horaires particuliers (ex: un jeudi entre 13h30 et 17h)
- Choix de l'entité qui nous vaccine (ex: Docteur/pharmacie/autre)

Cependant en implémentant certains filtres peut être que dans une certaine mesure on «ralentirait » la campagne de vaccination. J'attends vos retours avec impatience ✨

EDIT:

Après recherches sur le GitHub, j’ai cru comprendre que le filtre de rayon de recherche a déjà été implanté, et qu’un système « type de vaccin » aussi. Le filtre concernant les horaires aussi.

CF issues/PR [#143-front](https://github.com/CovidTrackerFr/vitemadose-front/pull/143), [#233-front](https://github.com/CovidTrackerFr/vitemadose-front/pull/233) #519

Pouvoir filtrer le type d’entité serait-il intéressant ? 

J'espère ne pas avoir fait question doublon.

JM

**Comment by grubounet** [comment]
Bonjour, une bonne partie de ces filtres est en cours d'implantation ! :)
