### ISSUE TITLE
Centre de Santé "Les Cévennes" - 07

### ISSUE THREAD

**Issue by tdevlaeminck** [CovidTrackerFr/vitemadose#617]
**Checklist**

* [X] J'ai réessayé a 15min d'intervalle
* [X] Mon issue contient l'URL du centre manquant
* [X] Mon issue contient l'URL vers le département / code postal Vite Ma Dose

URL complète à insérer ici
VMD : https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt07-ardeche/commune07010-07100-annonay/recherche-standard/en-triant-par-distance
Doctolib : https://www.doctolib.fr/cabinet-pluridisciplinaire/annonay/maison-de-sante-des-cevennes?pid=practice-192790

**Notes**
Créneaux dispos à partir du 6 août.

**Comment by grubounet** [comment]
#634 devrait régler le soucis
