### ISSUE TITLE
Centre en doublon - 86300

### ISSUE THREAD

**Issue by tdevlaeminck** [CovidTrackerFr/vitemadose#621]
Bonjour, 

Le centre de vaccination du SDIS 86 à Chauvigny est en doublon, 
Url concernée : https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt86-vienne/commune86070-86300-chauvigny/recherche-standard/en-triant-par-distance

Capture : 
![image](https://user-images.githubusercontent.com/82476476/127443862-0e16506a-d269-47d3-b47c-e07cf20324e4.png)

Merci par avance,

**Comment by grubounet** [comment]
Le centre existe 2 fois avec 2 urls différentes pour les même lieux ..
https://www.doctolib.fr/vaccination-covid-19/chauvigny/centre-de-vaccination-covid-19-sdis-86
https://www.doctolib.fr/vaccination-covid-19/buxerolles/centre-de-vaccination-covid-19-sdis-86-buxerolles

Il faut contacter le centre pour leur faire part de leur mauvasie configuration
