### ISSUE TITLE
Centre manquant : 89100 Sens

### ISSUE THREAD

**Issue by chabrulat** [CovidTrackerFr/vitemadose#630]
Bonjour,

Le centre de Sens n'apparaît plus :
* https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt89-yonne/commune89387-89100-sens/recherche-standard/en-triant-par-distance
* https://www.keldoc.com/centre-hospitalier/sens-89100/centre-hospitalier-de-sens?category=-1&cabinet=16565&specialty=153

Cordialement,

**Comment by grubounet** [comment]
C'est fix !

**Comment by chabrulat** [comment]
Merci et bonne journée,
