### ISSUE TITLE
MG Bryan Horn - 44600 Saint Nazaire

### ISSUE THREAD

**Issue by tdevlaeminck** [CovidTrackerFr/vitemadose#638]
**Checklist**

* [X] J'ai réessayé a 15min d'intervalle
* [X] Mon issue contient l'URL du centre manquant
* [X] Mon issue contient l'URL vers le département / code postal Vite Ma Dose

URL complète à insérer ici
Doctolib : https://www.doctolib.fr/medecin-generaliste/saint-nazaire/bryan-horn
VMD : https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt44-loire_atlantique/commune44184-44600-saint_nazaire/recherche-standard/en-triant-par-distance

**Notes**
Ce lundi 16 août il y a des dispos pour le lundi 23 août.

**Comment by grubounet** [comment]
Bonjour, le centre n'est pas sur https://doctolib.fr/vaccination-covid-19/saint-nazaire.json
Il faut dire au médecin de contacter Doctolib pour leur demander pourquoi il n'apparait pas en tant que centre de vaccination !
