### ISSUE TITLE
Pharmacie des Béalières - 38240 Meylan

### ISSUE THREAD

**Issue by tdevlaeminck** [CovidTrackerFr/vitemadose#639]
**Checklist**

* [X] J'ai réessayé a 15min d'intervalle
* [X] Mon issue contient l'URL du centre manquant
* [X] Mon issue contient l'URL vers le département / code postal Vite Ma Dose

URL complète à insérer ici
Maiia : https://www.maiia.com/pharmacie/38240-meylan/pharmacie-des-bealieres
VMD : https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt38-isere/commune38229-38240-meylan/recherche-standard/en-triant-par-distance

**Notes**
Ce jour, créneaux disponibles mercredi 18 août.

**Comment by grubounet** [comment]
Fixed in #643

**Comment by grubounet** [comment]
Un
