### ISSUE TITLE
Pharmacie Couchouron - 22820 Plougrescant

### ISSUE THREAD

**Issue by tdevlaeminck** [CovidTrackerFr/vitemadose#640]
**Checklist**

* [X] J'ai réessayé a 15min d'intervalle
* [X] Mon issue contient l'URL du centre manquant
* [X] Mon issue contient l'URL vers le département / code postal Vite Ma Dose

URL complète à insérer ici
Maiia : https://www.maiia.com/pharmacie/22820-plougrescant/pharmacie-couchouron
VMD : https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt22-cotes_d_armor/commune22218-22820-plougrescant/recherche-standard/en-triant-par-distance

**Notes**
Ce jour, créneaux dispos mercredi 18 août.

**Comment by grubounet** [comment]
Fixed with 643
