### ISSUE TITLE
Centre manquant - 82500 Beaumont de Lomagne

### ISSUE THREAD

**Issue by tdevlaeminck** [CovidTrackerFr/vitemadose#647]
**Checklist**

* [X] J'ai réessayé a 15min d'intervalle
* [X] Mon issue contient l'URL du centre manquant
* [X] Mon issue contient l'URL vers le département / code postal Vite Ma Dose

URL complète à insérer ici
Maiia : https://www.maiia.com/centre-de-vaccination/82500-beaumont-de-lomagne-/centre-de-vaccination---maison-de-sante-des-halles
VMD : https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt82-tarn_et_garonne/commune82013-82500-beaumont_de_lomagne/recherche-standard/en-triant-par-distance

**Notes**
Dispos actuellement pour les 25, 26 et 29 août.

**Comment by rozierguillaume** [comment]
@grubounet est-ce que tu aurais un moment pour regarder, j'ai été relancé par un responsable ?

**Comment by grubounet** [comment]
#677 should fix

**Comment by chrisvernet** [comment]
Bonsoir et merci d'avoir résolu notre absence de référencement.
Un petit problème susbiste sur les dispos des 5-11 ans. Nous avons ouvert avant-hier 2X10 créneaux (24 et 25 janvier après-midi) et lorsque l'on se rend sur :

https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt82-tarn_et_garonne/commune82013-82500-beaumont_de_lomagne/recherche-dose_1_enfants/en-triant-par-distance

Il n'y a rien. Encore merci et chapeau pour votre travail remarquable !
