### ISSUE TITLE
Centres qui remontent sans créneaux

### ISSUE THREAD

**Issue by DjMomo** [CovidTrackerFr/vitemadose#650]
Bonjour,

Les Centres de Vaccination Covid-19 du Tarn remontent systématiquement tous sans créneau disponible alors qu'il y en a réellement.

Les URLS des centres concernés : 
- https://www.doctolib.fr/vaccination-covid-19/tarn/chic-castres-mazamet-centre-de-vaccination?pid=practice-164002
- https://www.doctolib.fr/vaccination-covid-19/tarn/chic-castres-mazamet-centre-de-vaccination?pid=practice-164141
- https://www.doctolib.fr/vaccination-covid-19/tarn/chic-castres-mazamet-centre-de-vaccination?pid=practice-164139
- https://www.doctolib.fr/vaccination-covid-19/tarn/chic-castres-mazamet-centre-de-vaccination?pid=practice-164318
- https://www.doctolib.fr/vaccination-covid-19/tarn/chic-castres-mazamet-centre-de-vaccination?pid=practice-165330
- https://www.doctolib.fr/vaccination-covid-19/tarn/chic-castres-mazamet-centre-de-vaccination?pid=practice-164315

URL VMD : https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt81-tarn/recherche-standard

Point commun de tous ces centres : il y a un nouveau champ "catégorie de motif" (= "scolaire" ou "vaccination") à saisir avant de choisir le motif de consultation, dans Doctolib.

**Comment by grubounet** [comment]
Merci, c'est ce champ qui doit bloquer, je vais le rajouter dans la config
