### ISSUE TITLE
Amélioration de la recherche de 3ème dose

### ISSUE THREAD

**Issue by nhumblot** [CovidTrackerFr/vitemadose#653]
Message de @rozierguillaume

> Ça pourrait être super cool d’avoir en front la possibilité de filtrer uniquement les doses de rappel afin de pouvoir accéder aux disponibilités (par jour) uniquement pour cette dose de rappel. 
>
> Concrètement au niveau du back il faudrait pouvoir obtenir pour chaque département la liste des centres ayant des disponibilités de dose de rappel, et par journée (donc exactement ce qu’on fait pour la 1ère rose, mais pour la 3e).

**Comment by grubounet** [comment]
On it !

**Comment by grubounet** [comment]
C'est bon pour toutes les plateformes sauf bimedoc et avecmondoc !
