### ISSUE TITLE
Mauvais motif Maiia

### ISSUE THREAD

**Issue by fcamblor** [CovidTrackerFr/vitemadose#658]
Il semble que des centres Maiia avec mauvais motifs soient retournés sur VMD.

Par exemple avec cette recherche actuellement : 
https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt31-haute_garonne/commune31149-31770-colomiers/recherche-standard/en-triant-par-distance
![Vaccination_COVID-19_à_Colomiers_31770](https://user-images.githubusercontent.com/603815/143619561-26c4822d-36c2-4bd1-92f8-140b713c6bbc.png)

=> On arrive sur une page Maiia avec comme motif pré-sélectionné "Dépistage COVID-19 test antigénique (prélèvement naso-pharyngé)"
![Pharmacie_des_Ramassiers_à_31770__Colomiers_-_Maiia](https://user-images.githubusercontent.com/603815/143619720-024a8fe2-25c0-4a18-9233-58d84afca2cc.png)

J'imagine que c'est à cause du mot-clef "COVID-19" : il faudrait peut-être rajouter "test" et/ou "antigénique" dans les exclusions si ce n'est pas déjà le cas.

**Comment by grubounet** [comment]
Yess je m'en occupe actuellement

**Comment by grubounet** [comment]
Fixed !
