### ISSUE TITLE
Centres manquant Hôpitaux de Sarreguemines

### ISSUE THREAD

**Issue by sysadminstory** [CovidTrackerFr/vitemadose#664]
**Checklist**

* [X] J'ai réessayé a 15min d'intervalle
* [X] Mon issue contient l'URL du centre manquant
* [X] Mon issue contient l'URL vers le département / code postal Vite Ma Dose

https://www.doctolib.fr/hopital-public/sarreguemines/ch-de-sarreguemines?highlight%5Bspeciality_ids%5D%5B%5D=5494&pid=practice-173166

https://www.doctolib.fr/hopital-public/sarreguemines/ch-de-sarreguemines?highlight%5Bspeciality_ids%5D%5B%5D=5494&pid=practice-169290

**Notes**

Les deux centres de vaccinations des Hôpitaux de Sarreguemines (situés dans la ville de 57200 Sarreguemines et de 57230 Bitche) sont présent sur la carte :
https://vitemadose.covidtracker.fr/centres

Par contre, ces deux centres ne sont pas présent sur les pages :
https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt57-moselle/commune57631-57200-sarreguemines/recherche-dose_rappel/en-triant-par-distance
https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt57-moselle/commune57089-57230-bitche/recherche-dose_rappel/en-triant-par-distance

Pour l'instant, aucun créneau n'est disponible, mais ces deux centres ne sont pas présent, y compris dans la liste des centres sans créneaux disponibles.

De plus, ces centres ne sont pas mentionnés dans le JSON des centres de Moselle :
https://vitemadose.gitlab.io/vitemadose/57.json

Ces deux centres sont accessibles par le lien Doctolib sur la page suivantes :
https://www.hopitaux-sarreguemines.fr/VACCINATION-ANTI-COVID/1/1/53
Celui ci mène à :
https://www.doctolib.fr/hopital-public/sarreguemines/ch-de-sarreguemines?pid=practice-163220

Ces centres sont accessibles également depuis la recherche de Doctolib :
https://www.doctolib.fr/hopital-public/sarreguemines/ch-de-sarreguemines?highlight%5Bspeciality_ids%5D%5B%5D=5494&pid=practice-173166

https://www.doctolib.fr/hopital-public/sarreguemines/ch-de-sarreguemines?highlight%5Bspeciality_ids%5D%5B%5D=5494&pid=practice-169290

**Comment by grubounet** [comment]
Du coup @sysadminstory j'ai enfin eu le temps de regarder. Le centre est mal configuré, les motifs sont des champs personnalisés et non des motifs de vaccination Doctolib ce qui fait que le champ "ref_visit_motive_id" dans l'api des motifs doctolib est à "null", or, c'est ce champ qui sert à filtrer. Il faudrait contacter le centre pour leur dire, @tdevlaeminck peux tu t'en charger stp ?
