### ISSUE TITLE
 Centre manquants ville de laval

### ISSUE THREAD

**Issue by mathis-kdio** [CovidTrackerFr/vitemadose#675]
**Checklist**

* [x] J'ai réessayé à 15 min d'intervalle
* [x] Mon issue contient l'URL du centre manquant
* [x] Mon issue contient l'URL vers le département / code postal Vite Ma Dose

URL Doctolib https://www.doctolib.fr/vaccination-covid-19/mayenne/pole-de-sante-de-mayenne-centre-de-vaccination?pid=practice-164879
URL VMD https://vitemadose.covidtracker.fr/centres-vaccination-covid-dpt53-mayenne/commune53130-53000-laval/recherche-dose_rappel/en-triant-par-distance

**Notes**
Seul le centre de vaccination de Laval dans le département de la Mayenne est manquant parmi les autres sur Doctolib.

**Comment by Bouska** [comment]
Alors le centre a l'air d'être revenu (premier centre dans la liste VMD) sans qu'il y ait eu de changements dans le code, sûrement un glitch.

**Comment by nhumblot** [comment]
Le centre est disponible en ce moment sur VMD: 
![image](https://user-images.githubusercontent.com/15015617/149818877-79bc9659-f7cb-4a7f-93ec-dafd2635b3fc.png)

@grubounet, est-il possible de clôturer ce ticket ? Je n'ai pas les droits pour le faire. :slightly_smiling_face:
