### ISSUE TITLE
Vaccinodrome Lille manquant

### ISSUE THREAD

**Issue by rozierguillaume** [CovidTrackerFr/vitemadose#676]
**Checklist**

* [x] J'ai réessayé a 15min d'intervalle
* [x] Mon issue contient l'URL du centre manquant
* [ ] Mon issue contient l'URL vers le département / code postal Vite Ma Dose

URL Centre : https://www.doctolib.fr/vaccination-covid-19/lille/centre-de-vaccination-covid-19-boulevard-de-metz?highlight%5Bspeciality_ids%5D%5B%5D=5494

**Notes**

Bonjour Mr Rozier,
Nous gérons avec mon collègue un vaccinodrome depuis milieu de semaine dernière. Nous sommes dans une capacité de 600 rdv journaliers 5j/7 et nous nous apercevons que nous n'apparaissons pas sur Vite ma dose. Sauriez vous pourquoi ?
Nous avons vérifié, nous apparaissons bien sur Doctolib.

Merci d'avance de votre réponse & bon WE à vous.

**Comment by grubounet** [comment]
Je regarde ca ajd !
