### ISSUE TITLE
[AvecMonDoc] Rang d'injection non récupéré

### ISSUE THREAD

**Issue by gaelbenoit** [CovidTrackerFr/vitemadose#678]
Le rang d'injection n'est pas implémenté dans le scraper AvecMonDoc, ce qui fait que tous les créneaux remontent en 'unknown_dose'
Du coup les filtres de recherche affichent les centres AvecMonDoc comme n'ayant aucun créneau

![image](https://user-images.githubusercontent.com/11502741/149492441-f9148234-9ac8-4a62-a000-516bd72d423d.png)

Il faut donc implémenter la détection du rang d'injection pour ce scraper

**Comment by nhumblot** [comment]
Le problème se situe dans `scraper/avecmondoc/avecmondoc.py`.

```python
self.found_creneau(
    Creneau(
        horaire=parse(slot["businessHours"]["start"]),
        reservation_url=request.url,
        type_vaccin=[vaccine],
        lieu=self.lieu,
    )
)
```

Le paramètre `dose` n'est pas alimenté. Je n'observe pas d'information en retour de l'api (https://api.avecmondoc.com/api/BusinessHours/availabilitiesPerDay) indiquant de quel type de créneau il s'agit. Faut-il le considérer comme un créneau de n'importe quel type ?
