### ISSUE TITLE
Centre manquant à Saint Caprais (33)

### ISSUE THREAD

**Issue by fcamblor** [CovidTrackerFr/vitemadose#680]
**Checklist**

* [X] J'ai réessayé a 15min d'intervalle
* [X] Mon issue contient l'URL du centre manquant
* [ ] Mon issue contient l'URL vers le département / code postal Vite Ma Dose

Centre manquant : https://www.doctolib.fr/maison-de-sante/saint-caprais-de-bordeaux/centre-de-sante-saint-caprais

Le centre ne ressort pas dans la liste des centres disponibles/indisponibles dans le `33.json`

**Notes**

Remonté via twitter : https://twitter.com/Dr_Boree/status/1482442005150150656

**Comment by Bouska** [comment]
Je suis en train de regarder. Ca a l'air d'être assez pointu comme problème, parce que le centre apparaît bien quand on scrape tous les centres.

**Comment by Bouska** [comment]
Etrange : autant la MR #681 a corrigé #676, autant ce centre n'apparaît toujours pas dans les centres (alors qu'en local les deux avaient le même problème). Il faut que je m'y repenche.

**Comment by fcamblor** [comment]
Il ne faudrait pas re-open l'issue du coup ? _(je ne suis pas collaborator sur le projet, je ne peux le faire moi-même)_

**Comment by nhumblot** [comment]
Pour obtenir la liste des centres par département, on effectue, dans le cas de la Gironde, une itération sur `https://partners.doctolib.fr/vaccination-covid-19/departement-gironde.json?page={1}`, le centre https://www.doctolib.fr/maison-de-sante/saint-caprais-de-bordeaux/centre-de-sante-saint-caprais ne semble pas ressortir via cette api. En conséquence, il n'est pas écrit dans le fichier json des centres Doctolib et n'est référencé dans Vite Ma Dose.

**Comment by Bouska** [comment]
> Pour obtenir la liste des centres par département, on effectue, dans le cas de la Gironde, une itération sur `https://partners.doctolib.fr/vaccination-covid-19/departement-gironde.json?page={1}`, le centre https://www.doctolib.fr/maison-de-sante/saint-caprais-de-bordeaux/centre-de-sante-saint-caprais ne semble pas ressortir via cette api. En conséquence, il n'est pas écrit dans le fichier json des centres Doctolib et n'est référencé dans Vite Ma Dose.

Le centre est bien présent, juste bien caché au bout de la liste à la page 23 https://partners.doctolib.fr/vaccination-covid-19/departement-gironde.json?page=23 (3ème de cette page) [quand j'ai cherché il y une semaine, le centre était plutôt à la page 14, donc c'est possible que la page ne soit plus bonne à un moment donné)

**Comment by nhumblot** [comment]
Je viens de relancer mon script de collecte à l'instant et je l'ai bien trouvé cette fois. Désolé. :thinking:

**Comment by Bouska** [comment]
Même après la résolution du problème de cache/job, ce centre n'apparaît toujours pas, le mystère s'épaissit. Il faudra que je refasse une passe dessus ce weekend.

**Comment by Bouska** [comment]
Après des tests complémentaires, ce centre est (faussement) considéré comme un doublon et est donc ignoré. Plus qu'à comprendre où est le bug dans la gestion des doublons.
