### ISSUE TITLE
Doses enfant non détectées

### ISSUE THREAD

**Issue by rozierguillaume** [CovidTrackerFr/vitemadose#683]
https://twitter.com/flight_behav/status/1484287015680188421?s=21

**Comment by fcamblor** [comment]
Plateforme : Doctolib
Centre : https://www.doctolib.fr/vaccination-covid-19/bruz/centre-de-vaccination-covid-19-bruz

Le lieu n'est pas trouvé (il n'apparaît pas dans la liste des centres dispo/indispo dans le JSON du 35)

Potentiellement lié à #680 ?

**Comment by fanetted** [comment]
Bonjour,
Dans le Rhône non plus, aucune dose enfant détectée. 
Cela fait 3 ou 4 jours que c'est comme ça.

Par exemple, pour Saint Bonnet de Mure
![image](https://user-images.githubusercontent.com/43910088/150546079-1bcbbb12-bc0c-4c80-ae6b-ee6cc66d302f.png)

Alors qu'il y a bien des doses enfants ici : https://www.doctolib.fr/vaccination-covid-19-pour-les-professionnels-medico-sociaux/genas/cpts-de-l-est-lyonnais-copsel?pid=practice-205103
![image](https://user-images.githubusercontent.com/43910088/150546228-8863c1b5-5a22-4ed4-89f8-c27535e109a3.png)

**Comment by nhumblot** [comment]
@fcamblor En première analyse, je dirais que la cause pour ce centre est différente de #680. Autant le centre de #680 n'est pas remonté par l'api des centres en Gironde, autant celui-là l'est.

**Comment by Bouska** [comment]
Après beaucoup de péripéties, le problème a été réglé aujourd'hui :partying_face:
