### ISSUE TITLE
Liens fournis par le gouvernement erronnées

### ISSUE THREAD

**Issue by baptistepl** [CovidTrackerFr/vitemadose#73]
Je ne sais pas si ce bug est en cours de résolution.

Certains liens de centre de vaccinations fournis par le gouvernement sont erronées, est-ce qu'il vaudrait mieux vérifier directement sur Doctolib les centres avec les RDV dispo ?

**Comment by aureliancnx** [comment]
On a pour objectif d’ajouter un scraper qui cherche les centres Doctolib qui ne sont pas présents / qui ont une mauvaise URL pour les ajouter en base

**Comment by baptistepl** [comment]
> On a pour objectif d’ajouter un scraper qui cherche les centres Doctolib qui ne sont pas présents / qui ont une mauvaise URL pour les ajouter en base

Ok nickel

**Comment by aureliancnx** [comment]
Référencé par l'issue https://github.com/CovidTrackerFr/vitemadose/issues/50
