### ISSUE TITLE
Mise à jour des statistiques non synchrone

### ISSUE THREAD

**Issue by rozierguillaume** [CovidTrackerFr/vitemadose#88]
Les statistiques ne semblent pas être mises à jour en même temps que la détection de créneaux

Ex ici : 4 centres en haut, 1 en bas

![image](https://user-images.githubusercontent.com/22763678/113841694-47c45280-9792-11eb-97b6-afff9886f9fb.png)

**Comment by aureliancnx** [comment]
Corrigé par https://github.com/CovidTrackerFr/vitemadose/commit/b9e46921eca983c5df0fd26ef9d394d1b0d43521

Ils n'étaient plus à jour suite à l'ajout de tests il y a peu, les fichiers rentraient en conflit
