### ISSUE TITLE
Deux motifs de réservation (Pfizer / Moderna) => second motif non détecté

### ISSUE THREAD

**Issue by Youps75** [CovidTrackerFr/vitemadose#90]
Exemple "Aucun Rendez-vous détecté" sur "Très grand centre du Stade de France" alors qu'il y en a plein sur le Motif "1ere injection (Moderna)".

Je pense que l'algo ne scan que le 1er motif.

**Comment by aureliancnx** [comment]
Non, on scanne bien le second motif, il s'agit d'un problème lié à l'API de doctolib

**Comment by aureliancnx** [comment]
Réglé
